- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/new_proposal.md
- .github/PULL_REQUEST_TEMPLATE.md
* Update issue templates
* Update templates
* Some cosmetic changes
* More wording
> Update issue templates (#6)

- README.md
- RFC/README.md
Tidy up README and move Documentation instructions to root README
> Tidy up README and move Documentation instructions to root README

- Cargo.lock
- infrastructure/storage/Cargo.toml
- infrastructure/storage/src/keyvalue_store.rs
- infrastructure/storage/src/lib.rs
- infrastructure/storage/src/lmdb.rs
This PR
This PR adds a `DataStore` trait that represents a generic key-value storage mechanism. As proof of concept, an LMDB implementation is also included
> Add storage abstraction and LMDB implementation

- .travis.yml
This PR
Travis should build RFC docs off `development` rather than master now that we've moved to git-flow development.
> Build RFCs off development branch

- .travis.yml
Align RFC deployment to github pages with RFC doc generation, by making both tasks run off develoment branch
This PR
Align RFC deployment to github pages with RFC doc generation, by making both tasks run off develoment branch
> Fix doc generation

- RFC/src/RFC-0110_BaseNodes.md
The RFC text was changed slightly to allow for mempool timelocks. Allowing transactions to only be marked as valid after a specific block height or timestamp has been reached.
> RFC-0110 - Added extra transaction state for mempool timelocks

- .travis.yml
This PR
Moving `deploy` section into `docs` stage so that it doesn't run for normal tests and break the docs build
> travis: move deploy job into docs stage

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/new_proposal.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR
changes this template
The current templates look fine for issues; for PRs, they're a bit clunky. 
The proposed changes put comments in HTML comments (so no need to delete them); reorders sections to prioritise the description; and modifies checklists to better represent use cases.
> make the PR and issue template a bit more ergonomic

- RFC/src/theme/css/variables.css
Quick CSS update for the RFC mdbook theme to improve code highlighting readability
Updated the styling
It was hard to read
just a CSS change
> Make RFC code highlight text colour lighter for readability

- .travis.yml
Add `on.branch` field to github pages deployment config
Github pages are not automatically being built after a merge
> Add development branch to deploy

- RFC/src/Glossary.md
- RFC/src/RFC-0110_BaseNodes.md
- RFC/src/RFC-0130_Mining.md
- RFC/src/RFC-0140 Syncing and seeding.md
- RFC/src/RFC-0140_Syncing_and_seeding.md
This PR adds in the syncing RFC
The cut-through was also moved to this RFC
Adds in the RFC for syncing
Fixes #73
> Sw Syncing RFC

- .circleci/config.yml
- .travis.yml
Added circle CI config which mirrors the current `travis.yml`.
We have more control over the build environment with Circle CI.
To deploy GitHub pages a deploy key with write access needs to be added to Circle CI (private key in pem format) and to GitHub (public key).
`ssh-keygen -m pem -t rsa -b 4096 -C "my@email.address"`
The key fingerprint must be added as a step before ghpages deploy as follows
```yaml
- add_ssh_keys:
fingerprints:
- "SO:ME:FIN:G:ER:PR:IN:T"
```
More Info:
https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/ 
https://circleci.com/docs/2.0/add-ssh-key/
I tested by activating Circle CI on my fork. https://circleci.com/gh/sdbondi/tari/44
> Circle CI config

- .circleci/config.yml
Deploys mdbook files in root of gh-pages branch
rfc.tari.com is broken
> Set dest flag to . for gh-pages

- infrastructure/crypto/src/keys.rs
- infrastructure/crypto/src/lib.rs
- infrastructure/crypto/src/macros.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- infrastructure/crypto/src/ristretto/ristretto_sig.rs
- infrastructure/crypto/src/ristretto/test_common.rs
- infrastructure/crypto/src/signatures.rs
Mostly what it says on the box.
Sone ergonomic / breaking changes:
* `Signature::sign` takes ownership of the secret and nonce, so you have to explicitly clone them beforehand if you want to re-use them. It's a bit less user friendly, but reduces the risk of bad things happening due to nonce re-use
* Added a macro (thanks dalek!) to generate all the `Add`, `Sub` and `Mul` variants.
This is much closer to the intent I had for this module initially. `SchnorrSignature` should only really be implemented once, and now it is! The `RistrettoSchnorr` file now contains one line: An alias type mapping the <P,K> types to the Ristretto pub/secret keys, and tests.
All existing tests pass
> Refactor Signature to use generic structs

- base_layer/blockchain/src/chain.rs
- base_layer/core/Cargo.toml
- base_layer/core/src/block.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/range_proof.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_builder.rs
- base_layer/core/src/types.rs
- infrastructure/crypto/Cargo.toml
- infrastructure/crypto/src/commitment.rs
- infrastructure/crypto/src/hash.rs
- infrastructure/crypto/src/lib.rs
- infrastructure/crypto/src/ristretto/pedersen.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
The PR implements the building blocks of a Mimblewimble Transaction. The data structures are implements and the basic methods for constructing a transaction are included. A method is provided to validate the sum of the components of the transaction against the provided kernel values taking into account the offset and fees.
Closes https://github.com/tari-project/tari/issues/128
Beginning of the functionality required for the TransactionBuilder described in https://github.com/tari-project/tari/issues/42
A unit test is provided to test the added functionality
> Implement basic transaction components

- .circleci/config.yml
Replaced `gh-pages` with a simple script 
`gh-pages` doesn't seem able to listen to it's `--dest` flag
I've run this successfully locally on the same docker quay.io image as used in circleci
> Replaced gh-pages with script

- Makefile
- infrastructure/crypto/src/commitment.rs
- meta/assets/rustdoc-include-katex-header.html
Use a trick from the Dalek libraries to include KateX.js in the reference docs for this project.
This change allows LaTeX markeup to be rendered in our docs, like so:
Added a small example equation in `HomomorphicCommitment` to illustrate the principle.
> Add LaTex markup rendering to Docs

- RFC/src/RFC-0301_NamespaceRegistration.md
Updated RAID_ID generation and TXT record specifications, presented real example in RFC
Previous RFC was still WIP
Used online resources:
https://8gwifi.org/MessageDigest.jsp
https://incoherency.co.uk/base58/
https://crccalc.com/
Used Python [**test program**](https://gist.github.com/hansieodendaal/721db88197b6b8ff1683f5748e7e9e44) (forked from [**CjS77**](https://gist.github.com/CjS77/9dc02ef008522ce0a7d5357551010726)) to generate RAID_ID
Used small RistrettoSchnorr [**test program**](https://github.com/hansieodendaal/crypto_playpen) to generate the keys and sign the RAID_ID
> RFC-0301_NamespaceRegistration

- base_layer/core/src/transaction.rs
- infrastructure/crypto/src/common.rs
- infrastructure/crypto/src/musig.rs
- infrastructure/crypto/src/ristretto/musig.rs
- infrastructure/crypto/src/ristretto/pedersen.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- infrastructure/crypto/src/ristretto/ristretto_sig.rs
By convention, if a function returns a reference, it is called `as_xxx`.
The ByteArray implementation called this `to_bytes`; so renaming it
to fit with the convention.
Keep with Rust convention. It reduces confusion for newcomers to the project
Fixes #106 
> Follow the Rust convention for `as_bytes`

- base_layer/core/src/transaction.rs
- base_layer/core/src/types.rs
- infrastructure/crypto/src/commitment.rs
- infrastructure/crypto/src/ristretto/pedersen.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
HomomorphicCommitment is refactored to abstract away the static reference to the Commitment
base without compromising on the ability to build commitments with different generator bases.
The explicit dependency on the `Scalar` from the Dalek library is also removed, which removes
the leaky abstraction that was present in the existing implementation.
The references to `base` that were being carried in `Transaction` structs can also now be
removed.
> Refactor `HomomorphicCommitment`

- RFC/src/RFC-0311_AssetTemplates.md
MDBook does not render `||` in table rows properly, so replace them with the unicode ‖ (double bar)
Broken rendering in mdbook
> Replace double bars in table

- infrastructure/tari_util/Cargo.toml
- infrastructure/tari_util/src/chacha20.rs
- infrastructure/tari_util/src/cipher.rs
- infrastructure/tari_util/src/lib.rs
- Added cipher encoding and decoding trait for vec<u8>
- Added implementation of ChaCha20 stream cipher.
- Added unit tests for testing encoding and decoding system
Making secure backups of the KeyManager requires encoding and decoding using a stream or block cipher.
New unit tests were developed that test the encoding and decoding mechanism
Close #203
> Cipher encoding and decoding using ChaCha20

- infrastructure/comms/Cargo.toml
- infrastructure/comms/src/peer_manager/mod.rs
- infrastructure/comms/src/peer_manager/node_id.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- Added NodeId and NodeDistance structs and functions
- Added unit test for creating a NodeID from a public key and measuring closeness using XOR metric.
- Added Hashable implementation for RistrettoPublicKey
NodeID is used to provide the location of a node on the communication network. Measuring the distance between different NodeIDs is important to perform efficient node discovery and message forwarding.
Unit tests were developed that test the newly introduced structs and functions.
Closes #213
> Implement NodeID (Messaging)

- base_layer/core/src/transaction.rs
- base_layer/core/src/types.rs
Removing `Option`s from `TransactionKernel` provides stringer guarantees about data integrity when building blocks and passing TX data around.
Code is also cleaner because checks for `is_some()` aren't necessary anymore.
However, we now require a "Builder" struct while collecting Kernel information. This adds some boilerplate but is a good tradeoff to grab the
benefits describes above.
Part of #42
> Kernel builder

- base_layer/core/src/block.rs
- base_layer/core/src/transaction.rs
- infrastructure/crypto/src/signatures.rs
Kernel sorting was temp removed from the code, but now an efficient ordering mechanism
has been implemented on `SchnorrSignature` that allows Ord to be derived on TransactionKernel.
This ordering does not require `2n.ln(n)` hash operations, but in most cases zero, and occasionally
a few `to_hex` conversions if signature public nonces are equal for whatever reason.
> Sort kernels

- base_layer/core/src/block.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/pow.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/mod.rs
- base_layer/core/src/transaction_protocol/receiver.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/src/transaction_protocol/test_common.rs
- base_layer/core/src/transaction_protocol/transaction_initializer.rs
This PR closes #42.
@philipr-za did most of the work here; this is largely a re-org of his code and generalisation to permit multi-receivers in future.
Implement the Sender side of the Tari transaction protocol using a finite state machine
cargo doc inserts `<p>` tags in paragraphs, so insert comments in the    mermaid diagram to keep formatting clear and still produce the correct    output
Add a test (and fix the bugs) for a single sender and recipient   including one with no change and one with change
All that remains is to integrate range proofs!
Receiver will need to figure out whether they're in a single- or multi-round    transaction
* Clean up unused imports
* Add some colour to RecipientProtocol
* Add docstrings and tests for `ReceiverTransactionProtocol`
Tari needs Transactions. …
> Tari transactions

- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
Originally a new RangeProofService was created for each transaction range proof verification. When verifying large batches of transactions it would be faster to create a single instance of a service and pass it in. This PR adds an Option<&RangeProofService> parameter to the verification methods so that if an RPS is provided it will be used or else a new one will be created. 
This parameter was set to None for all the transaction builder functions as this optimization is intended for batch verification of large sets of existing transactions and will not be a large overhead during the construction of a single transaction.
Tests have been updated to use this parameter. Tests use both pass in an RPS and pass in None to test both cases.
> Allow RangeProofService to be passed in for transaction verification

- Cargo.lock
- base_layer/core/Cargo.toml
We shouldn't explicitly depend on the dalek libraries in the domain layer
> Drop dalek dependency in tari_core

- comms/Cargo.toml
- comms/src/connection/peer_connection/connection.rs
- comms/src/connection/peer_connection/context.rs
- comms/src/connection/peer_connection/error.rs
- comms/src/connection/peer_connection/mod.rs
- comms/src/connection/peer_connection/worker.rs
- comms/tests/connection/peer_connection.rs
This PR adds the connection id frame as the first frame on the consumer side of the PeerConnection. This will be used to map connections to peers.
Related #293 - We'll likely only need to connection ID added as the first frame without other metadata. 
The expected ID frame is checked on the consumer side in existing tests.
> Send connection ID as first frame to consumer connection

- infrastructure/storage/src/keyvalue_store.rs
- infrastructure/storage/src/lmdb.rs
There needs to be a general way to release resources from Datastores.
LMDBStore recently implemented this in #303 ; now it is included in the trait
> Close datastore

- comms/src/connection/connection.rs
- comms/tests/connection/connection.rs
- comms/tests/connection/peer_connection.rs
This is a fix for flaky connection tests. This change sets connections to linger for as long as they need to complete sending. 
Should fix failing tests like this one: https://circleci.com/gh/tari-project/tari/1458
`while true;do cargo test||break; done` was not able to produce a failure in comms tests with the fix
> Allow connections in tests to linger to complete sending

- comms/Cargo.toml
- comms/src/lib.rs
- comms/src/outbound_message_service/mod.rs
- comms/src/outbound_message_service/outbound_message.rs
- The OutboundMessageService creates the OutboundMessage that it writes to the outbound message pool. The OutboundMessages can then be retrieved from the pool by the ConnectionManager so that they can be sent to peers.
- This struct tracks send attempts, creation timestamps, retry timestamps and has a copy of the MessageEnvelope.
Required by OutboundMessageService and ConnectionManager
A unit test was added
> OutboundMessage

- comms/src/connection/connection.rs
- comms/src/connection/dealer_proxy.rs
- comms/src/connection/mod.rs
- comms/src/connection/types.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/outbound_message_service/outbound_message.rs
Small abstraction of zmq proxy which is used in inbound message service. This may also be needed elsewhere (e.g. ControlService). The proxy requires `Connection` to be able to bind with an Inbound direction, so I've added another property to connections which allows you to optionally select the way the socket establishes connections (`Bind`, `Connect` or `Auto`(default))
Related to #247 
Tests for spawn proxy - inbound message service tests remain the same
> Abstraction of zmq::proxy

- RFC/src/RFC-0314_AssetDiscovery.md
- RFC/src/SUMMARY.md
Asset discovery is simple enough that it can fall under the Tari Collections API
RFC.
Closes #88
> Remove asset discovery RFC

- comms/Cargo.toml
- comms/src/connection/message.rs
- comms/src/lib.rs
- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/outbound_message.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/node_identity.rs
- comms/src/types.rs
- infrastructure/crypto/src/keys.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- infrastructure/crypto/src/signatures.rs
- Added the OutboundMessageService with unit test
- Added the BroadcastStrategy enum
- Added a NodeIdentity container
- Added DiffieHellmanSharedSecret trait to Crypto
Handler functions use the OutboundMessageService to send messages to peers. The OutboundMessage service will receive messages from handlers, apply a broadcasting strategy, encrypted and serialized the messages into OutboundMessages and write them to the outbound message pool.
A unit test was added for the OutboundMessageService.
> OutboundMessageService

- comms/src/connection/net_address/net_address_with_stats.rs
- comms/src/connection/net_address/net_addresses.rs
- comms/src/connection/zmq/curve_keypair.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
It looks like Rust can already be reusing memory by the time the address is checked after being zeroed.
e.g. see this code
```
use rand::rngs::OsRng;
use rand::Rng;
use std::slice;
use std::mem;
use std::ptr;
pub struct Zeroed([u8; 32]);
impl Drop for Zeroed {
fn drop(&mut self) {
let size = mem::size_of_val(self);
unsafe {
let ptr = self as *mut Self;
ptr::write_bytes(ptr as *mut u8, 0, size);
}
println!("In Drop: {:?}", self);
}
}
fn main() {
let zero = &vec![0u8; 32][..];
let mut rng = OsRng::new().unwrap();
let ptr;
{
let mut k = [0u8;32];
rng.fill(&mut k);
let foo = Zeroed(k);
println!("Value: {:?}", foo);
ptr = foo.0.as_ptr();
println!("Address before: {:?}", ptr);
unsafe { assert_eq!(slice::from_raw_parts(ptr, 32), k); }
}
unsafe {
assert_eq!(slice::from_raw_parts(ptr, 32), zero); …
```
> Fix broken tests in release mode

- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
Used MPSC channels to exhaustively test all the worker threads in in the `inbound_message_service` unit tests.
The test didn't test the fair dealing aspect of the message service, now it explicitly tests the dealing of messages to the workers in addition to testing that the dispatcher handle is called.
It is a test.
> Improve inbound_message_service test

- comms/src/peer_manager/node_id.rs
Tests are more future proof now if the key type ever changes
> Use keys as specified in types.rs

- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/types.rs
- Added Random and Closest peer selection to PeerManager
- Modified Closest BroadcastStrategy to allow broadcasting to any nodes closes peers.
- Corrected the OMS to use a Arc instead of a RwLock for the PeerManager
Last missing pieces for the BroadcastStrategy
Tests have been added
> BroadcastStrategy: Selecting Random and Closest peers

- comms/Cargo.toml
- comms/src/connection/mod.rs
- comms/src/connection/net_address/net_addresses.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/message_pool_worker.rs
- comms/src/outbound_message_service/mod.rs
- comms/src/outbound_message_service/outbound_message.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
The Outbound Message Pool (OMP) fields requests to send OutboundMessages from the various OutboundMessageService's (OMS's) in the system. OMS's assemble the OutboundMessages to be sent and then write them to the OMP's inbound InProc address which acts as a queue. The OMP spins up a series of workers to which the messages are fairly dealt and each worker will attempt to send the message, if it has failed it will requeue the message to the OMP queue to be attempted again in the future.
Currently the OMP is almost done, all the threading, worker logic and queuing is done. it is just waiting on the ConnectionService to be completed to actually attempt to make connection and attempt to transmit the message.
Waiting on https://github.com/tari-project/tari/issues/195
Related to issue …
> Added initial portion of OutboundMessagePool

- comms/src/connection_manager/manager.rs
- comms/src/macros.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/support/helpers/connection_message_counter.rs
@philipr-za Identified a race condition in connection manager when a new peer connection is being requested at the same time by two or more threads. This results in the connection being established twice. This fix locks the connection establishment code for a given node id ensuring that only one connection establishment per node id can occur simultaneously.
Updated the connection manager test to use two threads that simultaneously request a peer connection. The updated test failed until after this fix was applied.
> Fix race condition when establishing a connection to a single peer

- comms/src/connection/mod.rs
- comms/src/connection/net_address/mod.rs
- comms/src/connection/net_address/net_address_with_stats.rs
- comms/src/connection/net_address/net_addresses.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
When attempting a connection to a Peer the ConnectionManager will attempt to contact all NetAddress associated with that peer for a set amount of attempts before giving up. If you want to try connect to that Peer again at a later stage you need to reset the connection_attempt stats to allow another attempt. This PR enabled that.
Closes #365 
Tests have been provided
> Implemented resetting connection_attempts to all net_addresses in a peer

- comms/src/connection/error.rs
- comms/src/connection/monitor.rs
- comms/src/connection/net_address/mod.rs
- comms/src/connection/peer_connection/error.rs
- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/message_pool_worker.rs
- comms/src/outbound_message_service/mod.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/mod.rs
- comms/tests/outbound_message_service/mod.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
The Outbound Message Pool (OMP) fields requests to send OutboundMessages from the various OutboundMessageService's (OMS's) in the system. OMS's assemble the OutboundMessages to be sent and then write them to the OMP's inbound InProc address which acts as a queue. The OMP spins up a series of workers to which the messages are fairly dealt and each worker will attempt to send the message, if it has failed it will requeue the message to the OMP queue to be attempted again in the future.
Closes #325 
Unit and Integration tests provided
> Completed Outbound Message Pool

- base_layer/core/src/block.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/src/transaction_protocol/test_common.rs
- base_layer/core/src/transaction_protocol/transaction_initializer.rs
- base_layer/core/src/types.rs
- base_layer/wallet/src/transaction_manager.rs
Added additional coinbase constructer function
Renamed Type::SecretKey to Type::PrivateKey because we already have a SecretKey trait
The current coinbase function in the block builder might not be very usefull. The new one only takes a SecretKey in as parameter to construct the coinbase.
> Block builder additional coinbase constructer function

- base_layer/core/Cargo.toml
- base_layer/core/src/lib.rs
- base_layer/core/src/tari_amount.rs
By subtyping Tari amounts (MicroTari in particular), we can prevent silly bugs
by letting the Rust compiler statically check all arithmetic using Tari values
> Introduce Tari amounts

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/ping_pong.rs
- comms/Cargo.toml
- comms/src/builder/builder.rs
- comms/src/connection/connection.rs
- comms/src/connection/dealer_proxy.rs
- comms/src/connection/peer_connection/mod.rs
- comms/src/inbound_message_service/error.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/message_pool_worker.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- Changed DealerProxy to allow shutdown. of dealer and make use of proxy_steerable
- Update IMS, OMS and Workers to allow safe shutdown using Control Messages
- Modified tests to demonstrate safe shutdown
Shutdown of threads and dealers were unsafe
Tests were modified
> Allow OMS, IMS and OMP to shutdown cleanly

- base_layer/keymanager/src/keymanager.rs
- comms/Cargo.toml
- comms/src/connection/net_address/net_address_with_stats.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/peer.rs
- infrastructure/crypto/src/ristretto/serialize.rs
- infrastructure/tari_util/src/hex.rs
NodeId will now be de/serialized to/from hex, by implementing ByteArray. I moved the serialize_to_hex function from tari_crypto to tari_utilities as the same function can be used for serialization in that crate. I was not able to do the same for deserialization. 
NodeId was serializing to json as an array while public key was a hex string. This change makes the serialization of peers consistent. 
Peer serialization to json tested
> NodeId de/serialized to/from hex

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/macros.rs
- base_layer/p2p/tests/ping_pong.rs
- base_layer/wallet/src/wallet.rs
- comms/src/connection_manager/establisher.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/handlers.rs
- comms/src/control_service/service.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/tests/connection_manager/establisher.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/control_service/service.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
`control_service_establish_timeout` in `PeerConnectionConfig` is not needed
`requested_outbound_connection_timeout` added to `ControlServiceConfig` to remove hardcoded value
Added some more checks to `ConnectionAttempt` in `ConnectionManager` to ensure that failures to connect (inbound or outbound) result in a failure being reported.
Fixed some warnings
Reviewing some of the code in connection manager revealed that the config was a little off. 
Existing tests updated and pass
> Change in connection manager and control service configs

- base_layer/p2p/tests/ping_pong.rs
- comms/src/builder/builder.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/service.rs
- comms/src/control_service/types.rs
- comms/src/control_service/worker.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
- comms/src/message/envelope.rs
- comms/src/message/message_context.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/node_identity.rs
- comms/src/peer_manager/peer.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/control_service/service.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- comms/tests/support/factories/connection_manager.rs
- comms/tests/support/factories/node_identity.rs
Removed the redundant public key type param from `NodeIdentity`. Serde
required type annotations to serialize the secret key (was `PK::K`). I
tried explicitly adding trait bounds for `PK::K` but it seems that
serde's proc macro has a limitation for handling associated types.
Existing tests compile and pass
> Removed generic type param from NodeIdentity

- comms/src/builder/builder.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/error.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/message_pool_worker.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- Removed threading from the InboundMessageService
- Added a config to the InboundMessageService and InboundMessageWorker
- Added the control_timeout_in_ms to the config of the InboundMessageService and OutboundMessageService
- Renamed InboundMessageService to InboundError so it is similar to OutboundError from the OutboundMessageService. Also, inbound_address is now message_queue_address like the OutboundMessageService
- Removed unused results from the constructors of the InboundMessageService and OutboundMessagePool
- The InboundMessageService and InboundMessageWorker tests were updated 
This will reduce the complexity of the InboundMessageService, which might result in improved reliability.
The InboundMessageService and InboundMessageWorker tests were updated
> Remove ImboundMessageService threading

- base_layer/p2p/examples/pingpong.rs
- comms/src/connection/monitor.rs
- comms/src/connection/net_address/i2p.rs
- comms/src/connection/net_address/ip.rs
- comms/src/connection/net_address/mod.rs
- comms/src/connection/net_address/onion.rs
- comms/src/connection/peer_connection/connection.rs
- comms/src/connection/peer_connection/control.rs
- comms/src/connection/peer_connection/worker.rs
- comms/src/connection/zmq/inproc_address.rs
- comms/src/connection_manager/establisher.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/error.rs
- comms/src/control_service/handlers.rs
- comms/src/control_service/worker.rs
The outbound control port connection would drop the attached connection
monitor before the connection terminates, which causes the connection to
stop working. This is likely the cause of test flakiness in establish_peer_connection_by_peer
Additional changes:
- [bug] Ensure that the address sent to the target peer's control port
is the external host of the node.
- [bug] Correctly handle an existing peer establishing a new connection
- Some peer connection unit tests
- More logging
Used the pingpong example to test sending messages back and forth between two laptops.
> Fixed "dropping monitor" bug in connection manager

- comms/src/connection/connection.rs
- comms/src/connection/dealer_proxy.rs
- comms/src/connection/types.rs
- comms/src/connection_manager/establisher.rs
- comms/src/control_service/worker.rs
- comms/tests/connection_manager/manager.rs
A few pauses are currently needed in tests to ensure that the control
service has enough time to start up and peer connections can finish sending. Also fixed a bug in
ConnectionAttempts, some minor cosmetic changes and logging improvements.
Using (short) pauses never guarantee an end to flakiness and make tests run slowly, but this should greatly improve the reliability of this test.
In future we should consider some basic ready signals so that pauses won't be needed.
> Improve establish_peer_connection test reliability

- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
It's possible that these IP addresses will hit a firewall in circle CI
which cause the connection to "hang" for an extended period of time.
This PR changes those to use the local loopback address.
> Removed 1.2.3.4 IP addresses in OMS tests

- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/mod.rs
- base_layer/p2p/src/services/service.rs
- base_layer/p2p/src/tari_message.rs
- base_layer/p2p/tests/ping_pong.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/macros.rs
- base_layer/wallet/src/text_message_service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/support/mod.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- base_layer/wallet/tests/text_message_service/text_message_service.rs
- comms/src/builder/builder.rs
- comms/src/connection/net_address/net_address_with_stats.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/message/message.rs
This PR implements a Text Message Service that can:
- Send text messages via the comms stack
- Receive text messages and send an acknowledgement of receipt
- Update the status of sent messages from pending to sent when an acknowledgement is received.
Currently TMS keeps all of the state in memory, added a persistence backend will be done in a later issue.
The TMS was added along with the PingPong service to the Wallet API.
Closes Issue #190 
Tests were provided for the TMS and Wallet API
> Implemented TextMessageService and added it to the Wallet API

- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/wallet/src/text_message_service.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- comms/src/builder/builder.rs
- comms/src/message/message.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
Sending a message through the OMS changed from this:
```rust
oms.send(
BroadcastStrategy::DirectPublicKey(text_message.dest_pub_key.clone()),
MessageFlags::ENCRYPTED,
Message::try_from(text_message)?.to_binary()?,
)?;
```
To this:
```rust
oms.send_message(
BroadcastStrategy::DirectPublicKey(text_message.dest_pub_key.clone()),
MessageFlags::ENCRYPTED,
text_message,
)?;
```
In either case you need to implement `TryInto<Message>` (or `TryFrom<YourMessage> for Message`) for your message type.
Renamed getters in CommsServices as per rust [checklist recommendations](https://rust-lang-nursery.github.io/api-guidelines/checklist.html)
Remove serialization concern from the domain service, it should be the OMS's responsibility
> OMS send api ergonomic improvement

- comms/src/connection/dealer_proxy.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
The dealer proxy was silently erroring when being sent the TERMINATE
command from the control socket. The [zmq docs](http://api.zeromq.org/4-1:zmq-proxy-steerable) indicate that a PUB/SUB socket pair should be used. 
Tests fail with the shutdown result used. After the use of PUB/SUB they pass.
> Fixed DealerProxy shutdown

- comms/benches/connection/peer_connection.rs
- comms/src/builder/builder.rs
- comms/src/connection/dealer_proxy.rs
- comms/src/connection/peer_connection/worker.rs
- comms/src/control_service/worker.rs
- comms/src/inbound_message_service/error.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/message_pool_worker.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- comms/tests/support/comms_patterns.rs
- comms/tests/support/helpers/connection_message_counter.rs
- Added ability to change allocated thread stack size to PeerConnection, DealerProxy, Peer connection worker, Control service worker, InboundMessageWorker, MessagePoolWorker, AsyncRequestReplyPattern and ConnectionMessageCounter.
- Manually selected thread stack sizes for each service/worker that are 3-4x larger than the size that caused a stack overflow error.
- The minimum stack size allocated was 16kb.
Rust allocates a default 2mb stack for each thread, much smaller stack sizes can be used for the light threads used by many of the workers and services.
Existing tests will produce a stack overflow error if the allocated stack size was insufficient
> Limit stack size of light worker threads

- scripts/code_coverage.sh
Increasing code coverage on the tari project
LLVM automatically inlines some function to improve performance, I have reduced this so that grcov can see more functions and more correctly report on the lines hit metric. 
More accurate reporting on lines of code hit metric
> Decreased LLVM inline to improve grcov code viewing

- .gitignore
- applications/grpc_wallet/Cargo.toml
- applications/grpc_wallet/proto/wallet_rpc.proto
- applications/grpc_wallet/sample_config/node1_peers.json
- applications/grpc_wallet/sample_config/node2_peers.json
- applications/grpc_wallet/sample_config/wallet_config_node1.toml
- applications/grpc_wallet/sample_config/wallet_config_node2.toml
- applications/grpc_wallet/src/grpc_interface.rs
- applications/grpc_wallet/src/main.rs
- applications/grpc_wallet/src/wallet_server.rs
- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/wallet/src/text_message_service.rs
- base_layer/wallet/src/wallet.rs
This PR provides the binary for the gRPC wallet server. This includes the command line switches, support for config files and support for loading peer data from json files.
Also adds one CRUD to the gRPC interface to return the current nodes public key.
Closes https://github.com/tari-project/tari/issues/457
No tests as this is just the binary.
> Implement the binary interface for the grpc-wallet server

- base_layer/p2p/examples/pingpong.rs
Quick PR to allow the pingpong example to optionally set the log config
path. This helped me debug two pingpong nodes, by separating the log output files for each.
> PingPong example gets log config from cli arg

- base_layer/core/src/block.rs
- base_layer/core/src/chain.rs
- base_layer/core/tests/mod.rs
- base_layer/core/tests/support/mod.rs
- base_layer/core/tests/support/simple_block_chain.rs
Very basic chain builder for the unit tests. It currently only does coinbase UTXOs and then a new block
This provides a chain builder for integration tests to build a chain of blocks. All blocks currently only have a coinbase UTXO. 
This will be used by all unit and integration tests for the block chain.
Unit tests testing that the blocks follow on each other with block height increasing.
> Very basic chain builder for the unit tests

- comms/src/connection/dealer_proxy.rs
- comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs
- comms/src/peer_manager/peer_manager.rs
The OutboundMessageWorker notifies the MessageRetryService once a
message has been successfully sent to a peer. The MessageRetryService in
turn flushes all the messages it destined for that peer to be sent by
the worker.
Ref #325 
Ref #461 
Unit and integration tests
> Failed messages sent as soon as peer is sendable

- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/p2p/examples/pingpong.rs
Using the loopback address in tests so that we don't get annoying firewall popups while
running them ;)
> Use loopback address in tests

- applications/grpc_wallet/sample_config/node2_peers.json
- applications/grpc_wallet/sample_config/node3_peers.json
- applications/grpc_wallet/sample_config/wallet_config_node3.toml
- applications/grpc_wallet/src/main.rs
Added a third config file and peer to demo the grpc_wallet interface.
Also added the -N switch to the binary to be able to quickly specify a config file pair using an integer switch i.e. -N 1 to use the node 1 configs when running from the Tari repo root.
e.g. cargo run --bin grpc_wallet_server -- -N 1
Make demo easier.
Nope
> Add a third grpc_wallet_server config file for demo purposes

- comms/src/connection/dealer_proxy.rs
The dealer proxy tests had a race condition when testing if the dealer
proxy was no longer accepting connections. If after shutdown, the sender
connection could still send, the test would pass, otherwise the test may
block indefinitely on the `send_sync` (`send` would return an error if
unable to send).
Since the shutdown would error if it timed out (i.e. the proxy steerable does
not respond), I feel it's pretty redundant to try send afterwards as we already 
know in the test that the proxy call has returned.
Ref #455
> Removed race condition in dealer proxy test

- base_layer/core/src/block.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/tests/support/simple_block_chain.rs
The simple block chain thats supposed to be used for testing only created new blocks with coinbase UTXO. It can now spend UTXO's with the each block.
This allows for a much clearer blockchain to do testing on. 
Unit test looking at the chain that was constructed. The unit test is currently disabled because of #473
> Added transactions to the block chain builder

- comms/src/connection/net_address/mod.rs
- comms/src/connection/net_address/net_addresses.rs
Adding an existing address to NetAddresses should not result in an
error.
> Make NetAddresses::add_net_address idempotent

- comms/src/connection/net_address/mod.rs
- comms/src/connection/net_address/net_addresses.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/handlers.rs
- comms/src/message/p2p/mod.rs
- comms/tests/control_service/service.rs
public key is now solely obtained from the message envelope header.
Branched from #483 
It was redundant to have a field for the public key in the EstablishConnection message.  
Existing tests updated
> Remove redundant public key field from Establishconnection message

- comms/tests/connection_manager/establisher.rs
- comms/tests/connection_manager/manager.rs
Tests should have ample time to complete successfully
> Timeout for joins is a bit short when run in CI

- comms/src/connection/connection.rs
- comms/src/connection/peer_connection/worker.rs
Allow the connection to set the following
[socketopts](http://api.zeromq.org/4-2:zmq-setsockopt#toc17)
- zmq_hearbeat_ttl
- zmq_hearbeat_timeout
- zmq_hearbeat_ivl
And set these on the PeerConnection. This ensures that peer connections
remain active when no traffic is sent/received for an extended period.
ref #445 
Socket ops unit tests
> Allow heartbeat to be set on Connections

- base_layer/core/src/block.rs
- base_layer/core/src/fee.rs
- base_layer/core/src/tari_amount.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/mod.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/src/transaction_protocol/test_common.rs
- base_layer/core/src/transaction_protocol/transaction_initializer.rs
- base_layer/core/tests/support/simple_block_chain.rs
- base_layer/wallet/src/transaction_manager.rs
All fees and amounts where just u64. This was all refactored to the microtari newtype struct
By having the amounts just as u64, it makes it easy to assume its just Tari and get the magnitude wrong which could cause significant issues. 
All unit tests are still passing
> Refactored all fee as MicroTari struct and not u64 anymore

- comms/src/control_service/types.rs
- comms/src/control_service/worker.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/message/envelope.rs
- comms/src/outbound_message_service/outbound_message_service.rs
Removed generic public key from MessageEnvelopeHeader in favour of
CommsPublicKey.
This generic could not be used in the comms crate and this change cuts down on some generics cruft. 
Existing tests updated and pass
> Remove generics from MessageEnvelopeHeader

- comms/src/peer_manager/peer_storage.rs
- infrastructure/storage/src/key_val_store/error.rs
- infrastructure/storage/src/key_val_store/key_val_store.rs
- infrastructure/storage/src/key_val_store/lmdb_database.rs
- infrastructure/storage/src/key_val_store/mod.rs
- infrastructure/storage/src/lib.rs
- infrastructure/storage/src/lmdb_store/store.rs
- infrastructure/storage/tests/lmdb.rs
- Renamed LMDBDatabase delete, size and exist functions to be similar to HashMap naming convention and so that those names can be used by the KeyValStore trait
- Added new KeyValStore trait that has a similar interface to LMDBDatabase
- Added KeyValStoreError used by new KeyValStore trait
- Implemented KeyValStore for LMDBDatabase 
This trait will make it easier to switch to a HashMap implementation when persistent storage is not required, such as during testing.
New test added.
> New KeyValStore trait and LMDBDatabase implementation for trait

- infrastructure/storage/src/key_val_store/error.rs
- infrastructure/storage/src/key_val_store/hmap_database.rs
- infrastructure/storage/src/key_val_store/mod.rs
- This PR has a dependency on PR #490 
- Added HMapDatabase that can be used as a replacement for LMDBDatabase where persistent storage is not required.
- Also provided an implementation of the KeyValStore for the HMapDatabase to make switching between LMDBDatabase and HMapDatabase easier.
Tests can rather use the HMapDatabase and not the LMDBDatabase as no persistent storage is required.
New Test was added
> HMapDatabase with KeyValStore implementation

- comms/src/builder/builder.rs
- comms/src/connection_manager/manager.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/error.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/types.rs
- infrastructure/storage/src/key_val_store/error.rs
- infrastructure/storage/src/key_val_store/hmap_database.rs
- infrastructure/storage/src/key_val_store/mod.rs
- Changed PeerStorage to use the new KeyValStore trait
- Changed tests in comms to use the HMapDatabase instead of LMDBDatabase
The persistence storage of LMDBDatabase is not required during testing. Sometimes the Database files are not properly cleared between different test runs and could potentially result in some tests failing.
The behaviour seems to be the same as all current tests that made use of LMDBDatabase still produce the same results after HMapDatabase has been integrated
> Replace LMDBDatabase with HMapDatabase in Comms

- applications/console_text_messenger/Cargo.toml
- applications/console_text_messenger/src/main.rs
libpnet was added to replace local-ip in the console_text_messenger application. 
See: [https://crates.io/crates/pnet/](https://crates.io/crates/pnet/)
The application now loops through available network interfaces, finds an available interface which is not a loopback interface and which also has an IPV4 address. If none is found the application is terminated.
libpnet has support for both windows and unix, fixes a TODO in the code.
Multiple terminal windows were run with different configurations (N1,N2,..) to ensure the application still functions correctly as it did prior to the change.
> Changed local_ip to pnet

- comms/src/control_service/worker.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/message/envelope.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/utils.rs
Moved verify signature into MessageEnvelopeHeader so that
MessageEnvelope doesn't have to deserialize the header to verify.
Small optimisation of message signature verification
Split up a few unit tests and added a new one specifically for signature verification
> Remove need to double deserialize EnvelopeHeader to verify msg signature

- infrastructure/crypto/src/ristretto/ristretto_keys.rs
Implement `fmt::Display` as a hex representation of a Ristretto public
key. This can be used to display the public key instead of the Debug
implementation and dramatically cuts down on log clutter.
Unit tested
> Implement Display for RistrettoPublicKey

- comms/src/connection/net_address/net_addresses.rs
A single NetAddress can be accessed using: `addresses[0]`. This is
expected behaviour for a collection.
> Added Index impl for NetAddresses

- comms/src/connection/peer_connection/control.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
Join timeouts are set too low and cause TimeoutReached errors on
CircleCI. 3000ms chosen to give more than ample time.
Ref #441 
> Increase join timeouts (flakiness)

- RFC/src/RFC-0315_AssetTransfer.md
- RFC/src/SUMMARY.md
Transfers are a privilege, not a right ;)
There is no requirement that assets be transferable, therefore this shouldn't be
a generic RFC, but soemthing that is left to the individual templates to
implement.
Closes #90
> Remove RFC-315

- base_layer/p2p/tests/ping_pong/mod.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- infrastructure/storage/tests/lmdb.rs
The logs in CI are exceeding circle ci's maximum number of log lines
and are cluttering test output. When debugging, you can add
`simple_logger::init()` to the test you are debugging. This will
also emit a warning which would remind you to remove it afterwards.
In future, we may want logs in CI tests to write to a file and which can be
later inspected as an [artifact](https://circleci.com/docs/2.0/artifacts/).
Makes test output nice and clean
N/A
> Remove logging from tests

- base_layer/p2p/src/ping_pong.rs
- base_layer/wallet/src/text_message_service.rs
Removed some large log debug output from RistrettoPublicKey in text
message service and ping pong service
Depends on #516 
Logs will be less cluttered 
N/A
> Remove Debug RistrettoPublicKey from log output

- comms/src/connection/connection.rs
- comms/src/connection/peer_connection/control.rs
- comms/src/connection/peer_connection/worker.rs
- comms/tests/connection/peer_connection.rs
0MQ suggest that a low or zero linger is set before disconnecting.
+ Minor improvements to peer connection logs.
http://api.zeromq.org/2-1:zmq-setsockopt#toc15
> Set 0 linger on peer connection when dropped 

- applications/grpc_wallet/src/grpc_interface.rs
- base_layer/p2p/src/services/service.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/diesel.toml
- base_layer/wallet/migrations/2019-06-26-130555_initial/down.sql
- base_layer/wallet/migrations/2019-06-26-130555_initial/up.sql
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/text_message_service/error.rs
- base_layer/wallet/src/text_message_service/mod.rs
- base_layer/wallet/src/text_message_service/model.rs
- base_layer/wallet/src/text_message_service/service.rs
This PR implements models and diesel based Sqlite backend for persistence of all the data required by the Text Message Service. 
Only the models and backend are provided thus far, it has not yet been plumbed into the TMS service logic in order to reduce this PRs size. That will be done in the next PR.
Related to https://github.com/tari-project/tari/issues/429
Unit tests are provided
> Implement Sqlite backend for Text message service

- comms/src/connection/net_address/net_addresses.rs
- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/mod.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/error.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- Modified Closest Broadcast strategy to have peer exclusions.
- Changed Closest and Random peer functions to return all available peers up to the requested number, without throwing an insufficient peers errors.
- Added Test for new functionality.
- Added ability to update the NetAddresses without discarding usage stats.
- Added ability to update a peers NodeID, Flags and NetAddresses.
- Added exists method to check if peer exists in the PeerManager.
These changes are need for sending and receiving DHT join requests
New tests have been added
> Peer exclusions on closest peers and Peer Updating

- comms/tests/connection/monitor.rs
Fixes problem with the test for ZMQ V4.3.2+.
Fixes problem with the test for ZMQ V4.3.2+. Requires ZMQ V4.3.2+
Fixes problem with the test for ZMQ V4.3.2+.
cargo test --all
> Fixed test for ZMQ V4.3.2+

- .circleci/config.yml
Migrate to the new Rust Build image that includes all deps,
inc libzmq, sqlite, clang (and more in future)
> Update docker image for Circle CI

- comms/Cargo.toml
- comms/src/consts.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/message_cache.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/lib.rs
- Added DuplicateMsgCache for detecting and discarding duplicate inbound messages.
- Integrated The DuplicateMsgCache into the InboundMessageWorker.
- Modified InboundMessageService and InboundMessageWorker tests to not send duplicate messages.
- Added extra tests to check that the detection and discarding of duplicate messages work correctly.
With the propagation of messages on the DHT, the same message can be received from multiple peers.
Only the first one should be processed and the rest should be discarded.
This is important for the functioning of the DHT, otherwise peers will get stuck in an endless loop attempting to send join requests to each other.
Test were modified and new tests were added
> Discard duplicate inbound messages

- infrastructure/merklemountainrange/Cargo.toml
- infrastructure/merklemountainrange/src/lib.rs
- infrastructure/merklemountainrange/src/merkle_change_tracker.rs
- infrastructure/merklemountainrange/src/merklemountainrange.rs
- infrastructure/merklemountainrange/tests/unit/mmr_rewinding.rs
Adds Croaring dependancy to the MMR. 
Adds a roaringbitmap to track the unspent UTXO's inside the mmr. 
Adds a call to get the hash of the roaringbitmap. 
We require some way to track to the UTXO's and not just the TXO's
See IRC discussion: https://www.tari.com/2019/07/15/tari-protocol-discussion-42.html
Added unit tests to test the roaring bitmap as well as rewinding them.
> Add roaring bitmap to the mmr so we can track the UTXO's

- comms/src/connection/peer_connection/connection.rs
- comms/src/connection/peer_connection/mod.rs
- comms/src/connection/peer_connection/worker.rs
- comms/tests/connection/peer_connection.rs
Added some basic PeerConnection protocol messages implemented as a
frame containing a single `u8`:
- `Identify` (`0u8`): The outbound connection is identifying itself (as in ZMQ identity) to the
inbound connection. This message MUST be sent by an outbound connection
before any others (this now happens automatically inside an outbound PeerConnection).
- `Message` (`1u8`): The peer is sending a domain message, which should be
forwarded downstream to the IMS.
- `Invalid`: Every other value is treated as invalid and ignored (in
future, this could effect ban heuristics)
Currently, the control service has to send a (pretty useless) domain-level message to the remote peer before both sides of the peer connection can say they are connected. This change will move that message to the peer …
> Added PeerConnection level protocol messages

- comms/src/outbound_message_service/error.rs
- comms/src/outbound_message_service/outbound_message_pool/error.rs
- comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs
- comms/src/outbound_message_service/outbound_message_pool/mod.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_pool/outbound_message_worker.rs
- comms/tests/outbound_message_service/message_retry_service.rs
Changed the MessageRetryService to use a mpsc channel as part of a
larger refactor away from inprocs and a more stable OMP.
Messages:
`Shutdown` - Shut the MessageRetryService down
`AttemptFailed(OutboundMessage)` - Add the failed message to the retry queue
`Flush(NodeId)` - Flush all message for a given Node ID and queue for sending
Part of a larger refactor of the OMP to use concurrency primitives (channels, work stealing) rather than Zmq inprocs. 
Ref #445 
Unit tested behaviour for all types of `RetryServiceMessage`s, updated existing tests where applicable.
> Message retry service using mpsc channel

- comms/src/control_service/client.rs
- comms/src/control_service/worker.rs
- comms/src/domain_connector.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/message/error.rs
- comms/src/message/message.rs
- comms/tests/connection_manager/establisher.rs
Included a nonce in MessageHeader to distinguish multiple requests from duplicate messages
Currently, when multiple duplicate messages are received from different peers only the first one will be processed. Messages from different requests might look the same, resulting in only the first one being processed. Adding a nonce in the header will eliminate the misclassification of duplicate messages.
Test was modified
> Added nonce to MessageHeader

- base_layer/p2p/src/consts.rs
- base_layer/p2p/src/dht_service/dht_messages.rs
- base_layer/p2p/src/dht_service/dht_service.rs
- base_layer/p2p/src/dht_service/mod.rs
- base_layer/p2p/src/lib.rs
- base_layer/p2p/tests/dht/mod.rs
- comms/src/domain_connector.rs
- Added ability to send join messages and handle received join requests
- Added initial join DHT message struct
- Implemented propagation of join messages
- Added test for join propagation
The join request is used to inform neighbouring peers in the network about the identity and contact details of a new node.
A new test has been addded.
> Sending and handling DHT join requests

- comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs
- comms/tests/connection_manager/establisher.rs
Theory goes: Circle CI shared infra will have widely varying
performance depending on current load. Timeouts should allow
enough time to complete.
Ref #445
> Increase timeout on sporadically failing tests

- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/src/main.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/services/error.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/tests/dht/mod.rs
- base_layer/p2p/tests/ping_pong/mod.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- comms/src/builder/builder.rs
- comms/src/outbound_message_service/outbound_message_pool/message_retry_service.rs
The ServiceExecutor does not need to own the Arc<CommsServices>.
This change removes the constraint that all comms services need to be Sync.
Specifically, the mpsc::Receiver is !Sync which will come into play
in the coming OMP refactor PR.
Prerequisite for #562  
Existing tests compile. Tests now need to hold onto the CommsServices so that it doesn't drop prematurely.
> Removed CommsServices ownership from ServiceExecutor

- base_layer/p2p/src/dht_service/dht_messages.rs
- base_layer/p2p/src/dht_service/dht_service.rs
- base_layer/p2p/src/dht_service/error.rs
- base_layer/p2p/src/dht_service/mod.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/tests/dht/mod.rs
- base_layer/wallet/src/text_message_service/service.rs
- comms/src/builder/builder.rs
- comms/src/consts.rs
- comms/src/control_service/client.rs
- comms/src/control_service/worker.rs
- comms/src/domain_connector.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/message/domain_message_context.rs
- comms/src/message/envelope.rs
- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- Added ability to send and handle DHT discover requests
- Added forwarding mechanic of private messages in comms handlers
- Added forward and discover Broadcast Strategies
- Added DiscoverMessage type
- Added forward_message function to OutboundMessageService
- Added a test where two nodes discover each other through peer nodes
- Made changes that allows the current nodes identity to be retrieved like an api or service 
- Modified MessageEnvelopeHeader so that it specifies the origin source and peer source and have signatures for both
- Changed signature verification to check the origin and peer signature
Closes #501, #502 and partially closes #499
This will allow unknown nodes to discover each other using neighbouring peer nodes.
New tests have been added
> Send and handle DHT Discover requests

- base_layer/p2p/tests/dht/mod.rs
- base_layer/p2p/tests/ping_pong/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
```
error[E0412]: cannot find type `TariMessageType` in this scope
--> base_layer/p2p/tests/dht/mod.rs:68:62
|
68 | ) -> (ServiceExecutor, Arc<DHTServiceApi>, Arc<CommsServices<TariMessageType>>)
|                                                              ^^^^^^^^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
|
24 | use tari_p2p::tari_message::TariMessageType;
|
error[E0412]: cannot find type `TariMessageType` in this scope
--> base_layer/p2p/tests/ping_pong/mod.rs:72:23
|
72 |     Arc<CommsServices<TariMessageType>>,
|                       ^^^^^^^^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
|
25 | use tari_p2p::tari_message::TariMessageType;
|
```
> Fix compile error that snuck into development

- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/keymanager/Cargo.toml
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/output_manager_service.rs
- base_layer/wallet/tests/mod.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/support/utils.rs
This PR adds the backend of the Wallet’s output manager service that maintains the list of spent and unspent outputs for the wallet. The service contains the following functionality:
- Keeps track of unspent and spent UnblindedOutputs
- Maintains the Wallet’s Key Manager to produce keys for sending and receiving outputs
- Produce SenderTransactionProtocols by selecting outputs based on a specified strategy
- Keep track of PendingTransactions and their constituent outputs
- Allow for the Confirmations of the transactions which moves Outputs into the Spent/Unspent lists respectively
- Allow for cancellation of transactions
- Allow for timeout of transactions
Closes https://github.com/tari-project/tari/issues/553
Tests provided
> Implement a wallet Output Manager Service

- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/tests/dht/mod.rs
- comms/src/builder/builder.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- Modified in_network_region to work for unknown NodeIDs
- Added a test for the in_network_region function
- Fixed merge issue on development
The in_network_region function is used by the DHTService and for message forwarding
A test has been added
> Improve in_network_region to work for unknown NodeIds

- base_layer/p2p/src/services/executor.rs
- comms/tests/support/factories/macros.rs
- comms/tests/support/helpers/connection_message_counter.rs
- comms/tests/support/makers/node_id.rs
Removed some unused functions where appropriate.
Comms test support can have dead code as factories are meant to expose
all the ways to build a component regardless of whether it happens to be called 
by tests or not.
> Fixed all warnings on comms test support (+ fix development compile fail)

- base_layer/p2p/src/services/executor.rs
- comms/src/connection/peer_connection/connection.rs
- comms/src/connection/peer_connection/context.rs
- comms/src/connection/types.rs
- comms/src/connection_manager/connections.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/establisher.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/repository.rs
- comms/tests/connection/peer_connection.rs
- comms/tests/connection_manager/manager.rs
ConnectionManager now limits the number of peer connections to
`PeerConnectionConfig::max_connections`.
If the number of active connections is reached, one of two scenarios
exist:
- if this node is initiating the connection, the connection which has
seen the least recent activity is dropped in favour of the new
connection.
- if another node is initiating the new peer connection through the control service, existing
connections are preferred and the new connection is denied.
Closes #385 
New unit tests
> Limit number of active peer connections

- base_layer/core/src/block.rs
- base_layer/core/src/transaction.rs
Nearly all the transaction validation code currently in `Transaction`
involves references to `self.body.some_field`. This suggests that
it should really live in `AggregateBody`.
As it stands _block_ validation code has to do some yucky copying
to get at the same code (blocks have an AggregateBody, not a
Transaction).
This PR moves all the validation code into `AggregateBody` which
both cleans up the code smell, and allows a more efficient and
ergonomic call through to validation code when validating `Block`s
> Move transaction validation code from `Transaction` to `AggregateBody`

- infrastructure/merklemountainrange/Cargo.toml
- infrastructure/merklemountainrange/benches/bench.rs
- infrastructure/merklemountainrange/src/merkle_change_tracker.rs
- infrastructure/merklemountainrange/src/merklemountainrange.rs
- infrastructure/merklemountainrange/src/merklenode.rs
- infrastructure/merklemountainrange/tests/support/testobject.rs
- infrastructure/merklemountainrange/tests/unit/examples.rs
1. This PR fixes a criterion benchmark that was not enabled.
2. Upgraded the benchmarks to rust 2018
3. Fixed a bug in the MMR change checker
#
1. The benchmark did not work do to a bug in the MMR code, more details below in 3.
2. The current code in the benchmarks was not fully in rust 2018, this was upgraded to full 2018 code, also removed the serde-derive crate from the MMR as the serde trait has this built in now.
3. The MMR change checker had a bug in it that allowed you to select a too small pruning horizon. the pruning horizon has to be 2 or larger. This is how the change checker rewrites and merges older checkpoints to create new combined checkpoints. if the pruning horizon is below 2 there is no older checker to rewrite. This was fixed be enforcing the pruning horizon to be 2 or …
> Fix MMR benchmark

- infrastructure/crypto/Cargo.toml
- infrastructure/crypto/benches/mod.rs
- infrastructure/crypto/benches/range_proof.rs
- infrastructure/crypto/benches/signatures.rs
This PR adds a few small benches for the Dalek Range proof module.
Some refactoring on the `benches` folder was required to allow
the tests to be split into several files
New benchmarks:
```
Generate range proofs/8 
time:   [2.3685 ms 2.3853 ms 2.4022 ms]                                     
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) low mild
2 (2.00%) high mild
2 (2.00%) high severe
Generate range proofs/16                                                                             
time:   [4.1531 ms 4.1979 ms 4.2501 ms]
Found 8 outliers among 100 measurements (8.00%)
2 (2.00%) high mild
6 (6.00%) high severe
Generate range proofs/32                                                                             
time:   [7.3179 ms 7.3504 ms 7.3888 ms]
Found 1 outliers among …
```
> Add benchmarks for Range Proofs

- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/dht_service/dht_service.rs
- base_layer/p2p/src/dht_service/error.rs
- base_layer/p2p/tests/dht/mod.rs
- base_layer/p2p/tests/ping_pong/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/error.rs
- comms/src/control_service/worker.rs
- comms/src/peer_manager/node_identity.rs
- comms/tests/control_service/service.rs
- comms/tests/support/factories/node_identity.rs
- The DHTService will join the network on service start and on detection of control_service_address change
- Added test for new join mechanisms
- Modified control_service worker to not add but replace the control_service_address
- Changed NodeIdentity to allow changing of the control_service_address
- Modified node identity factory to use the NodeIdentity constructor
Node will automatically inform neighbouring nodes of latest control_service_address.
New test has been added
> DHT network join on startup and control_service_address change

- base_layer/core/src/blockchain/block_chain_state.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/tests/support/simple_block_chain.rs
1. I updated the Blockheaders to now include rangeproofs in them. We currently commit to the rangeproofs in a MMR. 
2. I have also changed the TXO commitment to include the UTXO commitment. 
1. This was discussed on IRC: https://www.tari.com/2019/07/18/tari-protocol-discussion-43.html
2. This was discussed on IRC: https://www.tari.com/2019/07/15/tari-protocol-discussion-42.html
> Update blockheaders to include rangeproofs and utxo commitments

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/executor/handle.rs
- base_layer/p2p/src/executor/mod.rs
- base_layer/p2p/src/lib.rs
`ChannelServiceHandle` should be the most commonly used
handle for a service. It is used to send requests
on a given unbounded mpsc sender and produce a future which
should resolve to a response.
Ref #654 
Unit tests (added dev-dependency tokio_mock_task)
> Added basic async request-reply handle for #654

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/consts.rs
- base_layer/p2p/src/saf_service/error.rs
- base_layer/p2p/src/saf_service/saf_messages.rs
- base_layer/p2p/src/saf_service/saf_service.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/tests/mod.rs
- base_layer/p2p/tests/saf/mod.rs
- comms/src/builder/builder.rs
- comms/src/connection/peer_connection/worker.rs
- comms/src/connection_manager/manager.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/message/message_context.rs
- comms/src/message/message_data.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- comms/tests/connection/peer_connection.rs
- Implemented the Store-and-forward service functions: send_retrieval_request, receive_retrieval_request, receive_stored_messages and store_message
- Modified service executor and connection manager to provide access to the IMS message_sink_address and zmq_context
- Added a Store-and-forward test
- Added a forwardable field to MessageData to enable and disable the forwarding of a messages by the comms stack. Disabled forwarding of a message in the comms_msg_handlers when this field is set.
- Added exists_node_id function to peer_manager
The Store-and-forward service will allow peers to send messages between each other even if they are not online at the same time.
A Store-and-forward test has been added
> Implement store and forward service

- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/tests/dht/mod.rs
- base_layer/p2p/tests/ping_pong/mod.rs
- base_layer/p2p/tests/saf/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- comms/src/builder/mod.rs
- comms/src/connection_manager/mod.rs
- comms/src/control_service/mod.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/types.rs
- comms/tests/connection_manager/establisher.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/control_service/service.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- infrastructure/storage/src/key_val_store/hmap_database.rs
- infrastructure/storage/src/key_val_store/key_val_store.rs
- infrastructure/storage/src/key_val_store/lmdb_database.rs
- infrastructure/storage/src/lmdb_store/store.rs
As it stands, the `KeyValStore` trait has some pretty restrictive constraints
on it, inlcuding the very ugly dependency on an LMDB type.
There's no reason to impose these constraints, actually. Every implementation
is free to impose additional constraints to limit its applicability.
The main change of this PR is to remove the bounds on the `K` and `V`
generics in the trait, and shift them up into the implementations.
This allows us to use `KeyValStore` as a backend trait in e.g.
MerkleMountainRange without having to carry things like `AsLMDBBytes`
into the MMR crate :O
It also lets us massively simply the `HMapDatabase` type (no serialisation
required!)
So, two big wins!!
But..it makes things a little messy with LMDB.
There's a conflict between where the Generic specifications (K,V) live. …
> Refactor KeyValStore trait to be less restrictive

- base_layer/mmr/Cargo.toml
- base_layer/mmr/src/error.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/tests/MutableMmr.rs
Part II of the MMR refactor focusing on ergonomics, composability and performance.
Unlike a pure MMR, which is append-only, in `MutableMmr`, leaf nodes can be marked as deleted.
In `MutableMmr` a roaring bitmap tracks which data have been marked as deleted, and the merklish root is modified
to include the hash of the roaring bitmap.
The `MutableMmr` API maps nearly 1:1 to that of MerkleMountainRange so that you should be able to use it as a
drop-in replacement for the latter in most cases.
> Add Mutable MMR Datastructure

- base_layer/mmr/src/error.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/src/pruned_hashset.rs
- base_layer/mmr/src/pruned_mmr.rs
- base_layer/mmr/tests/merkle_mountain_range.rs
- base_layer/mmr/tests/mutable_mmr.rs
- base_layer/mmr/tests/pruned_mmr.rs
- base_layer/mmr/tests/support/mod.rs
Part 3 of an MMR refactor focusing on ergonomics and performance.
This PR leverages the ArrayLike trait to provide a very elegant implementation
of a pruned MMR. See notes in `pruned_hashet` for details.
Also as part of this, the `VectorBackend` implementation of `ArrayLike` is deprecated in favour of just implementing `ArrayLike` straight onto `Vec<T>`.
The test file `MutableMmr` was renamed to `mutable_mmr`; it looks like Github didn't notice the rename.
> Add support for Pruned MMRs

- comms/Cargo.toml
- comms/src/pub_sub_channel.rs
The waker/sleeper from the bus_queue crate turns out to be more efficient
than using `task::current().notify()` which will cause the subscriber poll
function to spin.
TODO: consider contributing some benchmarks & tests to bus_queue as it appears
this project will be using it in several places
Ref #621 
> Using original bus_queue implementation

- base_layer/p2p/src/services/comms_outbound/handle.rs
- base_layer/p2p/src/services/liveness/error.rs
- base_layer/p2p/src/services/liveness/messages.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
This PR adds an async replacement for the sync pingpong service. IT uses
the CommsOutboundService to send pings. Inbound ping and pong messages
are not read from the comms layer, this will be in a subsequent PR.
Ref #673 
Ref #621  
Unit tests
> Added Async Liveness (PingPong) Service

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/executor/handles/future.rs
- base_layer/p2p/src/executor/handles/lazy_service.rs
- base_layer/p2p/src/executor/handles/mod.rs
- base_layer/p2p/src/executor/mod.rs
- base_layer/p2p/src/executor/stack.rs
- base_layer/p2p/src/services/comms_outbound/mod.rs
- base_layer/p2p/src/services/domain_deserializer.rs
- base_layer/p2p/src/services/liveness/error.rs
- base_layer/p2p/src/services/liveness/handler.rs
- base_layer/p2p/src/services/liveness/messages.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/mod.rs
- base_layer/p2p/src/sync_services/service.rs
- comms/src/domain_subscriber.rs
- LivenessHandler connected up to a stream of PingPong messages
- Refactored the way services are initialized, keeping it super simple
and to allow more flexibility
Tari Services are one or more (usually) long-running asynchronous tasks which furnish request via a provided interface (called a Handle). Dropping the handle must cancel the task. This is (usually) implemented using an mpsc channel and/or subscription stream. That is, once all senders have disconnected, the receiver stream will close and so will the task. Services usually subscribe to one or many comms messages and update state or perform operations as necessary.
Services are set up by implementing the ServiceInitializer trait - this trait can be passed to the StackBuilder which is responsible for initializing the services and …
> Connected LivenessService to comms pub/sub

- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/src/test_utils/builders.rs
- base_layer/core/src/test_utils/mod.rs
The mempool test module has some useful utility function for building
test blocks and transactions that will be very useful for other modules;
For that reason I've moved the `create_text_transaction` and associated
helper functions to a separate module, and updated the mempool tests
to use them.
> Move mempool tests to tests folder

- base_layer/p2p/src/services/domain_deserializer.rs
- comms/src/builder/builder.rs
- comms/src/builder/mod.rs
- comms/src/domain_subscriber.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/message/domain_message_context.rs
- comms/src/message/message_context.rs
DomainMessageContext no longer makes sense for what it's being used for.
InboundMessage is better.
> Renamed DomainMessageContext to InboundMessage

- base_layer/core/src/consts.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/pending_pool/error.rs
- base_layer/core/src/mempool/pending_pool/mod.rs
- base_layer/core/src/mempool/pending_pool/pending_pool.rs
- base_layer/core/src/mempool/pending_pool/pending_pool_storage.rs
- base_layer/core/src/mempool/priority/error.rs
- base_layer/core/src/mempool/priority/mod.rs
- base_layer/core/src/mempool/priority/prioritized_transaction.rs
- base_layer/core/src/mempool/priority/timelocked_transaction.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool_storage.rs
- comms/src/message/envelope.rs
- Added the implementation of PendingPool and PendingPoolStorage
- Added tests for PendingPool
- Renamed TxPriority to FeePriority and Moved FeePriority and TimelockPriority to priority folder
- Extend the create_test_tx and create_test_block functions to allow testing of transaction lock_height
Note: This only implements the Transaction Time-locks and doesn't yet enforce the time-locks on the spending of input UTXOs.  
The Pending Pool contains all transactions that are restricted by time-locks.
New tests have been added
> Pending Pool

- base_layer/core/src/consts.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/pending_pool/pending_pool.rs
- base_layer/core/src/mempool/reorg_pool/mod.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- Added implementation of ReorgPool 
- Added ReorgPool unit tests
- Modified OrphanPool to rather store and return an Arc to each transaction.
The ReorgPool consists of all transaction that have recently been added to blocks. When a potential blockchain reorganization occurs, the transactions used to construct these discarded blocks can be recovered from the ReorgPool and can be added back into the UnconfirmedPool. 
New tests have been added.
> Reorg Pool

- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/sync_services/executor.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service.rs
- comms/Cargo.toml
- comms/src/builder/builder.rs
- comms/src/domain_subscriber.rs
- comms/src/inbound_message_service/inbound_message_publisher.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/pub_sub_channel.rs
In this PR the comms crate is updated to use the new Futures 0.3. This was done while keeping the interface used by domain level services consistent but required some work to make the modules using Futures 0.1 be able to use the new futures stuff.
Closes https://github.com/tari-project/tari/issues/708
Closes https://github.com/tari-project/tari/issues/690
Tests have been provided and updated
> Update Comms crate to use Futures 0.3

- base_layer/core/src/blocks/block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/src/chain_storage/transaction.rs
- base_layer/core/src/proof_of_work/blake_pow.rs
- base_layer/core/src/proof_of_work/difficulty.rs
The pruning horizon is an important and general piece of metadata that informs
users of BlockchainDatabases where full storage of blockchain history begins.
The pruning horizon is used in synchronisation requests and block data requests
(e.g. from explorers).
Given that this is the 3rd piece of metadata, the fetch method is DRYd up to
eliminate a bunch of repeated code.
* Cleans up `read_metadata` by using a macro to clean out boilerplate
* Allows the setting of a pruning horizon. BAckend can use this as a
hint to delete older data
* Clean up some compiler warnings
> Pruning horizon metadata

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
The wrong height was used to fetch the best block header when
adding a new block to the BlockchainDB.
This is fixed; ands a new test has been added that catches the
old bug and now passes.
> Fix best_block check bug

- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/error.rs
- base_layer/core/src/mempool/orphan_pool/mod.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/mempool/pending_pool/pending_pool.rs
- base_layer/core/src/mempool/pending_pool/pending_pool_storage.rs
- base_layer/core/src/mempool/priority/prioritized_transaction.rs
- base_layer/core/src/mempool/priority/timelocked_transaction.rs
- base_layer/core/src/mempool/reorg_pool/error.rs
- base_layer/core/src/mempool/reorg_pool/mod.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool_storage.rs
- base_layer/core/src/test_utils/builders.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/sender.rs
- Added min_input_maturity, max_input_maturity and max_timelock_height member functions to transactions
- Removed "mut" requirements for some of the member functions of blockchain_database
- Separated OrphanPool and PendingPool into an Interface and Storage sections with RwLocks
- Changed OrphanPool to have a reference to the BlockchainDatabase so it can correctly query the UTXO set
- Added snapshot and calculate_weight functions to the UnconfirmedPool, OrphanPool, PendingPool, and ReorgPool
- Modified FeePriority to include the oldest maturity of the input UTXO
- Modified TimelockPriority to correctly use the Transactions lock_height and UTXO maturity
- Modified create_test_tx and create_test_block to create more validly constructed transactions and blocks
- Added create_test_input for …
> Improvements to UnconfirmedPool, OrphanPool, PendingPool, and ReorgPool

- base_layer/mmr/src/backend.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/src/pruned_hashset.rs
- base_layer/mmr/tests/pruned_mmr.rs
Changed ArrayLike and ArrayLikeExt to rather return owned copies. This change was required to simplify the integration of LMDB for blockchain storage.
> Changed ArrayLike and ArrayLikeExt to return owned copies

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/error.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/mmr/src/error.rs
- base_layer/mmr/src/mutable_mmr.rs
- Implemented fetch_mmr_proof and added utxo_and_rp_mmr_proof, header_mmr_proof and kernel_mmr_proof tests
- Added fetch_mmr_only_root to the BlockchainBackend trait, this function will return the root without the roaring bitmap contribution, it is needed for verifying proofs.
- Changed fetch_mmr_proof to rather require a usize instead of u64 as the for_leaf_node function of MerkleProof uses a usize
- Exposed the MerkleMountainRange of the MutableMmr to allow the calculation of proofs using MerkleProof::for_leaf_node function
fetch_mmr_proof is used to construct a merkle proof for the specified merkle mountain range and the given leaf position.
New tests have been added.
> Implement fetch_mmr_proof for MemoryDatabase

- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/error.rs
- base_layer/core/src/chain_storage/historical_block.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/test_utils/builders.rs
- Added rewind_to_height function to BlockchainDatabase and a test for new functionality, this function can be used to rewind the blockchain state to the specified block height.
- Added RewindMmr WriteOperation to MemoryDatabase
- Added unspend_stxo function to DbTransaction to move an STXO to the UTXO set.
- Added rewind_header_mmr, rewind_kernel_mmr, rewind_utxo_mmr and rewind_rp_mmr to DbTransaction for rewinding the MMRs by the specified number of Checkpoints.
- Added an accessor function to HistoricalBlock to allow access to its Block.
- This new functionality allows the extra tests from the Mempool reorg test to be enabled. 
Enables the rewinding of the blockchain state to the specified block height.
The rewind_to_height test was added.
> BlockchainDatabase rewind_to_height

- base_layer/p2p/examples/pingpong_async.rs
- base_layer/p2p/src/services/comms_outbound.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/service_framework/Cargo.toml
- base_layer/service_framework/src/initializer.rs
- base_layer/service_framework/src/stack.rs
- comms/src/builder/builder.rs
Changed the kind of executor passed into ServiceInitailizers from `&mut TExec`
to TaskExecutor. TaskExecutors can be cheaply cloned and passed around.
The tokio runtime has the blocking thread pool which is desirable for
CPU-bound tasks which services will run.
Ref #705 
Ref #727 
> Changed services to use tokio runtime

- comms/src/domain_subscriber.rs
- comms/src/inbound_message_pipeline/inbound_message_pipeline.rs
- comms/src/message/inbound_message.rs
- comms/src/message/mod.rs
The destination will be used in domain middlewares and services.
`domain_message_context` module renamed to `inbound_message`
> Added destination field to InboundMessage

- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/pending_pool/pending_pool.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/src/test_utils/builders.rs
Add a convenient and ergonomic wrapper for the `spend_utxo` function
Builds on #758
> Spend macro

- base_layer/wallet/migrations/2019-06-26-130555_initial/up.sql
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/text_message_service/model.rs
- ffi/Cargo.toml
- ffi/src/lib.rs
- ffi/src/test.rs
Added boolean field to SentTextMessage.
Extended FFI to return additional fields for ReceivedTextMessage.
Extended FFI for SentTextMessage.
Added boolean field isread to SentTextMessage in Model, Schema and Migration.
Added Test to SentTextMessage for Mark_Sent_Message_Opened method.
Implemented Ord and PartialOrd for SentTextMessage.
Extended FFI to return additional fields for ReceivedTextMessage.
Extended FFI for SentTextMessage.
Useful field to include, differentiates between a message being delivered and the message being processed.
FFI needed to be extended to account for Sent messages, Received messages needed to be able to return additional fields.
cargo test --all
> Added field to SentTextMessage, extended FFI

- base_layer/p2p/src/domain_subscriber.rs
- base_layer/p2p/src/lib.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/sync_services/error.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service.rs
- comms/src/lib.rs
- DomainMessage<T> improves ergonomics of working with incoming messages
- Moved domain_subscriber as part of an effort to remove MType from
comms and to allow for "add-ons"/middleware for incoming and outgoing
messages
Ref #675 
Ref #761 
> Replaced (MessageInfo, T) tuple with DomainMessage

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- Implemented handle_possible_reorg and handle_reorg for detecting potential reorgs, constructing reorg chains and updating the main chain with higher accumulated difficulty reorg chains.
- Added the handle_reorg test for testing the reorg functionality of the BlockchainDatabase.
- Added for_each_orphan function to BlockchainBackend and MemoryDatabase to allow access to each orphan block in the orphan pool.
- Changed update_metadata to allow the updating of the chains total accumulated difficulty and made use of Difficulty instead of u64.
- Added fetch_header_with_block_hash to BlockchainDatabase to enable the retrieval of block headers using the block hash.
- Fixed an issue with rewind_to_height where the metadata was not correctly updated.
- Note: the changes to the futures was …
> Implement handle reorg and possible reorg for BlockchainDatabase

- comms/middleware/src/inbound_connector.rs
- comms/middleware/src/lib.rs
- comms/middleware/src/message.rs
- comms/middleware/src/pubsub.rs
- comms/middleware/tests/stack.rs
Small change removing unnecessary coupling of inbound domain message
middleware and pubsub.
InboundDomainConnector deserializes domain-level header, assembles a
domain-level message and sends that along a given sink.
`pubsub_service` simply connects a pubsub Publisher and the
InboundDomainConnector
Flow from comms middleware to domain services
`mpsc send DomainMessage<MType> >-- mpsc receive and forward to TopicPublisher --< received by domain-level subscribers`
Ref #761
> Decoupling of pubsub and domain-level messages

- comms/dht/src/inbound/decryption.rs
- comms/dht/src/inbound/deserialize.rs
- comms/dht/src/inbound/dht_handler/layer.rs
- comms/dht/src/inbound/dht_handler/message.rs
- comms/dht/src/inbound/dht_handler/middleware.rs
- comms/dht/src/inbound/dht_handler/mod.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/inbound/error.rs
- comms/dht/src/inbound/forward.rs
- comms/dht/src/inbound/message.rs
- comms/dht/src/inbound/mod.rs
This PR adds the vaious inbound DHT middleware components.
The module is currently not part of the module tree as
there are a number of changes to the comms and tari_middleware
crates that need to go along with it.
_Overview of middleware architecture_
The `tari_comms_dht` crate adds DHT functionality to `tari_comms`.
It provides two sets of middleware (_inbound_ and _outbound_) which
process incoming requests and outgoing messages respectively.
_Attaching to comms_
In `tari_comms`, incoming and outgoing messages are connected using two mpsc sender/receiver pairs.
One for incoming messages (receiving `InboundMessage`s) and one for outbound messages (sending `OutboundMessage`s).
The DHT module consists of two middleware layers (as in `tower_layer::Layer`) which form
an inbound and outbound …
> Inbound DHT middleware

- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/broadcast_strategy.rs
- comms/dht/src/outbound/encryption.rs
- comms/dht/src/outbound/error.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/mod.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/outbound/serialize.rs
This PR adds the vaious outbound DHT middleware components.
The module is currently not part of the module tree as
there are a number of changes to the comms and tari_middleware
crates that need to go along with it.
Overview of middleware architecture
The tari_comms_dht crate adds DHT functionality to tari_comms.
It provides two sets of middleware (inbound and outbound) which
process incoming requests and outgoing messages respectively.
Attaching to comms
In tari_comms, incoming and outgoing messages are connected using two mpsc sender/receiver pairs.
One for incoming messages (receiving InboundMessages) and one for outbound messages (sending OutboundMessages).
The DHT module consists of two middleware layers (as in tower_layer::Layer) which form
an inbound and outbound pipeline for …
> Outbound DHT middleware

- infrastructure/test_utils/src/lib.rs
- infrastructure/test_utils/src/paths.rs
These are useful when creating temporary database paths which are (still) needed for peer manager.
- cargo_path returns the path to the cargo manifest dir
- database_path returns the test data path
- create_random_database_path creates a random path in the database_path and return it
> Add path helpers to tari_test_utils (DRYer tests)

- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/mmr/src/backend.rs
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/error.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/merkle_proof.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/src/pruned_hashset.rs
- base_layer/mmr/tests/change_tracker.rs
- base_layer/mmr/tests/merkle_mountain_range.rs
- base_layer/mmr/tests/merkle_proof.rs
- base_layer/mmr/tests/mutable_mmr.rs
- base_layer/mmr/tests/pruned_mmr.rs
- base_layer/mmr/tests/with_blake512_hash.rs
- Modified ArrayLike trait so that the len and get methods return results, this change was made so that errors can be properly handled when implementing ArrayLike for non-memory backends.
- The BackendPushError was replaced with BackendError in MerkleMountainRangeError
These changes are required to make the MerkleChangeTracker have persistent storage.
Current test were updated to accommodate the change.
> Changed ArrayLike to return results

- base_layer/core/src/transaction.rs
This PR adds optional kernel fields that will be required by the some of the scripts. 
The one field is for a linked kernel, this is required for relative time locks.
The other field is for a meta_info, which is so that contract data can be checked by a challange without knowing what the contract data is. This will be used by the DAN etc.  
#740 
This breaks none of the unit tests and these are optional fields
> Add optional kernel data

- base_layer/p2p/src/initialization.rs
- comms/src/builder/builder.rs
- comms/src/lib.rs
- comms/src/outbound_message_service/mod.rs
- comms/src/outbound_message_service/service.rs
- comms/tests/outbound_message_service/service.rs
- OMS now keeps a small set of active connections so that they can be
reused without querying connection manager. This improves performance
when some connections are pending while new messages are incoming for
peers that are already connected.
- Added a shutdown signal for OMS to ensure it shuts down timeously
Ref #692 
Expanded test to test for connection reuse
> OMS concurrency improvements

- Cargo.toml
- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/src/lib.rs
- applications/grpc_wallet/src/main.rs
- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/utils.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/text_message_service/error.rs
- base_layer/wallet/src/text_message_service/messages.rs
- base_layer/wallet/src/text_message_service/mod.rs
- base_layer/wallet/src/text_message_service/model.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/support/data.rs
- base_layer/wallet/tests/support/utils.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- ffi/src/lib.rs
This PR converts the TMS to be async and use the Service Framework to be able to be compassable into domain service stacks. The TMS is now able to directly connect to pub_sub channels from the Comms layer and a Requester handle is provided that will be used as the API interface to the service from the application and other services. The Diesel db backend calls have been wrapped as Blocking futures as they are disk I/O bound. 
This PR comment out the FFI, GRPC_Wallet, Console Text Messenger application and removed the Liveness aspect in the TMS as it was causing trouble with the current version of the Comms stack which is undergoing a major refactor. Rather than fixing this now and then redoing it when the Comms stack is stable I decided to pull these items out and then return them when …
> Convert the Text Message Service to by Async

- base_layer/core/src/test_utils/primitives.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/mod.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/src/transaction_protocol/transaction_initializer.rs
This PR adds optional kernel fields to the challenge as well. 
The challenge will take the fields into consideration if the fields are filled in
#740 
This breaks none of the unit tests and these are optional fields
> Sw add extra kernel challenge

- base_layer/core/Cargo.toml
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_vec.rs
- base_layer/core/src/chain_storage/lmdb_db/mod.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/chain_storage/test/mod.rs
- base_layer/core/tests/data/.gitkeep
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/tests/change_tracker.rs
- infrastructure/storage/src/lmdb_store/store.rs
- Added LMDBDatabase chain storage backend with helper functions to perform lmdb operations
- Added LMDBVec that can be used as a persistent backend for the MerkleChangeTracker
- A set of tests for testing only the backend functionality of memory_db and lmdb_db was added under chain_backend tests
- A custom serializer  and deserializer was added for MerkeCheckPoint, this was required as croaring bitmap doesn't implement serialize and deserialize.
Note: The persistent storage of the MerkleChangeTrackers needs to be improved so that only a single WriteTransaction is used, this will also allow a single lmdb commit to be performed once all the changes have successfully been set.
The Blockchain state requires persistent storage
A set of backend tests were added.
> Initial LMDB BlockchainBackend implementation

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/text_message_service/error.rs
- base_layer/wallet/src/text_message_service/handle.rs
- base_layer/wallet/src/text_message_service/mod.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/tests/support/utils.rs
- base_layer/wallet/tests/text_message_service/mod.rs
This PR implements an event stream for the text message service using the tari_broadcast_channel. This makes it easier for other services and tests to listen for any events occurring in the service efficiently. This is then used to make the TMS tests not require synchronous polling code.
Closes https://github.com/tari-project/tari/issues/816
Using thread::sleep while polling async code is apparently bad practice to implementing the async event stream to make testing easier and for more efficient communication between services.
Tests updated
> Implement an Event Stream for the Text Message Service

- base_layer/p2p/examples/pingpong_async.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/utils.rs
- base_layer/p2p/src/sync_services/executor.rs
- comms/middleware/src/lib.rs
- comms/middleware/src/pipeline.rs
- comms/src/builder/builder.rs
- comms/src/connection_manager/actor.rs
- comms/src/connection_manager/connections.rs
- comms/src/connection_manager/manager.rs
- comms/src/lib.rs
- comms/src/outbound_message_service/service.rs
- comms/src/shutdown.rs
- comms/tests/connection_manager/actor.rs
- comms/tests/outbound_message_service/service.rs
The comms builder links up shutdown oneshots which trigger
when comms is shut down. The service using the trigger replies
when it has cleanly shutdown so that the shutdown procedure waits
until services have completed the work required to shutdown cleanly.
Closes #817 
Unit tests
> Added shutdown triggers for comms

- base_layer/p2p/src/domain_subscriber.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/message.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/broadcast_strategy.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/test_utils.rs
- comms/src/message/mod.rs
Generic still left over from attempt to generalise the public key used
in comms. Moved NodeDestination to DHT crate as it is no longer in the
comms header.
> Removed CommsPublicKey generic from NodeDestination

- base_layer/service_framework/src/handles/future.rs
- base_layer/service_framework/src/handles/mod.rs
- base_layer/service_framework/src/stack.rs
This bug fix ensures all cloned ServiceHandleFutures resolve when notified.
Fixes bug which is the root cause of the issue described here: https://github.com/tari-project/tari/blob/3b63e667f07b005b4e875a9586412f3d76eced6a/base_layer/wallet/src/text_message_service/service.rs#L418
Unit test which tests cloning a number of `ServiceHandleFuture`s and testing that they all resolve when notified.
> Fixed ServiceHandleFuture wake

- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/lmdb_db/mod.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/mmr/src/change_tracker.rs
- The MerkleChangeTrackers now have full persistent storage using LMDB backends, the issue with the clashing WriteTransactions have been resolved by splitting the processing of the MMR DbTransactions and Storage DbTransactions.
- Moved commit_block logic to db_transaction allowing the CreateMmrCheckpoint WriteOperations to be used, the CommitBlock DbKeyValuePair was removed.
- Removed some of the dependency on MerkleNode from the MemoryDatabase, now it is only used for the UTXOs and STXOs.
- Fixed issue in MemoryDatabase and LMDBDatabase where block hashes are not deleted when headers are deleted.
- Removed dependency on MerkleNode from LMDBDatabase by using a txos_hash_to_index_db to find the MMR index of a UTXO or STXO, this reduced the amount deserialisation that needs to be performed. …
> MerkleChangeTracker persistent storage

- Cargo.toml
- applications/console_text_messenger/Cargo.toml
- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/src/grpc_interface.rs
- applications/grpc_wallet/src/main.rs
- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/pingpong_async.rs
- base_layer/p2p/src/services/liveness/error.rs
- base_layer/p2p/src/services/liveness/handle.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
- base_layer/p2p/tests/mod.rs
- base_layer/p2p/tests/services/liveness.rs
- base_layer/p2p/tests/support/comms_and_services.rs
- base_layer/p2p/tests/support/comms_outbound.rs
- base_layer/p2p/tests/support/mod.rs
- base_layer/p2p/tests/support/utils.rs
- base_layer/wallet/src/text_message_service/error.rs
- base_layer/wallet/src/text_message_service/mod.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- ffi/src/lib.rs
This PR updates the Waller container object to support the new async services. 
Integration tests were added for the current Wallet services such as the wallet itself, TMS and the Liveness service.
The new wallet object was then plumbed into the Console Text Messenger application.
The gRPC wallet was not updated as it is not due for MVP and the FFI bindings still need to be updated to use a Tokio runtime.
Closes https://github.com/tari-project/tari/issues/796
Closes https://github.com/tari-project/tari/issues/797
Integration tests provided
> Update the Wallet container and reintroduce it to the applications + integration tests

- comms/src/consts.rs
- comms/src/message/envelope.rs
- comms/src/outbound_message_service/service.rs
- comms/src/peer_manager/peer_storage.rs
- infrastructure/storage/src/key_val_store/hmap_database.rs
- infrastructure/storage/src/key_val_store/key_val_store.rs
- infrastructure/storage/src/key_val_store/lmdb_database.rs
- infrastructure/storage/src/lib.rs
- infrastructure/storage/src/lmdb_store/store.rs
- infrastructure/storage/tests/lmdb.rs
- `for_each` closure now must return a `ForEachLoop` enum to indicate
whether the for_each closure should be called again
- Added convenience functions: `for_each_ok`, `filter`, `filter_take` as
default impls on `KeyValueStore` trait
- Few small optimisations on peer manager (avoid clones, exit loop early)
- COMMS_RNG is now a `RefCell` to avoid cloning the rng each time it is
needed.
Part of #824 
> KeyValueStore convenience functions + small perf improvements

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/mod.rs
When node first get the sync status, or fall behind, they could
land up in either `FetchingHorizon` or `BlockSync` depending on how far
back they are. This PR updates the FSM to reflect that reality.
> Add missing state transitions to base node FSM

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/fetching_horizon_state.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
Adds stubs for the missing state structs in the base node FSM.
Provide comments for allowed state conversions.
What's quite nice about doing it this way is that the _compiler_ will tell you
if you try and enact an illegal state change, e.g. from Startup -> Listening;
becuase the From trait isn't written for that change.
> Add boilerplate for base node FSM

- Cargo.toml
- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/consts.rs
- applications/tari_base_node/src/main.rs
- applications/tari_basenode/Cargo.toml
- common/src/lib.rs
The start of the base node executable.
Included:
- Scaffolding
- Configuration file handling
- Log file configuration and handling
> Add CLI and logging init to base node binary

- comms/src/connection_manager/connections.rs
The join timeout for threads was set to 100ms. This could be too short
in circle ci tests when there is high resource contention. Set to 3000ms.
Failing example: https://app.circleci.com/jobs/github/tari-project/tari/6508
N/A
> Increase join thread timeout for connection manager shutdown

- base_layer/core/Cargo.toml
- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_interface.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/service/error.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/mod.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/service/service_request.rs
- base_layer/core/src/base_node/service/service_response.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/mod.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/src/consts.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/types.rs
- base_layer/p2p/src/tari_message.rs
- Added the skeleton of the BaseNodeService, the service connects the InboundNodeCommsInterface and OutboundNodeCommsInterface to the comms layer.
- The ability to manage the linking between sent requests and received responses and request timeouts were also added. The RequestKey field in the BaseNodeServiceRequest and BaseNodeServiceResponse is used to match the original request to the received responses.
- The comm_interface tests were modified to accommodate the change to NodeCommsResponse. Originally a vector was returned in the enum, this was changed to rather return a vector of responses. This simplified the service implementation as it is difficult to append to a vector in an enum.
This PR allows Base node service requests to be sent to other connected Base Nodes and to respond to …
> Base node service skeleton

- base_layer/core/src/base_node/service/service.rs
- base_layer/p2p/src/lib.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/support/utils.rs
- base_layer/wallet/tests/transaction_service/mod.rs
- comms/dht/src/actor.rs
- comms/dht/src/config.rs
- comms/dht/src/dht.rs
- comms/dht/src/envelope.rs
- comms/dht/src/inbound/deserialize.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/broadcast_strategy.rs
- comms/dht/src/outbound/error.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/outbound/mod.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/store_forward/forward.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/src/test_utils/makers.rs
- comms/dht/src/test_utils/mod.rs
- comms/dht/tests/dht.rs
- comms/middleware/src/pipeline.rs
- comms/src/connection_manager/establisher.rs
- Outbound message requester has `send_direct`,
`send_direct_neighbours`, `propagate`, `send_flood` and `send_random`
methods.
- Requester returns the number of messages queued for sending
- Added MockOutboundService to aid in testing
Closes #903 
Unit tests, existing tests updated where applicable
> Simplified the outbound message requester

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/comms_response.rs
- base_layer/core/src/base_node/comms_interface/inbound_interface.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/chain_storage/async_db.rs
- base_layer/core/src/chain_storage/test/async_db.rs
- Added functionality to request and provide UTXOs using the BaseNodeService.
- Changed the db queries to be async in InboundNodeCommsInterface.
- Removed the use of an Arc to create references to the BlockchainDatabase.
- Changed the make_async macro to allow the generation of async db queries without params.
- Removed duplicate functions create_runtime and test_async from async_db, these functions are available in tari_test_utils.
Closes #856 and #859
This will allow the sharing of UTXOs between remote nodes.
Modified the tests to work with the async db calls and added tests for handling inbound and outbound UTXO requests.
> BaseNodeService: request and provide UTXOs

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/main.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/lib.rs
- common/Cargo.toml
- common/src/configuration.rs
- common/src/dir_utils.rs
- common/src/lib.rs
- common/src/logging.rs
- config/tari_config_sample.toml
Changes:
* `create_id` CLI flag to create and save a new node ID
* Reads seed peers from config file and assigns them to Comms Stack
* Instantiates and starts the base Node service
* Sets up and starts the Comms stack
* Load global config file from disk
* envars starting with `TARI_xxx` are automatically applied over the config
> Towards a base node executable

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/comms_response.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_interface.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/chain_storage/historical_block.rs
- base_layer/core/src/consts.rs
- Added ability to request and provide historical blocks.
- Update the BaseNodeService to make use of the new and simplified BroadcastStrategies. This allowed the BaseNodeService to no longer need access to the NodeIdentity and allow the BaseNodeServiceConfig to be simplified.
- Waiting requests in the BaseNodeService can now wait for an adjustable fraction of the responses from the contacted remote base nodes.
These changes simplified the BaseNodeService and allow base nodes to share blocks.
Tests for testing the request and response of historical blocks were also added.
Closes #854 and #855
> BaseNodeService: request and provide historical blocks

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/core/src/base_node/backoff.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/shutdown_state.rs
Provides a new `BackOff` struct that facilitates backoff retry logic.
`BackOff` is used in the InitialSync base node state to retry
fetching the chain state metadata.
Added some more colour to log messages,
> Add back-off retries to InitialSync

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/fetching_horizon_state.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
The chain metadata sync can gracefully recover when there are no
other peers, or when those peers have no data to give.
The state transition code now takes an event (and its metadata)
to properly transition and initialise the next state.
The Listening state now waits for CTRL-C rather than shutting down
immediately (a stop-gap while the rest of the state eninge in written)
Added a few more explanatory log messages.
Stubbed out Fetch Horizon state code.
> Tidy up initial sync logic

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/p2p/src/domain_message.rs
Added a `inbound_block_stream` to BaseNodeService.
As part of this process, the PeerMessage gets stripped and converted into a `DomainMessage<Block>` object. If any errors occur, the block is dropped and a message is logged. In future, we can add an event stream to blacklist peers that repeatedly send us invalid blocks.
I also moved the streams into a separate struct to avoid all the  `Option<S>` overhead. Though it seems that you have to call  `.fuse()` and `pin_mut` in the same function as the `select!` macro, so I'm not sure how much neater this approach is.
>  Add incoming block stream to BaseNodeService

- base_layer/core/src/transaction_protocol/proto/transaction_metadata.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/store_forward/forward.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/tests/dht.rs
- comms/src/connection_manager/connectivity.rs
- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/manager.rs
- comms/src/control_service/worker.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_query.rs
- comms/src/peer_manager/peer_storage.rs
- comms/tests/connection_manager/manager.rs
- comms/tests/control_service/service.rs
- comms/tests/support/factories/peer.rs
- Peer manager has `perform_query` method (example below)
- Added basic peer connection stats to `Peer`, this determines
eligibility for connection at the broadcast strategy level
- Queries sorted by Distance require searching through entire peer database.
However, this is no different from the existing `closest_identities` function.
```rust
let query = PeerQuery::new()
.select_where(|peer| !peer.is_banned())
.sort_by(PeerQuerySortBy::DistanceFrom(&node_id))
.limit(10);
let selected_peers = peer_manager.perform_query(query)?;
```
Closes #951 
Ref #928 
Unit tests
> Added limited query interface for PeerManager + Peer Connection stats

- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_vec.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/mmr/src/backend.rs
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/error.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/src/mutable_mmr_leaf_nodes.rs
- base_layer/mmr/src/pruned_hashset.rs
- base_layer/mmr/tests/change_tracker.rs
- base_layer/mmr/tests/merkle_mountain_range.rs
- base_layer/mmr/tests/mutable_mmr.rs
- Added the ability to change the configuration for the MerkleChangeTracker, this allows the minimum and maximum checkpoint history to be set.
- Added functionality to allow the base MMR of the MerkleChangeTracker to be updated using the oldest checkpoints when the maximum checkpoint history is reached.
- Added the ability to retrieve the leaf hashes from MerkleMountainRange and restore it using leaf hashes.
- The state of MutableMmr and MerkleChangeTracker can be retrieved and used to restore their previous states.
- CompactMmrState was introduced to extract a restorable state for the MerkleChangeTracker and MutableMmr. It also allows state parts to be retrieved and combined to form the full state.
- Added clear to ArrayLike trait and shift to ArrayLikeExt and provided implementations …
> Extract and restore MMR state

- applications/tari_testnet_miner/src/miner.rs
- base_layer/core/src/proof_of_work/difficulty.rs
- base_layer/core/src/proof_of_work/error.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/core/src/proof_of_work/mod.rs
This PR adds in a difficulty adjustment algorithm. 
We need to adjust the difficulty per block. This PR adds the LWMA algorithm  as per https://github.com/zawy12/difficulty-algorithms/issues/3 
This should be proficient for early testnet versions. 
Added unit test testing for changes in the algorithm.
> Apply LWMA algo with diff adjustiment trait

- scripts/test_in_docker.sh
Have you ever wished you could run tari tests in Ubuntu on OSX but had no
idea how to do it? Well now you can! If you have Docker installed,
this script will pull a docker image (with the required libraries
precompiled), copy your local source over,
and run the tests.
> Add local docker test script

- .circleci/config.yml
Seems to be OOM issues with the rust build.
I've decreased the number of concurrent jobs to 2 (from 4)
and this seems to help the build pass.
> Possible fix for sporadic build failure on circle CI

- base_layer/transactions/src/transaction_protocol/proto/transaction_sender.proto
- base_layer/transactions/src/transaction_protocol/proto/transaction_sender.rs
- base_layer/transactions/src/transaction_protocol/recipient.rs
- base_layer/transactions/src/transaction_protocol/sender.rs
- base_layer/transactions/src/transaction_protocol/single_receiver.rs
- base_layer/transactions/src/transaction_protocol/transaction_initializer.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/transaction_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/src/lib.rs
This PR adds in a `test_harness` feature to the wallet which provides 3 functions that will allow a mobile dev to mimic the behaviour of the wallet interacting with another wallet and base node without the need for the external nodes. These functions are:
- `complete_sent_transaction`: Confirm a sent transaction as if the receiver replied
- `receive_test_transaction`: Have this wallet receive a transaction as if an external wallet sent it
- `mine_completed_transaction`: Will update the state of a completed transaction as if it has been mined, this will also update the status of the outputs associated with the transaction
- `detect_broadcast_of_inbound_transaction`: Will update an InboundTransaction to Completed as if it was detected as broadcast by the sender.
This PR also adds in a …
> Add some final MVP features and testing/development functions to wallet 

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/tests/support/comms_and_services.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- comms/src/connection/net_address/i2p.rs
- comms/src/connection/net_address/ip_dns.rs
- comms/src/connection/net_address/mod.rs
- comms/src/connection/net_address/onion.rs
- comms/src/connection/net_address/parser.rs
- comms/src/control_service/service.rs
This allows users to advertise a DNS address if they so wish.
Useful if a user does not have a static IP address and wishes to use
services like no-ip.
Updated pingpong example to use local LAN address
DNS addresses are a quick addition and may be useful to users
Unit tests for new net address type
> Allow DNS addresses to be used for peer connections

- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/transactions/Cargo.toml
- base_layer/transactions/src/consensus.rs
Refactor target and block_window constant location
Add FTL to consensus rules
The FTL stops timestamp manipulation for selfish mining. 
See : https://github.com/zawy12/difficulty-algorithms/issues/13
For how this was calculated. 
Also moved the target time and block_window constant to consensus rules as they are required by the ftl calculation. We cannot have them in two places. Its better to have it in consensus than difficulty.
> Add Future time limit to concensus

- comms/Cargo.toml
Release notes here:
https://github.com/erickt/rust-zmq/blob/master/NEWS.md#092
Nothing that really effects this project but it's often a good idea to
stay up to date
> Update zMQ v0.9.2

- base_layer/core/src/base_node/service/service.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/tests/services/liveness.rs
- comms/dht/src/actor.rs
- comms/dht/src/broadcast_strategy.rs
- comms/dht/src/config.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/inbound/error.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/proto/dht.proto
- comms/dht/src/store_forward/forward.rs
- comms/src/connection_manager/actor.rs
- comms/src/connection_manager/connectivity.rs
- comms/src/connection_manager/manager.rs
- comms/src/control_service/worker.rs
- comms/src/outbound_message_service/service.rs
- comms/src/peer_manager/connection_stats.rs
- comms/src/peer_manager/error.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/test_utils/dialers.rs
- comms/tests/connection_manager/actor.rs
- comms/tests/support/factories/peer.rs
- infrastructure/test_utils/src/streams/mod.rs
- Allow a few attempts (configurable) to broadcast before entering a
cooldown period for broadcasts (configurable) per peer
- ~~`PeerConnectionStats` replaced with `LastConnectionState`.
`LastConnectionState` specifically deals with the last connection~~
- `PeerConnectionStats` includes details on the last connection  attempt 
and how many times a connection failed in a row.
- Test for select_peers in DHT
- Should fix flakiness for simultaneous connect test (e.g. https://app.circleci.com/jobs/github/tari-project/tari/7232)
When using a 1:many broadcast strategy, peers which are not contactable should be temporarily excluded. This allows broadcasting to 'expand' (in terms of the distance metric) if a number of neighbouring nodes go offline. An attempt to contact nodes directly is still …
> Prevent over eager broadcast cooldown

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/comms_response.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/comms_interface/mod.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/proto/request.proto
- base_layer/core/src/base_node/proto/request.rs
- base_layer/core/src/base_node/proto/response.proto
- base_layer/core/src/base_node/proto/response.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- Added the local base node service interface that allows the miner and other local services to request information from the base node service.
- Local services can use the local interface to request the metadata of the local base node service, the construction of a new block and submitting of blocks.
- The propagate_block function has been added to the OutboundNodeCommsInterface, to enable the broadcasting of validated blocks.
- The name of the InboundNodeCommsInterface has been changed to InboundNodeCommsHandlers.
- The logic of constructing a new block and handling of received blocks still need to be implemented.
These additions allow the local miner to submit completed blocks and local services to propagate blocks to the network.
Added a test for testing the local interface for …
> BaseNodeService: local api interface and propagation of blocks

- base_layer/core/src/chain_storage/blockchain_database.rs
When adding a new block, if the DB is empty,
`is_best_block` should only return true if
the block is the Gensis block
> Check that 1st block into DB is the Genesis block

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
The method completed_transaction_get_status, for the iOS build c_char is interpreted as i8, for the Android build it is interpreted as u8, which results in an error. Changing the return to c_int resolves the problem.
> Change FFI completed_transaction_get_status representation from c_char to c_int

- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/comms_interface/mod.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- Implemented handle_block by adding the received block to the blockchain db. A block event with the verification status is then created and sent on the block event stream.
- A block event and block event stream was added.
- The block event stream subscriber was added to the LocalNodeCommsInterface to allow other local services to obtain access to the block event stream.
Newly received blocks are now handled by the base node service.
Added tests for propagation of valid and invalid blocks, and submitting a new block using the LocalNodeCommsInterface.
> Handle block and block event stream

- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/transactions/src/aggregated_body.rs
- base_layer/transactions/src/proto/transaction.proto
- base_layer/transactions/src/proto/transaction.rs
- base_layer/transactions/src/proto/utils.rs
The `AggregateBody` fields should always be private.
Adding inputs and outputs have side-effects, and once built, an
AggregateBody should be considered immutable
> Undo regression - make AggregateBody fields private

- applications/tari_testnet_miner/src/miner.rs
- applications/tari_testnet_miner/src/t_blake_pow.rs
- base_layer/core/Cargo.toml
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/proof_of_work/blake_pow.rs
- base_layer/core/src/proof_of_work/difficulty.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/core/src/proto/block.rs
- base_layer/transactions/Cargo.toml
- infrastructure/tari_util/Cargo.toml
- infrastructure/tari_util/src/epoch_time.rs
- infrastructure/tari_util/src/extend_bytes.rs
- infrastructure/tari_util/src/lib.rs
Changed the timestamp field of the header to be a u64 and not a datetime
We currently have the timestamp as a chrono::datetime field. This adds a dependancy which is not really required and if this library is changed in the future it might give compatibility issues. 
Everywhere where we use the timestamp we need to convert it to a u64. We only use the timestamp as a u64 unix epoch including in wire transmission. 
The only exception to this is the display. This PR removes a dependancy and reduces the amount of conversions for the timestamp. 
This does not break any of the current unit tests
> Changed header timestamp to use u64 wrapper struct and not datetime

- base_layer/p2p/src/initialization.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/wallet/mod.rs
The Comms stack was not using the provided Discovery Timeout which was causing some trouble in a couple tests.
Also made the contacts keys and amounts of the generated wallet test data consistent between runs.
Closes https://github.com/tari-project/tari/issues/1023
tests updated
> Fixed Discovery Timeout and make wallet test data deterministic

- base_layer/transactions/src/transaction_protocol/recipient.rs
- base_layer/transactions/src/transaction_protocol/sender.rs
- base_layer/transactions/src/transaction_protocol/single_receiver.rs
- base_layer/transactions/src/transaction_protocol/transaction_initializer.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/src/lib.rs
As above
When the wallet_ffi test broke it would leave a corrupt LMDB file on the disk which caused future issues.
> Use tempdir for wallet_ffi tests to avoid corrupted LMDB file in testing

- base_layer/core/src/consts.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
Currently when you send a message via the wallet to a peer that has yet to be discovered the comms stack doesn't return while it waits for the the discovery process to complete or timeout. We are working on a solution with more detailed async feedback but for now just reducing this timeout.
> Reduce the Discovery timeout in the Wallet

- common/src/lib.rs
- common/src/logging.rs
A common pattern for asynchonous message passing components is to handle
errors by logging them and continuing.
```rust
futures::select! {
event = read_an_event() => {
match self.handle_event(event).await {
Ok(_) => {},
Err(err) => log::error!("An error happened {}", err);
}
// or ..
let _ = self.handle_event(event).await.or_else(|err| {
log::error!("An error happened {}", err);
Err(err)
})
}
}
```
Now you can write
```rust
futures::select! {
event = read_an_event() => {
log_if_error!(
target: LOG_TARGET,
"An error happened {}",
self.handle_event(event).await
);
}
}
```
> Added log_if_error helper macro

- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/proto/mempool_request.rs
- base_layer/core/src/mempool/proto/mempool_response.rs
- base_layer/core/src/mempool/proto/mod.rs
- base_layer/core/src/mempool/proto/service_request.proto
- base_layer/core/src/mempool/proto/service_response.proto
- base_layer/core/src/mempool/proto/tx_storage_response.proto
- base_layer/core/src/mempool/proto/tx_storage_response.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/outbound_interface.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/test/service.rs
- Added ability to request from the MempoolService if a transaction is stored in the Mempool and where in the Mempool the transaction is located.
- The transactions excess signature is used to uniquely identify the transaction.
- The TxStorageResponse proto enum was added with conversions.
This PR allows remote nodes to query if a transaction is in the Mempool and in which subpool the transaction is located.
A test was added to test the get transaction using excess sig request and a test for service request timeouts.
> Request Tx state from Mempool Service

- base_layer/core/Cargo.toml
- base_layer/core/src/base_node/chain_metadata_service/error.rs
- base_layer/core/src/base_node/chain_metadata_service/handle.rs
- base_layer/core/src/base_node/chain_metadata_service/initializer.rs
- base_layer/core/src/base_node/chain_metadata_service/mod.rs
- base_layer/core/src/base_node/chain_metadata_service/service.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/proto/mod.rs
- base_layer/core/src/lib.rs
- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/proto/liveness.proto
- base_layer/p2p/src/services/liveness/handle.rs
- base_layer/p2p/src/services/liveness/message.rs
- base_layer/p2p/src/services/liveness/mock.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/neighbours.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
- base_layer/p2p/tests/services/liveness.rs
- base_layer/wallet/src/wallet.rs
- comms/dht/src/actor.rs
- infrastructure/broadcast_channel/src/channel.rs
- infrastructure/broadcast_channel/src/lib.rs
- infrastructure/tari_util/src/lib.rs
- infrastructure/tari_util/src/locks.rs
- infrastructure/test_utils/src/enums.rs
- infrastructure/test_utils/src/lib.rs
This iteration does not send aggregated chain metadata to the base node
service as that is TBD, but is complete enough for a review.
- Liveness service sends pings at a configurable interval
- Metadata can be tacked onto the reply pongs
- The chain metadata service is responsible for:
- Keeping the metadata sent up to date by updating the metadata the
liveness service sends after each block that is added to the
blockchain
- Collecting the metadata from each neighbouring peer between rounds
of pings
- Sending that data to the basenode once all peers have responded or
before the next round of pings has started (sending to base node
service is TBD)
TODO:
- If base node enters synching state, chain metadata service needs to be notified and should stop sending chain metadata to peers until …
> Periodically share chain metadata

- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/support/data.rs
The Output Manager service functional integration tests only used the MemoryDB storage backend, this PR has each test run on both the MemoryDB and Sqlite Backend
It is tests!
> Update output manager service tests to use both storage backends

- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/mempool/service/error.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/core/src/mempool/test/service.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- comms/dht/src/actor.rs
- comms/dht/src/broadcast_strategy.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/encryption.rs
- comms/dht/src/outbound/error.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/message_params.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/outbound/mod.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/test_utils/mod.rs
- comms/src/connection/peer_connection/dialer.rs
- comms/tests/control_service/service.rs
- When a peer discovery is required a
`SendMessageResult::PendingDiscovery(discovery_notif)` is immediately returned with a
oneshot that will resolve once the discovery process is complete.
- The caller can choose if they are interested in waiting for the
discovery to resolve / can continue with other work in the meantime.
- Added SendMessageParam builder to encapsulate the options for sending messages. The 'preset' methods (such as propagate, neighbours etc) on the DhtOutboundRequester use this builder internally, and it can be used externally to use custom parameters when sending a message.
Closes #1041
Changed applicable tests
> DhtOutboundRequester indicates to caller if discovery is in progress

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/proto/request.proto
- base_layer/core/src/base_node/proto/request.rs
- base_layer/core/src/base_node/proto/response.proto
- base_layer/core/src/base_node/proto/response.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/blocks/mod.rs
- base_layer/core/src/blocks/new_block_template.rs
- base_layer/core/src/blocks/new_blockheader_template.rs
- base_layer/core/src/chain_storage/async_db.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/proof_of_work/proof_of_work.rs
- base_layer/core/src/proto/block.proto
- base_layer/core/src/proto/block.rs
- base_layer/core/src/test_utils/builders.rs
- Added GetNewBlock Base node service request and modified the NewBlockTemplate response to return a block template.
- Block and header templates were introduced that can be used to construct new partial blocks.
- When a miner submits a block template, the base node will update the header with the correct MMR roots and return the block to the miner.
- Added proto requests and responses for GetNewBlock and NewBlock. Proto conversions for NewBlockTemplate and NewBlockHeaderTemplate were also added..
- Fetch_future_mmr_root was added to Blockchain_db, Memory_db and Lmdb_db. This allows the MMR roots to be calculated using the provided change set without altering the MMRs of the current longest chain. This functionality is required to construct a valid new mineable block.
- The RewindMmr …
> Multi stage mineable block construction

- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
Added logging to callback registration and execution.
Fixed bug in callback registration for mined and broadcast callbacks.
cargo test --all-features
> FFI - Callback Fix

- base_layer/core/src/consts.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/migrations/2019-06-26-130555_initial/down.sql
- base_layer/wallet/migrations/2019-06-26-130555_initial/up.sql
- base_layer/wallet/migrations/2019-11-26-105357_contacts/down.sql
- base_layer/wallet/migrations/2019-11-26-105357_contacts/up.sql
- base_layer/wallet/migrations/2019-11-26-120903_peers/down.sql
- base_layer/wallet/migrations/2019-11-26-120903_peers/up.sql
- base_layer/wallet/src/contacts_service/error.rs
- base_layer/wallet/src/contacts_service/storage/database.rs
- base_layer/wallet/src/contacts_service/storage/memory_db.rs
- base_layer/wallet/src/contacts_service/storage/mod.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/error.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/mod.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/support/data.rs
This PR adds a Sqlite backend for the Contacts Service and the Peer database for the wallet
It also update the respective integration tests to test using both the sqlite and memory db’s
Closes https://github.com/tari-project/tari/issues/938
test provided
> Implement Sqlite backends for Contacts service and Wallet peer db

- infrastructure/protobuf_build/Cargo.toml
- infrastructure/protobuf_build/src/lib.rs
Generated protobuf structs were written on every build, which causes
rust to rebuild the crate.
This PR only writes a generated rust protobuf struct if necessary i.e.
if the hash of the files contents are different, and so prevents
unnecessary rebuilds.
> Only write generated proto structs if necessary

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/comms_response.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/proto/request.proto
- base_layer/core/src/base_node/proto/request.rs
- base_layer/core/src/base_node/proto/response.proto
- base_layer/core/src/base_node/proto/response.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/error.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/mod.rs
- base_layer/core/src/proof_of_work/error.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/core/src/proto/block.proto
- base_layer/transactions/src/consensus.rs
- Introduced the difficulty adjustment manager that keeps track of the chain state to calculate the target difficulty of the different PoW algorithms.
- Added the GetTargetDifficulty comms request and TargetDifficulty comms response to the BaseNodeService allowing miners to request the target difficulty from a Base node.
- Added proto conversions for the GetTargetDifficulty request and TargetDifficulty response.
- Added the difficulty adjustment manager to the tari base node and existing tests.
- Fixed 0 difficulty issue in Lwma_diff and change it to make use of the correct target time. Changed it to make the target time configurable.
Enables miners to query a Base node to determine the target difficulty for a specified PoW algorithm.
Added a test for testing the the get target difficulty …
> Request PoW target difficulty for miner from the base node

- base_layer/p2p/src/proto/message_type.proto
- base_layer/transactions/src/transaction_protocol/proto/transaction_finalized.proto
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/support/data.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Currently the transaction protocol between a Sender and Receiver wallet involves 2 stages. 
1. Sender send Partial Tx to Receiver
2. Receiver Signs Tx and sends partial Tx to Sender
The Sender then completes the Tx and broadcasts it. This means the Receiver is only aware of the finalised transaction once they spot it in the mempool.
It was decided to add one more message to the protocol where the Sender will send the Finalised transaction back to the Receiver so that they have a copy of it before it appears in the mempool. This makes it easier for the Receiver to spot the Tx in the mempool OR if the sender does not broadcast it the Receiver can potentially broadcast it.
This PR adds this sending of the finalised transaction and adds a FFI callback for receiving this message and a number …
> Add a final stage to the wallet Transaction Protocol

- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/test/service.rs
- base_layer/core/src/test_utils/mod.rs
- base_layer/core/src/test_utils/node.rs
- Unified the service test utilities of the Mempool service and Base Node service into a test BaseNodeBuilder in test_utils.
- The test BaseNodeBuilder provides a simple interface for constructing and configuring the different components of the Base Node.
- Helper functions for creating a network with 2 nodes or 3 nodes were also added.
- Cleaned and changed the tests of MempoolService and BaseNodeService to make use of the new test utilities and BaseNodeBuilder.
The BaseNodeBuilder provides a simpler and cleaner interface for constructing a test node.
Existing tests were modified to make use of the new test utilities.
> Refactor the BaseNodeService and MempoolService test helper functions

- base_layer/wallet/src/error.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
This PR Updates the wallet container to accept all 4 storage backends for the services it contains. This allows for the Wallet services that require storage to be constructed with either types of backend.
The Wallet FFI now builds the Wallet container using the Sqlite persistence backend.
Closes #55 
Existing tests, test this
> Update the FFI Wallet container to use the Sqlite backends

- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/mempool/test/service.rs
- base_layer/core/src/test_utils/node.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/tests/services/liveness.rs
- base_layer/p2p/tests/support/comms_and_services.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
We were using TempDir incorrectly. We were essentially using it to generate a random path for us, the letting it delete that directory but then remake the directly ourselves but never clean it up.
There was a line in the comms_setup that did this with a silent error which I have removed and then fixed all the usages of tempdir to be used correctly so the resulting directory is cleaned at the end of the test.
Properly cleanup temporary files in tests
Updated tests
> Fix the usage of TempDir

- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/functions.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/tests/pruned_mmr.rs
- base_layer/mmr/tests/support/mod.rs
A useful feature is to be able to relatively cheaply calculate a new MMR
root by simulating changes to a MMR without changing the MMR itself.
This PR adds two new functions that provide this functionality.
> Add `calculate_mmr_root` utility functions

- applications/tari_testnet_miner/src/miner.rs
- base_layer/transactions/src/coinbase_builder.rs
- base_layer/transactions/src/lib.rs
- base_layer/transactions/src/test_utils/builders.rs
- base_layer/transactions/src/test_utils/mod.rs
- base_layer/transactions/src/test_utils/primitives.rs
- base_layer/transactions/src/transaction.rs
- base_layer/transactions/src/transaction_protocol/mod.rs
- base_layer/transactions/src/transaction_protocol/recipient.rs
- base_layer/transactions/src/transaction_protocol/sender.rs
- base_layer/transactions/src/transaction_protocol/transaction_initializer.rs
The coinbase transaction hasn't been properly addressed until now.
There were several pieces of code that provided CB TXs in various
places in the codebase.
The CB TX is a simple but non-trivial implementation and so a builder
pattern is used.
The builder unifies all the code for generating a CB TX in one place.
The builder lives in the `transactions` crate and so does not know
about a block. Another PR will provide a `from_block` type function
in `tari_core` that will make use of the builder to ergonomically
construct a CB TX from information in a block.
Also brought the `TestParams` test utility into the common utils module to be more widely accessible
> Add Coinbase Transaction Builder

- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/transactions/src/consensus.rs
This adds tracking of the timestamps for the median timestamp. This will allow the query of the median timestamp of the past 11 blocks.
RFC 0120 specifies that we need to check that an incoming block's timestamp is greater than the median timestamp of the past 11 blocks. This requires that the past 11 bocks be kept track off. This uses the difficulty manager to keep track of the past 11 blocks as this already keeps track of the past 90 blocks for each difficulty. The median timestamp can now just be queried.
Added unit tests to ensure it keeps track of the correct blocks.
> Add median timestamp tracking

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/states/fetching_horizon_state.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/base_node/test/mod.rs
- base_layer/core/src/base_node/test/state_machine.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/proof_of_work/monero_rx.rs
- Implemented the initial base node horizon synchronisation of the kernel mmr, range proof mmr, output mmr, headers, kernels and utxo set.
- Added fetch_mmr_base_leaf_node_count blockchain_db, memory_db and lmdb_db function to retrieve the total base mmr node count.
- Added Configuration for BaseNodeStateMachine and Horizon syncing, to allow the configuration of request chunk sizes.
Enables the initial sync process of a Base node, allowing the blockchain to be synced from genesis block to pruning horizon.
Added a test for testing the horizon syncing mechanism and state transition.
> Base node horizon synchronisation

- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
When a transaction is sent to a peer that is not known the comms stack will perform a Discovery process which can take minutes. Do not block the client using the wallet library we now return immediately telling the client that the Discovery process is underway and then when it is completed we will use a call-back and event bus to let the client know that the Discovery has been completed (successfully or not) asynchronously.
If the discovery was unsuccessful the pending transaction is cancelled.
Closes https://github.com/tari-project/tari/issues/1065
Test provided
> Provide async callback for when Transaction service needs to perform peer discovery

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- Changed the fetch_mmr_checkpoint blockchain backend function to rather use height instead of index. Internally, the provided height is converted to the checkpoint index.
- This will fix the fetch_block issue when the change tracker committed checkpoints to the base MMR, a test was provided to demonstrate the fix.
- Added fetch_pruning_horizon function to the blockchain backend, memory_db and lmdb_db. This allows the pruning horizon of the MMR change trackers to be retrieved.
Fetch block uses height as the checkpoint index, which is not valid when the change tracker has committed some of the checkpoint to the base mmr. This PR will fix this issue.
Two tests were added to test the fetch_block and testing the fetch_mmr_checkpoint with changing pruning horizons.
> Fetch MMR checkpoints using height

- Cargo.toml
- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/consensus/mod.rs
- base_layer/core/src/mining/coinbase_builder.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/mod.rs
- base_layer/core/src/test_utils/node.rs
- base_layer/core/src/test_utils/test_common.rs
- base_layer/core/src/validation/block_validators.rs
The is the second refactor of consensus and difficulty adjustment manager. This adds difficulty manager to the consensus manager.
This refactor allows the code to only keep track of `ConsensusManager` which now keeps all state-full consensus objects inside of it. This is wrapped inside of an ARC and RwLocks. This allows the data to change while allowing multiple reads. The `ConsensusManager` can  safely be clone as we only clone the arc inside of it. 
This changes will also make the validation pipeline testing easier as it already has access to the consensus manager. It will now have access to all state-full checking objects
All existing test stil pass.
> refactor diff manager

- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/test_utils/node.rs
- base_layer/core/src/test_utils/test_common.rs
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/common.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/merkle_proof.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/src/mutable_mmr_leaf_nodes.rs
- base_layer/mmr/tests/change_tracker.rs
- base_layer/mmr/tests/merkle_proof.rs
- Modified the MerkleChangeTracker function to find the leaf index of previously committed hashes and uncommitted hashes. This change is required to enable MMR updates to be enabled or disabled in the blockchain backends. 
- Fixed the MerkleChangeTracker restore function so it correctly reverts the pruned MMR back to the newly restored base MMR.
- Added a find_leaf_index function that returns the leaf index of a given hash, and renamed the find_leaf_node function to find_node_index. 
- Changed the naming of the two types of indices used in the MMRs to leaf_index and node_index to make it more intuitive, less error prone and more descriptive of what index is required by the different functions. The leaf index refers to the leaf number and the node_index is the position in the MMR.
- Also, …
> Find the MMR leaf index for a hash in the MerkleChangeTracker

- base_layer/core/src/base_node/states/fetching_horizon_state.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/base_node/test/state_machine.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/chain_storage/test/chain_storage.rs
- base_layer/core/src/test_utils/test_common.rs
- Added validate horizon state step to the horizon sync process to allow the blockchain metadata to be updated and allow the future block sync process to build on the current horizon state.
- Modified the blockchain backend and db transactions to allow the enabling and disabling of MMR updates, this is useful to ensure that duplicate hashes are not inserted into the MMRs when the horizon state is synced.
- Modified the fetch_pruning_horizon function of the blockchain backends to calculate the number of checkpoints in the base MMR from the tip height and number of checkpoints in MerkleChangeTracker.
- Added the fetch_last_header blockchain backend function to allow easy retrieval of the tip header that can be used to update the blockchain metadata.
Syncing the horizon state did not …
> Fixed metadata update and duplicate hash issue of horizon state sync

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/test_utils/node.rs
- Added block forwarding/propagation for validated blocks. 
- Modified the the outbound block stream of the Base Node service to be a futures mpsc channel and not have a oneshot replay channel. This change was required to prevent a deadlock when the base node service handle_incoming_block passed the incoming block to the block handler, which in turn is requesting the propagation of the block from the base node service.
- Added the ability to exclude peers when requesting the propagation of a block using the outbound comms interface.
This change will allow blocks to propagate through the network.
Modified the propagate_valid_block and propagate_invalid_block tests. these tests now also check that only valid forwarding of blocks occur.
> Forward new blocks

- base_layer/wallet/migrations/2019-10-30-084148_output_manager_service/down.sql
- base_layer/wallet/migrations/2019-10-30-084148_output_manager_service/up.sql
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/support/data.rs
- base_layer/wallet/tests/transaction_service/callback_handler.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
The Key Manager state used by the OMS was not being persisted, it will now automatically check if there is state in the DB and if there is not it will start a fresh key manager.
Overlooked needing to persist this state
Tests provided
> Add persistence for the Key Manager used in Output Manager Service

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/base_node/test/state_machine.rs
- Implemented the block syncing state machine mechanism used for syncing blocks from the horizon or lagging height to the chain tip.
-  Introduced BlockSyncConfig, and added the block sync config to the BaseNodeStateMachineConfig.
Enable syncing of block between different base nodes.
- Added a test for testing block syncing from horizon to chain tip.
- Added a test for testing block syncing from lagging state, after horizon, to chain tip.
> Synchronise base node missing blocks

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/mod.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/core/src/base_node/test/state_machine.rs
- base_layer/core/src/mempool/test/service.rs
- base_layer/core/src/test_utils/node.rs
- Implemented the ability for a base node to limit the number of blocks that it will provided in response to fetch block requests.
- Added configuration to the inbound node comms handlers, allowing the maximum block response batch size to be specified.
- Changed the block synchronisation logic so that it doesn’t assume that all requested blocks were provided, the request batches are updated depending on what block responses were received.
This improvement is required to limit a potential DOS attack for the fetch block mechanism. 
- Extended the service request_and_response_fetch_blocks test to also test for a mismatch between the number of request and response block limits.
- Modified the state_machine tests (test_block_sync_from_horizon, test_lagging_block_sync) to check that syncing …
> Nodes should only send as many blocks as they want

- base_layer/wallet/migrations/2019-11-20-090620_transaction_service/down.sql
- base_layer/wallet/migrations/2019-11-20-090620_transaction_service/up.sql
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
This PR add the functionality for a Miner to request the spending key for a coinable output that they want to mine. The key and amount of the coinbase is stored as a Pending Incoming Transaction and will reflect in the pending balance of the wallet.
If the mining is successful the Miner will supply the completed transaction to the Transaction Service. 
If mining was unsuccessful the coinbase transaction should be cancelled.
Closes #1101 
Tests provided
> Add support for managing coinbase transactions to Transaction Manager in wallet

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
Refactored to the db to use an option<Validator>. This allows us to first construct the db. Then we can pass in the DB to the FullStateValidator which requires it to function. We then pass the validators in after construction of the db.  
FullStateValidators require DB access
This is only a refactor and does not break any changes
> Add db to FullStateValidator

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
Changed all add_validators to set_validators
This fixes a naming refactor bug in the previous PR #1169 
Passes all unit tests
> Changed all add_validators to set_validators

- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/transactions/src/helpers.rs
There is a single function that returns the genesis block. The block returned would not have passed consensus rules. This refactor moves the function to test code so that tests that currently use it, can still call it. It adds a new function that generates a genesis block that will pass consensus.
We dont want to let most of the tests depend on consensus code where it is not required to do so. Currently a lot of tests call a function call `get_genesis_block()` This function builds a random genesis block and returns it. 
Currently the returned block does not pass all consensus rules, the tests that call this function all so dont need those consensus rules and we dont want to let them depend on them. I have created a new function called `get_empty_test_gen_block() ` which replaces the …
> Get_genesis_block refactor

- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/proof_of_work/mod.rs
- base_layer/core/tests/diff_adj_manager.rs
- Added get_target_difficulty_with_height and get_median_timestamp_with_height function to the diff_adj_manager to enable the calculation of the target difficulty and median timestamp for any height in the chain and not only the tip. 
- Fixed an issue where the VecDeque of timestamps was not properly reset before full syncs with the blockchain db.
- Modified the diff_adj_manager tests to be less reliant on the calculated difficulties provided by lwma_diff, but rather test that the correct blocks were used in the calculation of the target difficulty and median timestamps.
This change was required to check the PoW and timestamps of the synced horizon state.
Added test_target_difficulty_with_height and test_median_timestamp_with_height tests.
> Request target difficulty and median timestamp with height

- base_layer/wallet_ffi/src/error.rs
Small PR to add missing OutboundSendDiscoveryInProgress to WalletError
Was being returned as the catch all error code (999) where it should be handled specifically by the client implementations
cargo test --all-features
> Added OutboundSendDiscoveryInProgress Error Code 

- base_layer/core/src/base_node/chain_metadata_service/service.rs
- base_layer/p2p/src/services/liveness/config.rs
- base_layer/p2p/src/services/liveness/error.rs
- base_layer/p2p/src/services/liveness/handle.rs
- base_layer/p2p/src/services/liveness/mock.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
This PR adds the ability to register NodeIDs to be monitored with the Liveness service which will then monitor their Liveness using periodic Pings and maintain stats regarding the Liveness. This is to enable a wallet to monitor the status of the Base Nodes it wants to use to interface with the base layer.
Closes #1183 
Test provided
> Allow Liveness Service to monitor Liveness stats for specified nodes

- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/lmdb_db/mod.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/tests/change_tracker.rs
- base_layer/mmr/tests/mutable_mmr.rs
- base_layer/mmr/tests/support/mod.rs
1. Add bitmap to MutableMMR constructor
One should be able to provide a set of nodes that are marked as deleted
when creating a MutableMmr.
2. Modify MutableMmr calls to use new constructor
All uses of MutableMmr have been updated to include a
Bitmap in the constructor.
The LMDB_DB constructor can now load the deleted UTXO state
from the backend and populate the UTXO Mmr instance. This
is Step 1 of making the UTXO state persist which UTXOs have
been spent.
The next step (not done here) is to write the UTXO bitmap to
the backend when it changes.
> Bitmap init

- base_layer/mmr/tests/pruned_mmr.rs
The `get_changes` method could provide a vector of zero changes,
which will cause some tests to fail 1% of the time. :face_palm:
> Fix MMR test

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/src/validation/horizon_state_validators.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/src/validation/traits.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/diff_adj_manager.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
- base_layer/core/tests/horizon_state_validators.rs
- Added the HorizonStateHeaderValidator for checking chaining, PoW and timestamps of the synced headers. 
- Added the horizon state header validator to the validators of the blockchain database and implemented the validate_horizon state function.
- Created a BlockHeaderValidationError and moved some of the header specific errors from BlockValidationError to the new error type.
- Exposed the get_target_difficulty_with_height and get_median_timestamp_with_height functions in the consensus manager.
- Split the timestamp FTL and median timestamp check into two separate checks to allow the median timestamp check code to be reused by the horizon state validator.
- Moved the common validation check functions to a helpers file.
- Removed the unused set_db function from the Validation trait. …
> Perform header validation on synced blockchain horizon state

- .circleci/config.yml
- .gitmodules
- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/gen_node_identity.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/wallet_ffi/src/error.rs
- comms/Cargo.toml
- comms/src/connection/connection.rs
- comms/src/connection/multiaddr.rs
- comms/src/connection/peer_connection/dialer.rs
- comms/src/connection/peer_connection/listener.rs
- comms/src/control_service/worker.rs
- comms/src/lib.rs
- comms/src/socks/client.rs
- comms/src/transports/socks.rs
- comms/src/utils/multiaddr.rs
- comms/tests/connection/connection.rs
- comms/tests/connection/monitor.rs
- comms/tests/connection/peer_connection.rs
- comms/tests/connection_manager/establisher.rs
- comms/tests/support/factories/net_address.rs
- infrastructure/test_utils/src/runtime.rs
- Removed rust-multiaddr submodule
- Parity multiaddr is an actively developed fork of rust-multiaddr residing in rust-libp2p
Ref #1186 
Only remaining issue is the `snow` git dependency
> Remove rust-multiaddr in favour of parity-multiaddr 

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/testnet_utils.rs
Update the test generation function to wait for dummy wallets to add the wallet to their peer_manager. Attempt to fix intermittent error on CI and mobile using this function.
> Update wallet test data generation function

- comms/Cargo.toml
- comms/src/noise/config.rs
- Ensure that snow builder is not part of the async fn's state
Removes the need for a `Send` `CryptoResolver` from the snow library
Closes #1186 
Code compiles with snow@0.6.2
> Remove snow git dep

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
PR to add two additional methods to wallet_ffi
1) wallet_check_originating_completed_transaction -> determines if a completed transaction was originally sent from the wallet.
2) pending_outbound_transaction_get_fee -> returns the fee of an outbound transaction.
Requested by mobile developers
> Added additional FFI methods

- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/helpers/mock_backend.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- Added total_kernel_excess function to Blockchain_db. Total_kernel_excess can be used to calculate the total kernel excess for all kernels in the chain.
- Added total_kernel_offset function to Blockchain_db, used to calculate the total kernel offset for all the kernel offsets recorded in the headers of the chain.
- Added total_utxo_commitment function to Blockchain_db, that calculates the total sum of all the UTXO commitments in the chain.
- Added for_each_kernel, for_each_header and for_each_utxo to the BlockchainBackend trait to provide access to all stored kernels, header and utxos.
- Implement these new functions for Lmdb_db, Memory_db and Mock_backend.
These changes are required to validate the synced horizon state.
Added new chain storage and backend tests for these new functions.
> Calculate total kernel excess, kernel offset and utxo commitment for chain

- base_layer/core/src/blocks/block.rs
- base_layer/core/tests/helpers/block_builders.rs
- Fixed issue where the genesis_template function was using the wrong public key for its kernel excess calculation.
- Moved duplicate coinbase creation code to create_coinbase function.
- Added chain_block_with_coinbase, generate_new_block_with_coinbase and generate_block_with_coinbase functions to allow simpler testing where configuration of the coinbase is required.
These test block builder functions are required for testing the account_balance validation code.
None
> Coinbase test block builder functions

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/mempool/error.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_comms_interface.rs
Added validators to the mempool. How the mempool validates transactions can now be customised depending on the validators. 
Mempool had hard locked ways of validating transactions. It also did not include any transaction verification. Using validators fixes this. This PR also fixes #1181 
Unit tests are all still passing.
> Added validators to the mempool so they can validate the transactions

- base_layer/transactions/src/transaction_protocol/transaction_initializer.rs
- infrastructure/tari_util/src/hex.rs
`Error::description()` is deprecated. Instances have been replaced
with `to_string()`
> Remove deprecated `to_description`

- base_layer/core/Cargo.toml
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/core/src/mempool/service/outbound_interface.rs
- base_layer/core/src/mempool/service/service.rs
This PR adds the following :
Only broadcast a transaction if it was validated as a valid transaction
Upgrade monero-rs lib
Issue #1180 
Still passes all unit tests
> TX broadcast will only happen if tx was validated successfully

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/blocks/mod.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/chain_validators.rs
- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
- base_layer/core/tests/horizon_state_validators.rs
- Added GenesisBlockValidator. This validator processes the genesis block header and ensures that the synced chain builds on the correct genesis block.
- Added ChainTipValidator. This validator processes the tip header and checks that the accounting balance and MMR states of the synced chain state is valid.
- Removed the unused CryptoFactories from the StatelessValidator. 
- Removed the unused blockchain_db from the orphan_pool in the Mempool.
These validators are required to ensure that the synced horizon state is valid.
Added tests for checking the genesis block, checking the accounting balance and checking the MMR roots of the kernel set, output set and range proof set.
> Perform accounting balance and mmr state validation on synced blockchain horizon state

- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/connection_manager/tests/listener_dialer.rs
- comms/src/lib.rs
- comms/src/macros.rs
- comms/src/peer_manager/peer_id.rs
- comms/src/protocol/error.rs
- comms/src/protocol/mod.rs
- comms/src/protocol/negotiation.rs
- comms/src/protocol/notifiers.rs
- comms/src/test_utils/test_node.rs
- A peer connection can open substreams with a given protocol negotiated
- Implemented ProtocolNotifier, used to register mpsc senders given by
domain-level components interested in speaking a particular protocol.
- Run Yamux Stream in it's own task, otherwise it doesn't work (bugfix)
- Extended dialer/listener test to include opening a substream and
sending a message on that substream.
Closes #1158 and #1102 
Improved smoke test for listener and dialer
> PeerConnection can open negotiated substreams

- base_layer/wallet_ffi/README.md
- base_layer/wallet_ffi/mobile_build.sh
Catalina Fix
Fixed build for macOS Catalina
Redirected output to log files
Added colored messages for output to terminal
Fixed all lints above weak-warning level
Check to determine if ZMQ and Sqlite3 dependencies need to be rebuilt or not
Updated readme
Script was broken in macOS Catalina
Manually run on macOS Catalina
> Library Build Script - Catalina Fix

- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/src/transaction_service/service.rs
- comms/Cargo.toml
- comms/dht/Cargo.toml
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/test_utils/mod.rs
- comms/src/builder/builder.rs
- comms/src/outbound_message_service/event.rs
- comms/src/outbound_message_service/messages.rs
- comms/src/outbound_message_service/service.rs
- comms/tests/outbound_message_service/service.rs
Currently, there is no way for domain clients to tell if a message has
succeeded or failed to send to a peer.
The PR adds this ability.
When a call to the OMS is made each message is 'tagged' (i.e random `u64`)
so that it can be uniquely identified later. These tags are returned to the caller.
The caller can expect that the same tag will be part of an OMS event
indicating that the message has been (un)successfully sent.
The following events can be emitted by the OMS
```rust
pub enum OutboundEvent {
PeerDialStart(NodeId),
PeerDialSuccess(NodeId),
PeerDialFail(NodeId),
PeerDialRetry(NodeId, usize),
MessageSendSuccess(MessageTag, NodeId),
MessageSendFail(MessageTag, NodeId),
}
```
Closes #1238 
Emitted events tested in existing oms integration test
> Added OMS events

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
PR#1203 seems to have been overwritten by a merge, submitting again.
Adds two additional methods to wallet_ffi
1)  wallet_is_completed_transaction_outbound-> determines if a completed transaction was originally sent from the wallet.
2)  pending_outbound_transaction_get_fee -> returns the fee of an outbound transaction.
Requested by mobile developers
> Additional Library Methods

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/error.rs
- base_layer/core/src/mining/miner.rs
- base_layer/service_framework/src/reply_channel.rs
This PR adds a basenode local interface to the miner to replace stub functions. 
This PR adds in a builder for the basenode for the miner. And links this to be build. 
This is all for linking the miner to the basenode so that it can receive data form the basenode.
> Add basenode interface to miner for stub functions

- base_layer/core/Cargo.toml
- base_layer/wallet_ffi/mobile_build.sh
Exclude the Monero and Random-X deps from Core for Wallet
Plus some minor build script fixes
1) Fixed dependecy search path for android x86 when checking if dependency is already built
2) Fixed overwrite bug for logging for each android architecture build
3) Added output to android loop to indicate build for an architecture is complete
4) Fixed comparison of a variable for android build
5) Fixed missing path when dependencies are found
Ran build script
* [ x] Bug fix (non-breaking change which fixes an issue)
> Exclude the Monero and Random-X deps from Core for Wallet

- comms/src/builder/builder.rs
- comms/src/outbound_message_service/mod.rs
Was hardcoded to 10. Made it configurable and default to 100
> Make OMS broadcast buffer size configurable

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/contacts_service/error.rs
- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/contacts_service/storage/database.rs
- base_layer/wallet/src/contacts_service/storage/memory_db.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/error.rs
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/memory_db.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/callback_handler.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet/tests/wallet/mod.rs
All the database calls in the wallet were synchronous and I suspect the deadlocks we were seeing in constrained environments was due to this fact. The PR makes all the wallet database calls proper async blocking tasks.
> Make wallet db calls properly async and use spawn_blocking()

- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/proof_of_work/blake_pow.rs
- base_layer/core/src/proof_of_work/difficulty.rs
- base_layer/core/src/proof_of_work/proof_of_work.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/horizon_state_validators.rs
- The handle_reorg function was updated to allow the construction of forked chains from newly received orphan blocks. The orphan chain tip with the highest accumulated difficulty that is linked to the new orphan block is found. A chain is then constructed from the tip to the new orphan block all the way to the main chain. When the total accumulated difficulty is higher than the tip of the main chain then a chain reorganisation is performed. 
- Added the total_accumulated_with_achieved_difficulty member function to BlockHeader, this allows the total accumulated difficulty for the blockchain at that height including the achieved difficulty to be determined.
- Changed the default difficulty to 1 as the geometric mean calculation fails when the difficulty is 0. Some tests had to be updated …
> Check and fix re-org logic 

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/mining/miner.rs
- common/src/configuration.rs
This PR adds in the miner runtime as well as the miner base-node event stream.
This allows the miner to run on its own thread, as well as listen to the base node when it receives a new block. When a valid new block has been received it will restart the miner on the new tip.
> Add the runtime for the miner

- comms/Cargo.toml
- comms/src/bounded_executor.rs
- comms/src/lib.rs
Spawning an unbounded number of tasks in response to e.g. a network message
is dangerous because an attacker could exploit this to cause a node to become
unresponsive/use excessive system resources.
This PR adds a `BoundedExecutor` which wraps the tokio executor and a
semaphore to asynchronously block calls to spawn should all the semaphore
permits be used. This should cause backpressure on the requesting peer.
For e.g. new requests won't be handled until a permit has been
released.
BONUS: removed some unused dependencies
> Added bounded executor

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/mining/coinbase_builder.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/src/transactions/types.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/chain_validators.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/horizon_state_validators.rs
Removed the use of all Arc's from cryptofactories.
Cryptofactories already wraps its internals inside of ARC's so its no need to wrap it in an arc as well. You can just clone it.
> removed arc from crypto factories

- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/tests/listener_dialer.rs
The peer listener now can accept and upgrade multiple peer
connections simultaneously. Each inbound connection spawns it's own
"connection upgrade" task using the bounded executor (see PR #1257).
A configuration field was added to set maximum simultaneous inbound
connections. Once this threshold is reached, any new inbound connections
will have to wait for other connection to complete their upgrade
procedure.
Closes #1151 
Concurrent inbound connections needs to be tested, leaving that for a later PR
> Allow multiple simultaneous inbound connections (bounded)

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
Added rustyline to handle the cli.
Swapped out the current ctril-c handling to rustlyline
We need someway to handle commands to the basenode. RustlyLine adds functionality to handle the cli for us. The PR will allow us to add commands easily.
> Added rustlyline lib for CLI to BaseNode app

- base_layer/p2p/tests/services/liveness.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/transaction_service/callback_handler.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- comms/Cargo.toml
- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/connection_manager/requester.rs
- comms/src/connection_manager/tests/manager.rs
- comms/src/connection_manager/tests/mod.rs
- comms/src/outbound_message_service/service.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/node_identity.rs
- comms/src/test_utils/node_identity.rs
- comms/src/test_utils/test_node.rs
- comms/tests/outbound_message_service/service.rs
- infrastructure/test_utils/src/streams/mod.rs
If peers dial each other at the same time there must be a way for both
peers to deterministically choose which connection to keep and which to
disconnect.
This PR adds code to handle this situation by using the NodeID and
ConnectionDirection to enable both sides to agree on a connection to
close.
Extra: Since async tests are moving towards to running in an async context (through `#[tokio_macros::test]` - tests should probably change to use this) it no longer makes sense to use `tari_test_utils::runtime` and `Runtime::block_on` everywhere.  I changed `tari_test_utils::collect_stream!` to rather work in an async context. 
Closes #1153 
Tested by having two connection managers simultaneously dial each other and checking the events produced. Since the tie breaking is transparent to the …
> Simultaneous connection tie breaking

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/core/Cargo.toml
- base_layer/core/src/mining/coinbase_builder.rs
- base_layer/core/src/mining/miner.rs
Miner wallet integration.
Cleanup the miner code and moved mining to a blocking thread.
The miner needs to be able to submit a utxo to the wallet. The miner cannot contain a wallet as this will cause a cycle dependancy. The base node will act as a mediator between the two. The miner gives a channel out to the base node which will sit and listen for an unblindedUTXO which it will give to wallet
The miner code has also been moved to a blocking thread as spawning a task is not the most efficient use of blocking task. The mining task will wait for the blocking thread to return and does not use a thread anymore with channels to communicate internally.
> Miner wallet integration

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/transactions/aggregated_body.rs
- base_layer/core/src/transactions/transaction.rs
- base_layer/core/src/validation/block_validators.rs
Did cut-through  on block
did cleanup of warnings of unused inputs
RFC states that we need to implement cut-through on blocks. This implements cut-through.
Cut through still needs to be done on the mempool, see issue #1277 
Added unit tests
> sw cut through on blocks

- base_layer/core/Cargo.toml
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/proto/mod.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/proto/mod.rs
- base_layer/core/src/transactions/aggregated_body.rs
- base_layer/core/tests/mempool.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/config.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
This PR implements base node monitoring for the Wallet to periodically ask a base_node if a pending CompletedTransaction has been mined yet.
When a Completed transaction is detected as broadcast to the mempool the Wallet will start querying the base_node for the outputs that have been mined.
When the wallet starts up it will go through stored completed transactions and check which have the broadcast state and start monitoring them for being mined
Closes https://github.com/tari-project/tari/issues/640
Closes https://github.com/tari-project/tari/issues/888
Closes https://github.com/tari-project/tari/issues/887
Tests provided
> Implement wallet base node monitoring for broadcast transactions

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Mistakenly used from_raw instead of from_ptr for strings that can originate outside of rust.
Cleaned up variables for sign message.
cargo-fmt
Bug fix
> Bug Fix - Sign and Verify messages

- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
This PR implements the ability to import a UTXO into the wallet by providing an amount and a private key. The UTXO will be added to your available balance and a faux CompletedTransaction will be created to record the event of adding the UTXO in the Transaction Service.
Closes https://github.com/tari-project/tari/issues/1249
Test provided
> Implement `import_utxo(…)` for wallet

- applications/tari_base_node/src/builder.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/connection_manager.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet_ffi/src/lib.rs
This change is due to database lock errors occurring on CI and the mobile environments. This change means there is only a single connection pool that will only serve a single connection the Sqlite database at a time. This will hopefully eliminate any potential for locks.
Tests updated
> Create only one R2D2 connection pool for the entire wallet

- applications/console_text_messenger/Cargo.toml
- applications/grpc_wallet/Cargo.toml
- applications/tari_base_node/Cargo.toml
- base_layer/core/Cargo.toml
- base_layer/key_manager/Cargo.toml
- base_layer/mmr/Cargo.toml
- base_layer/p2p/Cargo.toml
- base_layer/wallet/Cargo.toml
- base_layer/wallet_ffi/Cargo.toml
- comms/Cargo.toml
- comms/dht/Cargo.toml
- infrastructure/crypto/Cargo.toml
- infrastructure/storage/Cargo.toml
- infrastructure/tari_util/Cargo.toml
Bumping tari_utilities to v0.1.0
"External" crates, inc tari_crypto depend on tari_utilies.
Therefore it should keep to semver conventions.
To keep with semver conventions, breaking changes must
increase the minor version.
Since moving to rand v0.7 introduced breaking changes, we bump the minor
version.
> Bump tari_utilities minor version

- .gitignore
- Cargo.toml
- applications/test_faucet/Cargo.toml
- applications/test_faucet/src/main.rs
- base_layer/core/Cargo.toml
- base_layer/core/src/lib.rs
- base_layer/core/src/transactions/helpers.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/node_comms_interface.rs
- base_layer/core/tests/node_service.rs
To help wallet users get some testnet Tari to play with, we're
adding some utxos to the genesis block that they can claim
from their mobile wallet apps.
This PR add a small application that generates the faucet UTXOs
and private keys.
The UTXOs will be added to the alpha-net genesis block.
The `create_utxo` helper function was extended to accept `OutputFeatures`
> Add testnet faucet generator

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/chain_metadata_service/handle.rs
- base_layer/core/src/base_node/chain_metadata_service/mod.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/states/helpers.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/node_state_machine.rs
- Implemented the listening logic for the BaseNodeStateMachine. It listens for chain metadata events received from the liveness and chain metadata service. If it detects that the current node is lagging behind the network it will switch to the block sync state. When no metadata was received for a prolonged period of time it will transition to the initial sync state, where it will request chain metadata from remote nodes. 
- Modified the BaseNodeStateMachine to have access to the executor and metadata event stream.
- Also added an extra state transition in the BaseNodeStateMachine,allowing the node to transition from the listening state to the InitialSync state when network silence was detected.
- Moved the determine_sync_mode function to a helpers.rs file, to allow the listening state and …
> Base node listening state

- base_layer/core/tests/helpers/nodes.rs
Disabled auto network join for all network based tests, there seems to be a connection collision.
This PR is required to ensure the liveness service doesn't auto join the network resulting in the tests failing.
Tests were modified.
> Fix for flaky propagation tests

- applications/tari_base_node/src/builder.rs
- base_layer/wallet/migrations/2019-10-30-084148_output_manager_service/up.sql
- base_layer/wallet/src/output_manager_service/config.rs
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
This PR implements the functionality for the Output Manager to query the base node to confirm the status of stored Unspent Outputs as UTXO’s that exist on the blockchain. If the UTXOs do not exist then the Unspent Outputs and moved to the Invalid Outputs collection.
This sync function is called when the Base Node Public Key is first set and an FFI API call is provided for the frontend to call the function whenever it feels it is required.
An event bus is also added to the Output Manager Service.
This functionality is meant to help a wallet make sure its state is consistent with that is on the blockchain. If a wallet is copied and the other copy spends some of the outputs when the first wallet starts up it will have an incorrect balance so this will allow the first wallet to sync its state …
> Implement Base Node Syncing for Wallet Output Manager Service

- base_layer/wallet/src/util/luhn.rs
- base_layer/wallet/src/util/mod.rs
The luhn mod 1024 checksum is added to allow us to detect transposition
errors in emoji ids. Luhn was selected over e.g. Damm becuase the Damm
algorithm was developed for 10-digit "alphabets", whereas we have a 1024
digit alphabet.
The weaknesses of the Luhn algorithm (missing some errors) are mitigated
as the alphabet size increases, so the false positive rate for emoji ids
should be neglibly small.
> Add checksum algorithm

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/blocks/new_blockheader_template.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/consensus/mod.rs
- base_layer/core/src/consensus/network.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/validation/chain_validators.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/diff_adj_manager.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_comms_interface.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/node_state_machine.rs
- When a blockchain db is created using a provided storage backend, it will check if the backend has a genesis block. If it doesn’t, it will use the Consensus manager to add the correct genesis block to the blockchain db depending on the configured network.
- Added a Network enum for configuring the chain network and retrieving the correct genesis block that should be used for that network.
- ConsensusConstants was added to the ConsensusManager and the network configuration was added to the ConsensusConstants with methods to access the configured network and retrieving the genesis block of the specified network.
- The dependency on the blockchain db was removed from the create genesis block functions to remove a circle dependency issue. An update_genesis_block_mmr_roots function was added …
> Network genesis block refactor

- RFC/src/RFC-0151_EmojiId.md
- RFC/src/SUMMARY.md
This document describes the specification for Emoji Ids. Emoji Ids are encoded node ids used for humans to easily verify
peer node addresses.
> Add RFC-0151 EmojiID

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/tests/node_state_machine.rs
- Modified the block sync logic to enable redownloading missing blocks or received blocks that haven't passed block validation. Bad blocks will be ignored and requested again from the network.
- Block sync was also changed so that only one block is downloaded at a time, this simplified determining what blocks were received and which blocks should be requested again.
- The block_sync_chunk_size was removed from BlockSyncConfig and max_block_request_retry_attempts was added to specify how many times the current node should attempt to request the block at a specific height again from different peer nodes.
- The MaxRequestAttemptsReached state event was added to allow a node that has exceeded the maximum request attempts to transition to the InitialSync state and attempt to reestablish …
> Recovery mode if an error occurs during BlockSync

- base_layer/core/src/base_node/backoff.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/initial_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/base_node/states/shutdown_state.rs
- base_layer/core/src/base_node/states/starting_state.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/node_state_machine.rs
This PR adds in an event channel so that the state machine can publish its state when it changes. This uses `tari_broadcast_channel` as we have a single producer, multiple consumer. 
We need to be able to notify  applications that the state machine changed state. The longer term solution to this would be to modify the state machine into a service. But because of and the simplicity of just adding a channel, for test net we only added a channel. 
The miner is one of the applications that require the use of the channel and it will require that the state machine notifies it when it goes into listing mode so that it can ask for a new block to start mining on.
I have added a integration test that confirms that the node publishes its state to the channel
> Added event channel to base node for event state streaming

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/core/Cargo.toml
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/node_state_machine.rs
This PR adds in the ability for the base node to mine and run. This PR adds in the ability for the miner to listen to the state event change channel from the state machine. 
It also fixes a minor bug in the minor logic and temporary fix for metadata reading not working
For testnet we require the basenodes to be able to mine for testnet using the blake pow. This adds in the ability
The basenode successfully increased difficulty and its chain.
> Base node mining

- applications/tari_base_node/src/builder.rs
Whitelisted peer nodes in the base node app were being excluded because
the MESSAGE_PROPAGATION flag was not set in their peer records,
resulting in them not being discoverable on the network.
This change set the peer feature flag to COMMNuICATION_NODE by default
so that peers are selected.
> Base node peers - fix feature flag

- infrastructure/storage/src/lmdb_store/store.rs
Started getting `MDB_BAD_RSLOT: Invalid reuse of reader locktable
slot` error on peer manager. Adding this flag resolves it.
https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/open/constant.NOTLS.html
```
Applications that multiplex many user threads over individual OS
threads need this option.
```
> Added MDB_NOTLS flag to LMDB env

- base_layer/wallet/src/util/emoji.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Modified EmojiID to return node_id in emoji format.
Removed method to create PublicKey form emoji.
> Implemented PublicKey to NodeID Emoji

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/node_state_machine.rs
- base_layer/wallet/src/util/emoji.rs
- Changed update_metadata to also update the storage metadata values in the backend.
- Changed the lmdb and memory backends to allow the metadata values to be replaced and updated.
- Added the lmdb_replace function to allow key values to be inserted and replaced if they already exist.
- Reverted the previous temporary fix from read_metadata.
These changes will fix the blockchain db metadata restore issue.
Added a restore_metadata test to demonstrate that the backend metadata values were correctly updated.
> Base node not loading meta data correctly

- comms/src/peer_manager/peer_storage.rs
Peer IDs were stored as None when they are replaced using `add_peer`. This is a problem when they are retrieved later.
> Set the peer id when replacing

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/initial_sync.rs
Add a check to see if stop has been requested during initial check for peers. Currently, the node has to finish its full check in the current state before it checks whether a stop has been requested. This PR adds a check in between each retry. 
I also added some logs for failures during the block sync. It might be worth adding the details of the peer that returned bad data in CommsInterfaceError so that the peer can be logged and potentially later removed if it continues to provide bad data
Currently if you start the node and type `exit` to stop it, it needs to finish the initial sync state to shut down.
> Allow base node to shut down if requested during initial check for peers

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/chain_storage/async_db.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/error.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/src/mempool/pending_pool/error.rs
- base_layer/core/src/mempool/pending_pool/pending_pool.rs
- base_layer/core/src/mempool/reorg_pool/error.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/core/src/mempool/unconfirmed_pool/error.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_state_machine.rs
- Changed the mempool service so that it listens to block events from the base node, a block event handler was added to allow the mempool to react to add block events and chain re-org events.
- Changed the inbound block handler of the base node to allow the network propagation of received blocks that produced a re-org of the local chain.
- Modified the blockchain database rewind_to_height and reorganize_chain functions so they return the blocks that were removed, these removed blocks are required to process a re-org in the mempool.
- The BlockAddResult ChainReorg event was changed to allow the mempool service event handler to obtain the set of added and removed blocks. 
- Replaced the PoisonedAccess error type with a BackendError in the OrphanPoolError, PendingPoolError, ReorgPoolError …
> MempoolService: handle add block and reorg events

- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/README.md
`ncurses` is just used for the pingpong example, however it is not available on windows and
so prevents windows users from compiling the tari source.
This PR makes the `cursive` library optional under the `pingpong-example` feature flag
> Make cursive an optional dependency

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/wallet_ffi/src/lib.rs
- common/Cargo.toml
- common/src/configuration.rs
- common/src/lib.rs
- comms/src/socks/client.rs
- comms/src/tor/client/types.rs
- config/tari_config_sample.toml
The following keys now work in base_node.mainnet and base_node.testnet config sections:
```toml
// Select one transport
// TCP
transport = "tcp"
tcp_listener_address = "/ip4/0.0.0.0/tcp/18189"
// TOR
transport = "tor"
tor_control_address = "/ip4/127.0.0.1/tcp/9051"
tor_control_auth = "none" # or "password=xxxxxx"
tor_onion_port = 18141
tor_forward_address = "/ip4/127.0.0.1/tcp/18141"
// SOCKS
transport = "socks5"
socks5_proxy_address = "/ip4/127.0.0.1/tcp/9050"
socks5_listener_address = "/ip4/127.0.0.1/tcp/18189"
socks5_auth = "none" # or "username_password=username:xxxxxxx"
tor_private_key_file = "~/.tari/mainnet/tor.key"
```
Closes #1362 
Ran a base node over tor
> Allow transports to be configured for base node

- .circleci/config.yml
* Cache the target and crate registries so that subsequent pushes
don't have to re-download and build the dependencies
* Run debug and release tests in parallel pipelines to try and
speed up overall builds
All builds prior to this were taking ±35min.
Cold builds (i.e. with dependency changes) should run about 5-7min quicker due to release and debug being in parallel.
Subsequent pushes may be up to 50% faster (depending on how far caching got). This PR took 16min to build from a hot start.
> Add crate caching and parallel operation to circleCI

- comms/src/memsocket/mod.rs
The hard coded port numbers in the memsocket tests had a chance of
conflicting with other tests using memsocket. The tests now acquire a 
port number before binding to it.
> Remove hard-coded memsocket port numbers

- applications/tari_base_node/src/builder.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/contacts_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/transaction_service/config.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/outbound/serialize.rs
- comms/src/lib.rs
- comms/src/protocol/messaging/messaging.rs
- comms/src/protocol/messaging/outbound.rs
The Comms stack now has an event bus that informs you when a message has been successfully sent where before you only knew it had been queued for sending after a discovery process has been successful.
This PR updates the Transaction Service to start monitoring the Messaging Events to wait for the confirmation that the message has sent or failed to send. If the message failed to send the client application will be informed via a Callback that the transaction Failed to send.
Closes https://github.com/tari-project/tari/issues/1260
Tests updated and provided
> Integrate the Comms Event Bus feedback into the Wallet Send Transaction

- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
This PR adds in the faucet utxo's for the testnet launch
We need to include the faucets for the testnet launch into the genesis block. This adds that
Unit test that loads the genesis block for rincewind and ensures its 4001 blocks
> add faucet for alphanet

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/p2p/src/comms_connector/mod.rs
- base_layer/p2p/src/comms_connector/pubsub.rs
- base_layer/wallet/src/storage/connection_manager.rs
- common/src/configuration.rs
- comms/src/peer_manager/peer.rs
* The node builder has been cleaned up significantly.
* The `BlockchainBackend` has been abstracted away behind a  `NodeContainer` enum that exposes a set of methods that   are backend-agnostic.
* This lets us remove all the duplicated code in the builder logic.
* All the functions in the builder have been refactored to have a *single responsibility*.
* The miner builder code has been collected up and grouped together.
* A hash rate calculator hash been added to `blake_miner`.
Every minute, if a block hasn't been found, it'll log the hashrate to
the logs (in MH/s).
* Many log messages have been added to the code, the mining code in
particular.
_Please check_: The miner did not start because the `new_block_found`
flag was initially set to false, which put the mining thread in a
perpetual …
> Builder dry

- comms/src/transports/socks.rs
SO_KEEPALIVE was set too low and caused "Invalid Argument (OS error 22)"
on unix. Set to 1500ms.
> SO_KEEPALIVE setting cause invalid argument on linux

- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/node_state_machine.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
- base_layer/wallet/src/transaction_service/service.rs
- comms/src/builder/builder.rs
- comms/src/connection_manager/common.rs
- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/requester.rs
- comms/src/connection_manager/tests/manager.rs
- comms/src/consts.rs
- comms/src/net_address/multiaddr_with_stats.rs
- comms/src/peer_manager/async_peer_manager.rs
- comms/src/peer_manager/connection_stats.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/protocol/messaging/messaging.rs
- comms/src/protocol/messaging/mod.rs
- comms/src/protocol/messaging/outbound.rs
- comms/src/protocol/messaging/test.rs
- comms/src/test_utils/connection_manager_mock.rs
- comms/src/test_utils/test_node.rs
- comms/src/transports/socks.rs
Currently, if we cannot send to a peer the user of `MessagingProtocol`
has no way to know if the peer is not contactable.
This PR notifies the requester if they attempting to dial a peer which was not
contactable within a cooldown period (1 minute) so that they have some
way to handle that (give up, retry later etc).
The messaging protocol provides the following reasons as to why a message
failed to send:
```rust
pub enum SendFailReason {
/// Dial was not attempted because the peer is offline
PeerOffline,
/// Dial was attempted, but failed
PeerDialFailed,
/// Outbound message envelope failed to serialize
EnvelopeFailedToSerialize,
/// Failed to open a messaging substream to peer
SubstreamOpenFailed,
/// Failed to send on substream channel
SubstreamSendFailed,
}
```
Closes #1371 
Tested …
> Don't redial peer for a while if they cannot be contacted

- base_layer/core/tests/node_state_machine.rs
- base_layer/p2p/src/services/liveness/neighbours.rs
- base_layer/p2p/src/services/liveness/service.rs
Changed equality check for neighbour list to only use the node id.
This seems to fix the issue with `test_listening_lagging`
> Ensure liveness service correctly indicates pong from neighbour

- applications/tari_base_node/src/builder.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/initialization.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- comms/dht/src/discovery/error.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/proto/mod.rs
- comms/dht/tests/dht.rs
- comms/src/builder/builder.rs
- comms/src/connection_manager/common.rs
- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/mod.rs
- comms/src/lib.rs
Potentially malicious addresses were previously trusted by nodes. As an
example, an infected node accepts a loopback address from a malicious peer
and causes it to connect locally to some malware.
Addresses given by peers are now checked before being added to the
peer list.
Some test environments require the ability to use /memory and/or localhost addresses,
so a configuration item was added to comms to explicitly enable "test addresses".
Currently, the wallet and base node have these enabled to prevent
disruption to development on these applications. Once non-local addresses are used
for testnet environments, "test addresses" should be disallowed.
Closes #1315 - not validated against the transport, but the transport will reject addresses it doesn't support. This PR stops misuse of a node …
> Validate peer addresses before adding them to peer list

- base_layer/wallet_ffi/README.md
- base_layer/wallet_ffi/build.sample.config
- base_layer/wallet_ffi/mobile_build.sh
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
- comms/src/tor/client/client.rs
Add COOKIE authentication support to tor control client.
This is needed for Tor.Framework.
mobile_build.sh changes
- Added ability to disable cargo clean when doing mobile builds
- Updated mobile build readme
> Add tor COOKIE auth support

- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/proto/mod.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/service/mod.rs
- base_layer/core/src/proto/mod.rs
Using cfg_if! doesn't integrate well with CLion and makes navigating the code with features like "Go to definition" not work. This isn't a necessary change, but makes it easier to work with the project
> Remove cfg_if for better IDE integration

- applications/tari_base_node/src/parser.rs
- base_layer/wallet/src/output_manager_service/service.rs
Changed the wording for invalid commands to be slightly friendlier. Also formatted the wallet balances as well as slightly changing the wording of the balances.
The wallet balances were all on one line.
Manually, as well as running `cargo test`
> Updated wallet wording and formatting

- base_layer/core/src/transactions/transaction_protocol/recipient.rs
- base_layer/core/src/transactions/transaction_protocol/sender.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet_ffi/src/lib.rs
The frontend considers a transaction as Completed only once it is mined. However the Transaction manager considers a CompletedTransaction to be one that have been completely negotiated between parties and is now ready to be Broadcast and Mined.
In order to present both truly pending and CompletedTransactions in the Completed and Broadcast states as Pending to the frontend this PR adds some logic to return them in the `wallet_get_pending_outbound_transactions(…)` and `wallet_get_pending_inbound_transactions(…)` FFI function calls. They are also excluded from the `wallet_get_completed_transactions(…)` function call which only include CompletedTransactions with the Mined status.
FFI tests updated to account for these changes
> Update FFI Tx listing functions for pending & completed transactions

- common/src/lib.rs
- config/README.md
- config/tari.config.json
Add the JSON config definition that Tari Config Generator will use to
create the configuration options.
Add a README explaining the purpose of the file.
Create the presets folder that will hold a set of preset config files.
Update the CLI prompt to indicate the presence of the config
generator
> Add configuration file JSON definition

- base_layer/core/src/base_node/chain_metadata_service/service.rs
- base_layer/core/src/base_node/proto/chain_metadata.proto
- base_layer/core/src/base_node/proto/chain_metadata.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/src/proof_of_work/difficulty.rs
- base_layer/core/src/proof_of_work/proof_of_work.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/node_comms_interface.rs
This PR adds the geometric mean of the pow of the chain tip to the chain meta data struct and messages
We decide on reorgs based on the the Proof of work and not the chain length. The current metadata struct does not include this. We need to download the complete chain before we look at this.  With this PR we can just compare the pow and not only the length
> Add proof of work to the chain meta data

- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
Added `InterfaceError:DeserializationError(String)` to describe any
byte data passed into the interface which could not be deserialized.
This error is used when the tor identity data fails to deserialize.
> Added error for failed tor identity deserialization

- base_layer/core/src/transactions/tari_amount.rs
When formatting `µT >= 1e6` rather format as `T`
When formatting MicroTari that is greater than 1e6 rather display it as Tari.
Appended a unit test to display MicroTari > 1e6
> Format MicroTari as Tari when > 1e6

- common/src/configuration.rs
- common/src/lib.rs
- common/src/logging.rs
Default log and configs files are now compiled into the binary so that
they don't have to exist in deployments
> Fixed config and log creation when not running base node from source

- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/initial_sync.rs
Change the intial sync so that it compres the total accumulated proof of work and not the longest chain when comparing two chain tips.
Reorg is done on the geometric mean of the proof of work of the chain tip. The intial sync only looks at the total height of the chain when deciding to enter sync mode or not. This causes the node te enter sync mode prematurely. If it encounters a chain tip further ahead of it but with lower proof if work, it will get stuck as it will keep on entering sync state and failing to reorg as it already has a greater proof of work chain. This causes the base node to get stuck.
> Initial sync compare pow

- base_layer/wallet/README.md
- base_layer/wallet_ffi/README.md
- comms/dht/src/dht.rs
- infrastructure/storage/tests/lmdb.rs
- Conditional compilation was added to exclude `store_forward` Tokio layer to be added for Windows builds. This removes  `store_forward` functionality from Windpows, but provides a temporary fix.
- Small refactoring for `fn load_users()` in `lmdb.rs`
- Windows build and run instructions where SQLite is a dependency
The `tari_base_node` creates a stack overflow error when run in Windows. This has been traced to the implementation of multiple Tokio layers in `pub fn inbound_middleware_layer` (compliments due to @sdbondi). Excluding the 2x `store_forward` Tokio layers works for now. It seems this problem is related to the amount of layers added as well.
- The `tokio::runtime::Builder::new().thread_stack_size` has been increased from 2MB to 200MB but this did not solve the problem.
- …
> windows_compatibility_tari_base_node

- comms/dht/src/dht.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/logging_middleware.rs
- comms/dht/src/proto/mod.rs
- Shorter code in the logging layer. Unfortunately, could not avoid the
service clone (cheap anyway).
- Added better log for explicit rejection of messages.
- Fixed up some code warnings
> Quick clean up of message logging layer, reject msg log

- comms/src/utils/multiaddr.rs
- config/tari_config_sample.toml
Added a Dns4 match for the MultiAddr to SocketAddr resolver. This allows for dns based tor_control_addresses in the config.
The Dns4 match attempts to resolve the dns address using `std::net::ToSocketAddrs` it will then use the first result it finds as the ip address.
I also removed 2 whitespaces before some comments in the sample config file. It just allows for a cleaner parsing when generating a succinct config with `cat config/tari_config_sample.toml | grep -v '^#' | grep -v '^$' > clean_config.toml` 
This allows use of /dns4 multiaddresses
Fixes tari-project/tari#1426
Ran `cargo test`
Included 2 tests to test for successful resolution as well as a failed resolution
> Add dns4 to the MultiAddr to SocketAddr resolver

- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Now that Completed transaction can appear in the pending lists until they are mined it will be useful to find the status of these pending transaction via the FFI
Updated the wallet_ffi integration test to check it works.
> Add a status field to Pending Inbound and Outbound transactions

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/mempool/async_mempool.rs
- base_layer/core/src/mempool/error.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/mining.rs
- base_layer/core/tests/wallet.rs
- base_layer/wallet_ffi/src/lib.rs
- Added async_mempool for spawning blocking threads for the mempool functions.
- All Mempool calls in the mempool service inbound handlers were changed to the async alternatives.
- The base node inbound handlers were also updated to make use of the async versions.
- The mempool process_published_block/s and has_tx_with_excess_sig functions were changed to take as input owned copies of the signature and block to allow the async calls to be constructed.
- A static lifetime constraint was added to the blockchain backend generic of the mempool service and inbound handlers to enable async mempool calls. 
Making the mempool functions async might resolve some of the blocking behaviour experienced in the base node application.
None, existing tests are still functioning.
> Async Mempool

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/util/emoji.rs
- base_layer/wallet_ffi/src/lib.rs
Update emoji IDs
We've settled on using a 256-bit public key to represent emoji IDs and 256-character alphabets. This commit switches the code back to that; and updates the tests accordingly.
Docs have also been improved.
> 33 character emoji ids

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/transport.rs
- base_layer/wallet_ffi/src/lib.rs
- common/src/configuration.rs
- comms/src/connection_manager/tests/manager.rs
- comms/src/macros.rs
- comms/src/tor/control_client/client.rs
- comms/src/tor/control_client/commands/add_onion.rs
- comms/src/tor/control_client/commands/key_value.rs
- comms/src/tor/control_client/error.rs
- comms/src/tor/control_client/parsers.rs
- comms/src/tor/control_client/test_server.rs
- comms/src/tor/hidden_service/builder.rs
- config/tari_config_sample.toml
- Tor client parses `some-key="value1" "value2"` responses from tor
control port
- Fix `--create_id` not working saving the json
- Allow tor socks address to be overridden using
`tor_socks_address_override`
- Fixed missing default for `tor_onion_port` config
The tor control client did not correctly handle the response when additional listener ports are configured  `250-net/listeners/socks="127.0.0.1:9050" "unix:/run/tor/socks"`
tor_onion_port did not have a default
`--create_id` would didn't create the node  identity
> Tor control client correctly handles multi-string values

- common/logging/log4rs-sample.yml
This PR updates the default log4rs settings file to include yamux logs into the network layer logs.
Yamux logs does not belong in the base_layer logs
> Update default log to include yamux into the network log

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/service/error.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/service/service_request.rs
- The Base node service was updated to limit the blocking behaviour when messages are being processed..
- A task will be spawned for every request, response and block received by the base node service to allow the task to be completed independently and not cause the base node service to block messages while other messages are being processed.
- To enable the sharing of the base node handlers for the different spawned tasks, the block event publisher was placed in an async-std RwLock and a clone implementation was added.
- The WaitingRequests struct was introduced to manage the set of waiting requests.
- The Waiting requests hashmap was changed to a WaitingRequests struct with an internal lock to make it shareable between the different spawned tasks.
These changes allow the Base node …
> Improved async message handling in base node service

- base_layer/core/src/base_node/service/error.rs
- base_layer/core/src/base_node/service/mod.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/service/service_request.rs
- base_layer/core/src/base_node/service/service_response.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/helpers/waiting_requests.rs
- base_layer/core/src/mempool/service/error.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/core/src/mempool/service/mod.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/service/response.rs
- base_layer/core/src/mempool/service/service.rs
- The mempool service was updated to limit the blocking behaviour when messages are being processed. A task will be spawned for every request, response and received transaction, allowing the tasks to be completed independently and not cause the mempool service to block while messages are being processed.
- WaitingRequests was moved to helpers and was modified to allow the base node service and mempool service to use it. 
- An implementation of clone was provided to allow the mempool service to be shared between tasks.
- The unused executor was removed from the mempool service.
These changes allow the mempool service to handle all received messages as independent tasks, limiting blocking while listening for new messages.
None, current tests remain functioning.
> Async message handling in mempool service

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/diff_adj_manager.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/helpers/sample_blockchains.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_comms_interface.rs
Removed a bunch of clones on ConsensusManager and consolidated the version code for Blockheader. 
The main aim was to remove the ConsensusManager field from the BlockchainDatabase because it is only used in the constructor. Furthermore, it is only used for the blockchain version which I saw in most places was set to 0 or a value that didn't make sense.
I tried to apply this logic:
1. When creating a new block, use the value in the consensus rules.
2. When retrieving an old block, use the value it has
In most cases using the BlockBuilder,  the version would be set and then replaced immediately with the `header()` method. I introduced the `BlockHeader.into_builder()` method to use the header instead
> Remove consensus manager field from DB

- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Added method to FFI to convert an emoji string back into a public key.
Needed to get public keys back from 33 char emoji_ids
* [] Breaking change (fix or feature that would cause existing functionality to change)
> Public Key from Emoji String

- comms/dht/examples/memorynet.rs
- comms/examples/tor.rs
- comms/src/builder/mod.rs
- comms/src/builder/tests.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/connection_manager/tests/listener_dialer.rs
- comms/src/connection_manager/tests/manager.rs
- comms/src/peer_manager/peer.rs
- comms/src/protocol/error.rs
- comms/src/protocol/identity.rs
- comms/src/protocol/messaging/outbound.rs
- comms/src/protocol/mod.rs
- comms/src/protocol/negotiation.rs
- comms/src/protocol/protocols.rs
- comms/src/tor/control_client/client.rs
- comms/src/tor/control_client/commands/add_onion.rs
- comms/src/tor/control_client/commands/del_onion.rs
- comms/src/tor/control_client/commands/key_value.rs
- comms/src/tor/control_client/response.rs
- comms/src/tor/control_client/types.rs
This PR removes a round of comms when negotiating protocols if the protocols supported
by the peer are known ahead of time (see #1404).
The "normal" negotiation protocol as follows (best case):
1. Initiator sends protocol candidate, and waits
1. Responder responds with TERMINATE flag and name of protocol to speak
1. Protocol begins
The "optimistic" negotiation is as follows:
1. Initiator sends protocol candidate with OPTIMISTIC flag (no waiting)
1. Protocol begins
Responder will receive the protocol name with the OPTIMISTIC flag and
either close the stream (if invalid) or accept and begin the protocol.
EXTRA: logs for tor control client
Closes #1381 - establishing connections should be as efficient as possible.
Unit tests + existing test pass
> Implemented optimistic protocol negotiation

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/p2p/src/services/liveness/mock.rs
- base_layer/p2p/src/services/utils.rs
- base_layer/wallet/src/contacts_service/mod.rs
- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- comms/dht/src/inbound/dht_handler/task.rs
* Wallet request messages that printed a lot of debug information now
prints a human-friendly summary
* Normalise LOG_TARGET strings:
* to `c::bn`, short for `core::base_node`
* drop the leading `base_layer`
* Add target: LOG_TARGET in a few spots that were missing it
> Neaten up log messages

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/connection_manager/requester.rs
- comms/src/test_utils/connection_manager_mock.rs
- `list-connections` command will list the currently active connections
- Changed all commands to kebab-case
- `get-peers` to `list-peers`
- Tab completion moves to the end of the line
```
>> list-connections
Id = 10, Node ID = ee3db715400b5ad6, Direction = Outbound, Peer Address = /onion3/xxxxxxxx:18141
Id = 11, Node ID = fd728cb5b86eae64, Direction = Outbound, Peer Address = /onion3/xxxxxxxx:18141
```
> Added list-connections command

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Updated test_broadcast_transaction method to accept a tx id
Updated test_mine_transaction to accept a tx id
> Updated mine and broadcast methods to accept a TX ID

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/mod.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/waiting_requests.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/core/tests/node_comms_interface.rs
- base_layer/core/tests/node_service.rs
- Simplified the base node service and mempool service request response system by removing the unused multi peer response system.
- Simplified the WaitingRequests system as multiple responses do not need to be tracked before resolving the waiting requests.
- Updated the inbound handlers of the mempool and base node service to use the simplified request system.
- Removed the unused NodeCommsRequestType.
These changes remove the unused multi peers request response system, which simplifies the base node and mempool services.
Updated the base node service and mempool service tests to make use of only the single peer request system.
> Removed base node service multi peer request system

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/transport.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- common/src/configuration.rs
- comms/src/builder/error.rs
- comms/src/builder/mod.rs
- comms/src/peer_manager/connection_stats.rs
- comms/src/peer_manager/peer.rs
- comms/src/tor/hidden_service/mod.rs
- comms/src/transports/mod.rs
- comms/src/transports/socks.rs
- comms/src/transports/tcp_with_tor.rs
- config/tari_config_sample.toml
- Added optional setting to tcp transport that allows the node to use a direct connection
to the internet for all traffic _AND_ use Tor for peers which
advertise a tor address.
- `list-peers` displays last connection info
Closes #1350 
Base node works and joins network with "tcp with tor" transport.
> Allow nodes to use TCP transport and connect to onion addresses

- applications/tari_base_node/README.md
- applications/tari_base_node/setup.sh
- scripts/create_bundle.sh
The install script kills tor after `brew install tor`
This is because tor is running with default args at this point, and we
need to kill it to restart with custom arguments
Also added a short set of instructions in the README file and included
it in the bundle.
> Update osx install script

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/chain_metadata_service/handle.rs
- base_layer/core/src/base_node/chain_metadata_service/mod.rs
- base_layer/core/src/base_node/chain_metadata_service/service.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/helpers.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/tests/node_comms_interface.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/node_state_machine.rs
- Modified the base node state system to allow the sharing of the current set of sync peers that have the current best network state.
- Modified the chain_metadata_service to share PeerChainMetadata on its events, this includes the node_id of the peer that provided the metadata.
- The base node service and outbound node interface was changed to allow requests to be sent to either a random base node or a specified peer.
- The service_request_timeout test was fixed where the one node should not be reachable for the test to function correctly.
The base node state machine tests were updated to make use of the new sync peers functionality.
These changes will allow the block syncing to only request the missing headers and blocks from a subset of peer nodes that the local node has recently been …
> Block sync from active peers with best chain

- applications/tari_base_node/src/builder.rs
- base_layer/core/tests/wallet.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/migrations/2019-10-30-084148_output_manager_service/up.sql
- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/error.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/connection_manager.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/src/lib.rs
R2D2 was added to provide thread safety for the Async wallet services with the thought that in the future we might require a pool of connections but after testing we are having problems with Segmentation Faults on Android coming from the R2D2 thread pool.
So this PR removes the threadpool in favour of a single SqliteConnection maintained behind a Arc<Mutex<>>. This is a much simpler arrangement and will hopefully be more stable on mobile platforms.
I also moved the wallet logging to being initialized in the Wallet FFI so that logging starts as early as possible.
Updated existing tests
> Remove R2D2 for Sqlite from Wallet

- applications/tari_base_node/src/builder.rs
- base_layer/p2p/examples/gen_tor_identity.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/wallet_ffi/src/lib.rs
- comms/Cargo.toml
- comms/src/builder/mod.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/tor/control_client/client.rs
- comms/src/tor/control_client/commands/add_onion.rs
- comms/src/tor/control_client/commands/del_onion.rs
- comms/src/tor/control_client/commands/key_value.rs
- comms/src/tor/control_client/commands/mod.rs
- comms/src/tor/control_client/event.rs
- comms/src/tor/control_client/mod.rs
- comms/src/tor/control_client/monitor.rs
- comms/src/tor/control_client/parsers.rs
- comms/src/tor/control_client/response.rs
- comms/src/tor/hidden_service/builder.rs
- comms/src/tor/hidden_service/controller.rs
- comms/src/tor/hidden_service/mod.rs
- comms/src/transports/tcp_with_tor.rs
If the tor server is restarted (for whatever reason), the hidden service
would cease to exist on the tor network making it impossible for clients
to connect into the node until the node is restarted.
This PR fixes this by adding a controller that is responsible for tor
hidden service reliability. If the tor control server disconnects, the 
controller will attempt to reconnect every 5 seconds until either 
it succeeds or is shut down. On success, clients will be able once 
more to connect to the node's hidden service.
Additionally, the TorControlClient now has the ability to subscribe to
events emitted by the tor control server and publish those on a tokio
broadcast channel. This could be useful down-the-line for determining
network availability/bandwidth usage etc.
This implementation …
> Detect failure and reestablish tor control connection + tor events

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/miner.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/mining.rs
- base_layer/core/tests/wallet.rs
- common/src/configuration.rs
This PR refactors the mining of the base node to more clearly separate goals. It also includes multi thread support. 
This PR also fixes a bug that allowed the miner to mine when the BN is behind. 
The mining module was very difficult to follow what goes on and how it functions. This PR some what cleans it up. It also makes it easier to support shutdown via channels via a future PR. 
The miner will now stop mining when the BN falls behind and exits listening state.
The miner can now mine multi threaded as well to better support multi core cpu's
> Mining refactor and multi thread support

- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
This PR adds in the ability to ask the base node for the last 10 headers of the current chain tip. 
It also allows the user to send to a emoji id pubkey and not just a hex pubkey
Getting the last 10 headers gives use full information about the state of the blockchain to the user. 
The wallets work on an emoji id and it will be use full to be able to directly send to those
> WIP UI improvements

- base_layer/wallet/src/output_manager_service/config.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
This PR adds in a new callback to the FFI that is called when the Base Node Sync process for the Output Manager service completes.
fn wallet_sync_with_base_node(...) now returns a u64 which is the request key used to identify the callback associated with this request.
Existing tests updated
> Add callback to FFI for Base Node Sync process completion

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/helpers/mock_backend.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- The blockchain db was modified to have a RwLock on the backend, this will be used to lock the backend to a consistent state when performing a large set of operations such as adding blocks or performing re-orgs. 
-  All functions and operations in the blockchain db were changed to allow a single read or write lock to be reused until the entire sequence of operations are complete before the lock is released.
- The write function of the blockchain backend trait was changed to 'mut self' and the unnecessary locks of the lmdb backend was removed.
- The full state validator is temporarily disabled until the next PR to allow the validators to reuse the read and write lock guards.
- Some of the chain backend tests were updated to make use of the mut backend.
These changes fixes an issue where …
> Blockchain db locked access for async reorgs

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/mining.rs
- base_layer/core/tests/wallet.rs
This allows the user to enable and disable mining in the CLI via a command
We want the user to be able to enable mining in the UI without the user needing to restart the node and set it in the config
> Enable mining in CLI

- base_layer/core/src/mining/miner.rs
Up the buffer count in the wallet channel receiving for utxo's
Currently the buffer is only 1, and it should only be one as these are the utxo's you give to the wallet. It should be a local call only to the db. But if this delays somewhat you can crash the miner
> fix wallet channel buffer

- applications/tari_base_node/src/parser.rs
- applications/test_faucet/Cargo.toml
- base_layer/wallet/src/util/emoji.rs
- base_layer/wallet_ffi/Cargo.toml
The send_tari command was causing a thread panic if an emoji id was
used. In refactoring the parsing logic, it was discovered that the
problem lay with `from_hex` in the tari_utilities crate.
The crate was patched with a fix and bumped to 0.1.2.
The send_tari command now works with both hex and emoji pubkeys.
> Update to tari_utils 0.1.2 and send_tari arg parsing

- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
- applications/tari_base_node/src/utils.rs
- base_layer/wallet/src/transaction_service/handle.rs
- config/tari_config_sample.toml
The PR notifies the user when a discovery is initiated and
completes (success/fail) when using the `send-tari` command.
Before this would be treated as an error.
> Handle discovery "error" when sending a transaction

- base_layer/p2p/src/initialization.rs
- comms/src/connection_manager/dial_state.rs
- comms/src/connection_manager/dialer.rs
- comms/src/connection_manager/manager.rs
- comms/src/protocol/messaging/outbound.rs
- comms/src/protocol/messaging/protocol.rs
- comms/src/protocol/messaging/test.rs
It is possible for a lock up to occur in the messaging procotol if
many messages are sent to the same failing peer.
This PR uses unbounded mpsc channels to eliminate this possibility.
Since these channels are used for outbound messaging, backpressure
is less of a priority.
I was not able to confirm in a unit test that bounded channels
causes a lock up, the messaging protocol performed robustly. However,
latency over a network and exponential backoff was not completely
factored in.
I have changed the backoff implementation in the base node to a
ConstantBackoff - 1 second between retries. This will greatly speed up
the time to failure and the time that failed messages have to sit in the
outbound buffer.
Base node lock up bug hunting
Unit tests for bulk failing messages
> Use unbounded channel for each peer's outbound message buffer

- applications/tari_base_node/src/parser.rs
Base node app now displays the emoji id when typing `whoami`
> Display emoji Id with whoami command

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- comms/dht/src/lib.rs
- comms/src/peer_manager/peer.rs
```
>> discover-peer c85bb4933d2e9e9e924e47530c00b987072da14c3a2a36b86e
🌎 Peer discovery started.
⚡️ Discovery succeeded in 1293ms!
This peer was found:
[ac414ecc153977fa] PK=c85bb4933d2e9e9e924e47530c00b987072da14c3a2a36b86e20cf6xxxxxxx /onion3/[redacted]:18021 "WALLET" Last connected at '2020-03-20 15:14:01.734128'.
```
- `discover-peer [emoji id]` works
- `list-peers` also lists wallets.
- `list-peers basenode` lists base nodes only (`list-peers bn` for short) 
- `list-peers wallet` lists wallets only (`list-peers w` for short)
> Added `discover-peer` command

- base_layer/core/src/blocks/block.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
Added a few `warns!` and elevated some `debug!` to `warn!`s when validation fails. Sometimes validation would fail and the message would get lost in a `map_err`
Example:
```
2020-03-20 15:16:17.509604000 [c::cs::database] WARN  Validation failed on block:block error
2020-03-20 15:16:17.509901000 [c::bn::states::block_sync] WARN  Validation on block f40990379633be877af4018df8c8c9f5d820d91833b0fa7237c0ab750b453671 from peer failed:block error. Retrying
```
This is now:
```
[c::val::block_validators] WARN  Block header MMR roots in 6ba19de27caba88fd88bade649a1d588f31446d7d7b967af9915a40c3889e65f do not match calculated roots
```
> Add warns! when validation fails

- base_layer/wallet/src/output_manager_service/service.rs
Add a Trace level log to log the Balance of the Output manager service when it is requested via the Service API
> Add balance trace log to OMS

- comms/dht/src/actor.rs
- comms/src/noise/socket.rs
The socket should immediately be closed if the noise protocol handshake
fails.
When the noise protocol is not adhered to the node should immediately close the socket without flushing (buffer discarded).
Used netcat to send garbage to the node. Before the socket would error but the socket would not close. With this change the socket closes and netcat returns a BrokenPipe error.
> Close the socket if peer sends garbage on noise handshake

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/tests/node_state_machine.rs
- The block sync logic was updated to be less reliant on syncing headers first allowing only basic header validation(sequence, hash chaining and linking to genesis block) to be performed during the block sync process.
- During block syncing it first attempts to determine if the local chain is on the best network chain. If it is, it can immediately start syncing blocks without first downloading the headers.
When it detects that a fork has occurred, it will attempt to find the split block height by downloading a set of headers from the minimum tip height to the genesis block. This can be done using only a few header bundle requests. Once the split height is determined syncing of blocks can be performed by requesting blocks by height from the split height to the network tip. Requesting …
> Faster block syncing with basic header validation

- common/logging/log4rs-debug-sample.yml
- common/logging/log4rs-sample.yml
The log file sample configurations are updated so that
* They both make use of rolling logs
* The 'debug' configuration will log very verbose information in large
10MB maximum files (150 MB total logs). tokio, mio and other 3rd party
libraries have a significantly fewwer logs (warn level).
* The `log4rs-sample.yml` file will only log info or higher, and only
errors from 3rd party libraries. The max log files are also set to 1MB.
> Update Log configuration sample files

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- config/presets/rincewind-simple.toml
There was a bug in the Output Manager Service UTXO Sync process where if a UTXO was imported into the OMS after a Sync message was sent but before the response was received.
In this case the hash of the imported UTXO was not sent in the query and when the resposne came it does not include the new UTXO which was considered to be invalid.
This PR adds the list queries UTXO hashes to the list of pending sync queries and only hashes that are in that list and not in the response and invalidated.
Test was updated
> Fix for UTXO sync in output manager

- comms/src/tor/control_client/monitor.rs
- comms/src/tor/hidden_service/controller.rs
The contract for AsyncRead is generally that if there is an `Some(Err(_))`
or `Some(None)`, `poll_read` should never be called again. This fix
breaks the loop if a socket error is received. The tor controller will
attempt to reconnect on a "fresh" socket.
This prevents infinite looping of this log (confirmed on iOS app):
```
[comms::tor::control_client] ERROR Line framing error when reading from tor control server: 'Io(Os { code: 57, kind: NotConnected, message: "Socket is not connected"  })'
```
The following is unclear:
1. The reason this happens in the first place (tor crash?)
1. If the connection can be reestablished (maybe tor crashed and
restarted? If so then reconnect will work)
> If tor socket has some kind of error, it shouldn't be read from again

- applications/tari_base_node/src/main.rs
If mining threads are set higher than the blocking threads the node
stops responding, mainly due to the async db not being able to schedule
work while mining uses all available blocking threads.
> Make sure there are enough blocking threads to do mining

- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
This change allows an existing orphan block to be replaced instead of causing a panic.
Fixes a duplicate key issue when inserting the same orphan block.
Covered by existing tests
> Orphan block duplicate key issue

- base_layer/core/src/consensus/consensus_constants.rs
- Changed the max_block_transaction_weight to an estimate that will produce blocks closer to 1MBytes. Byte sizes estimated using bincode conversions.
  | Bytes | Counts | Weights per gram | Total
-- | -- | -- | -- | --
header | 254 | 1 | 0 | 0
input | 57 | 625 | 1 | 625
output | 737 | 1250 | 4 | 5000
kernel | 147 | 625 | 1 | 625
  | Total MBytes: | 1.000408173 | Total Weights: | 6250
Change will allow blocks to be produced that are closer to 1MBytes.
Only existing tests.
> Better max_block_transaction_weight estimate

- base_layer/core/tests/wallet.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/config.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
Add an initially shorter timeouts for Broadcast and Mined queries in Tx service to make them more responsive. Later timeouts should still be longer
Also some more logging.
> Add an initially shorter timeout for Base Node queries from Tx service

- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/core/tests/node_state_machine.rs
- Modified block syncing to check if the chains of the sync peers have been extended.
- Block syncing will keep on downloading blocks and check if the sync peer chain has been extended until the tip is reached.
These changes fixes an issue where the local chain is extended while a remote chain is being downloaded up to an old tip and the reorg is not successful as the local tip was updated and has a higher accumulated difficulty compared to the old tip that was synced.
Covered by existing tests.
> Fix for incomplete chain sync issue

- comms/dht/examples/memory_net/drain_burst.rs
- comms/dht/examples/memory_net/mod.rs
- comms/dht/examples/memorynet.rs
- comms/dht/src/actor.rs
- comms/dht/src/logging_middleware.rs
- comms/src/peer_manager/manager.rs
- comms/src/peer_manager/peer_storage.rs
- Dht closest peer selection was not taking ClosestPeerRequest::features
into account. This could lead to messages only being propagated to
wallet nodes without being propagated to base nodes (which propagate
messages further)
- Memorynet testing/demonstrating discovery with 3 different levels of
privacy
> Small DHT propagate fix

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
Currently the Transaction service monitors for CompletedTransactions being Broadcast and then after that transition for Broadcast transactions to change to being Mined. However if for some reason the Transaction service missed a transaction being broadcast and it moves straight to being mined the Transaction service wouldn’t note that. 
This PR updates the transaction service to also check if Completed Transactions are mined and not just broadcast to cater for this case.
Tests updated to cater for this change
> Update transaction service to monitor for completed tx’s being mined

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/state_machine.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/node_state_machine.rs
- Modified block syncing to keep track of sync peers during requests and ban bad nodes when they provide invalid blocks or respond incorrectly.
- The ban will ensure that they wont be able to establish connections in the future and wont be able to influence the local nodes block syncing.
- Removed the accumulation of the different metadata rounds as some of these peers might have been banned in later rounds.
- Removed the unused ListeningConfig.
This will enable nodes to detect bad nodes and exclude them from their local network.
A test was added to demonstrate the banning of sync peers: test_sync_peer_banning.
> Ban sync peers that provide invalid blocks and responses

- comms/src/builder/consts.rs
- comms/src/protocol/messaging/protocol.rs
- comms/src/protocol/messaging/test.rs
Messaging protocol makes a contract with clients that for every message
sent, you will either get back a MessageSent or SendMessageFailed event
for that (tagged) message.
Messaging protocol did not add the message to the retry queue after
one attempt. As a side effect of the bug, the above contract was broken.
See description
Changed existing unit test to attempt sending more than once and updated asserts to match expected results
> Fix bug when retrying message send in MessagingProtocol

- base_layer/service_framework/src/reply_channel.rs
- comms/dht/src/inbound/deserialize.rs
- comms/dht/src/logging_middleware.rs
`ready()` is deprecated, used `ready_and()` and `oneshot` where
appropriate.
> Fixed `ready()` deprecation warnings from tower upgrade

- applications/tari_base_node/src/miner.rs
- base_layer/core/src/base_node/state_machine.rs
- base_layer/core/src/base_node/states/events_and_states.rs
- base_layer/core/src/base_node/states/mod.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/helpers/chain_metadata.rs
- base_layer/core/tests/helpers/mod.rs
- base_layer/core/tests/mining.rs
- base_layer/core/tests/node_state_machine.rs
- base_layer/core/tests/wallet.rs
The base node event stream currently emits state changes, rather than
events.
This is likely not what was intended, since other parts of the code typically
want to respond to events rather than state changes.
This is corroborated by the fact that the function in the miner code
that makes use of the stream was in fact called the "event stream".
Now that the miner code can respond to events we can pause mining when
the block chain lags behind the network and it can start mining
again when the blocks have synchronised.
> Base node emits events rather than states

- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
Fix bug in median time stamp
Ignore test that deletes .tari folder
This PR fixes a bug where the incorrect target difficulty is added to the LWMA algo. 
Fixes a bug that was introduced with #1558 where the median timestamp is wrongly added
Removes a test that deletes the entire .tari folder
Difficulty is adjusted based on the target difficulties that are added. The difficulties that are added is not the same difficulty that is used as the actual target. This fixes it. Also reduced the initial difficulty. 
Median timestamp should always use the last `11` blocks. Since #1558 it always uses 0-11. This fixes that it only uses the last `11` blocks.
The test : `test_bootstrap_config_from_cli_and_load_configuration` will delete the entire .tari folder which might delete the running config of a …
> Fix bug in difficulty algo

- common/logging/log4rs-debug-sample.yml
- common/logging/log4rs-sample.yml
Update the default logging settings so only Warn ends up in std_out and base_node message end up in the base_layer appender. Also updated the comments.
Default logging is stale as targets have changed.
> Update default logging settings

- comms/Cargo.toml
- comms/src/connection_manager/common.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/multiplexing/yamux.rs
- comms/src/protocol/messaging/test.rs
- comms/src/test_utils/mocks/peer_connection.rs
0.4.5 includes yamux PR 80. This PR closes the stream after an error is
received. This is expected behaviour for streams.
There is no need to send a Result out of inbound substreams, so that
simplified the code a bit.
Removed the need to handle error edge cases in the yamux worker. yamux#80 removed the possibility of the endless loop log flooding issue.  
Existing tests do a decent job at testing for this.
> Upgraded yamux 0.4.5

- base_layer/core/src/blocks/genesis_block.rs
In main-net, this value will be much higher, so
we should test a higher maurity in testnet as well.
Also updated the gen block timestamp
** This is a hard-fork change ** You need to rest your node to continue synching after this change is deployed.
> We've been testing on 1 block coinbase maturity.

- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/mempool/async_mempool.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/mempool/pending_pool/pending_pool_storage.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool_storage.rs
- base_layer/core/src/transactions/transaction.rs
- base_layer/core/tests/mempool.rs
- base_layer/core/tests/node_state_machine.rs
- Changed the handling of an incoming transaction in the mempool service so it only logs an error when a received transaction fails validation and does not return an error result.
- Added more detailed log messaging into mempool service, handlers, mempool and the different sub pools.
- Added display implementations for TxStorageResponse, MempoolRequest and Transaction.
- Modified mempool insert to return which pool a transaction has been inserted into, this will make the log messages more descriptive.
These changes will make tracking of a transaction using logs simpler and will ensure the mempool service remains operational when an invalid transaction is received.
Existing tests cover changes.
> Mempool logs and handling of invalid transactions

- applications/tari_base_node/src/parser.rs
The android app includes pipes in the copied Emoji ID - this may be
desirable for a visual check but creates extra work when pasting into
a base node. This PR ignores pipes pasted in commands taking public keys/emoji IDs.
> Cleanup public key or emoji ID input

- base_layer/wallet/migrations/2019-10-30-084148_output_manager_service/up.sql
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
The behaviour in the transaction service when sending transaction where discovery failed or when discovery passed but the actually sending failed was wrong. It results in a pending transaction being added to the wallet that could never be completed as it was never sent and will never be resent. Another issue was that if during discovery the app was closed or crashed the encumbered UTXOs will never be released. The idea of short-term encumbrance was added to the Output Manager service to deal with this.
This PR implements the following:
- The handling of the flow of sending a transaction with the various permutation of discovery and send failure are now handled correctly
- Found a bug in the MessageEvent handling in the Comms layer that signals when a transaction was actually sent and now …
> Update Transaction Service to handle Discovery and failed sends properly

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/mempool/error.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/proto/mempool_request.rs
- base_layer/core/src/mempool/proto/service_request.proto
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- Added a SubmitTransaction mempool request that allows wallets and other services to insert a transaction into the mempool and allow them to determine where a transaction was inserted and if it was discarded by the mempool.
- Modified the transaction propagation to only propagate transactions that have been accepted by specific mempool subpools.
Enables wallets to insert a transaction using a mempool request that responds with the state of the insert instruction
No tests have been added.
> Mempool service submit transaction request

- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/tests/node_state_machine.rs
Enables requesting blocks in batches from remote nodes, this will speedup block syncing for test net where most blocks are empty.
This will speedup block syncing on the test net.
Covered by existing tests.
> Requesting block sets for block syncing 

- base_layer/core/src/base_node/chain_metadata_service/initializer.rs
When the chain metadata service receives newer chain metadata it will replace the set of chain metadata on the channel instead of queuing it. 
This change will ensure that old chain metadata will be discarded when a new set of chain metadata becomes available, fixing the issue where the state system enters an endless loop due to old chain metadata on the channel.
No tested.
> Fix for state system endless loop issue

- base_layer/core/src/chain_storage/blockchain_database.rs
If a block is added that is already in the orphan pool it should be replaced and check for reorg. Sometimes blocks have come in before the db is at that height, and it'll be added to the orphan pool. When syncing, when trying to add that block, it should check for a reorg
> Check for reorg if adding a block already in the orphan pool

- base_layer/core/src/base_node/states/listening.rs
- This change ensures that when the chain metadata is not updated on the metadata event stream then it wont reprocess the old chain metadata.
When the chain metadata event stream is no longer updated, then this will ensure that the exist event does not get processed multiple times by the base node listening state.
> Disable reprocessing of old chain metadata events

- base_layer/core/tests/wallet.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet_ffi/src/lib.rs
This PR upgrades the transaction service’s base node monitoring for when its transactions are broadcast and then mined.
Things this PR does:
- Use the new MempoolRequest to submit a transaction that will produce an Ack from the mempool
- Once a Transaction is detected as broadcast it will be monitored in both the Mempool and in the blockchain
- If a transaction drops from the mempool BEFORE it appears in the blockchain it will be cancelled.
Tests provided
> Update the transaction service base node monitoring heuristics

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/mempool.rs
- Fixed an issue where a block that has been committed after an invalid block was added can’t be recovered. This was achieved by applying the MMR and storage transactions together and only committing them to the backend when they all succeeded.
- Fixed issue where fetch_block would not return blocks that are before the nodes pruning horizon.
- Modified some of the block builder functions to allow lmdb and memory backends to be used.
The LMDB backend was left in an inconsistent state when an invalid block was added, these changes will help alleviate this issue.
Added the test invalid_block that checks that a valid block can be added after an invalid block was added, this test failed before these changes were applied.
> LMDB backend: adding of an invalid block issue

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/block_builders.rs
- base_layer/core/tests/node_state_machine.rs
- Fixed issue where the blockchain db with an LMDB backend was unable to rewind to the correct height and perform reorgs in some situations.
- Added checks for existing headers, utxos and kernels so it is similar to the memory db implementation.
- Removed the orphan duplicate check from the memory db as orphan blocks should be replaced without producing an error.
- Changed some of the block builder functions to make it easier to test with memory or lmdb backend.
The rewind_to_height and handle_reorg tests failed when using an LMDB backend, these changes fixes this issue. 
> Fixed blockchain db rewind to height and reorg issue

- base_layer/core/Cargo.toml
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/service/local_service.rs
- base_layer/core/src/mempool/service/mod.rs
Provide a Local Mempool Service struct that acts as a wrapper around a
Sender-Requester pair.
A single utility function `request_stats` is added that handles the
channel mangling for you and returns a future for the current  mempool stats.
This actual stats colleciton is not done right now; a subsequent PR will
connect the request stream to the main mempool service loop.
A test that demonstrates that the service is functional is provided.
A local handle into the mempool is very useful for the base node application.
> Add local Mempool Service struct

- base_layer/core/src/chain_storage/async_db.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
Async db calls do not always return, these logs will be able to identify
when this happens.
```
DEBUG [add_block] Entered blocking thread. trace_id: '4067860168'
DEBUG [add_block] Exited blocking thread after 164ms. trace_id: '4067860168'
```
> Added logs for async db enter and exit

- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
There was a chance that a timeout would fire before the second response is delivered so made the timeout longer and moved the two requests to be next to each other to make it most likely they arrive within the same Timeout period.
> Make Tx service test less flaky

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/transactions/aggregated_body.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/tests/diff_adj_manager.rs
This PR makes `db_read_access()` on the BlockchainDatabase private and exposes a new method that retrieves a read lock on the metadata as well. There were two instances in the mempool where the read lock on the DB was retrieved before the read lock on the metadata which is the reverse of most other operations. This would cause a deadlock. The new code makes it difficult for future developers to get the order incorrect.
I also added some logging to the validators for some extra tracing
> Restrict access to reader lock on DB to prevent deadlocks

- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet_ffi/src/lib.rs
This PR updates transaction cancellation to be done by changing the transaction status rather than dropping the data so that recovery is possible.
Tests updated
> Update transaction cancellation to use status rather than drop the data

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/src/mempool/async_mempool.rs
- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/src/mempool/proto/mempool_request.rs
- base_layer/core/src/mempool/proto/mempool_response.rs
- base_layer/core/src/mempool/proto/mod.rs
- base_layer/core/src/mempool/proto/service_request.proto
- base_layer/core/src/mempool/proto/service_response.proto
- base_layer/core/src/mempool/proto/state_response.proto
- base_layer/core/src/mempool/proto/state_response.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool_storage.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/core/src/mempool/service/local_service.rs
- base_layer/core/src/mempool/service/mod.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/service/response.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- Added two cli functions to enable the mempool stats and state of the local node to be queried.
- Added a state function and state response to the mempool that returns a list of transaction excess signatures for each pool in the mempool.
- Added proto conversions for StateResponse and Signature. Duplicate Signature conversions exist and the one copy should be removed at a later point.
These changes allow the mempool to be inspected to see which transactions are in the local pools.
> Added cli mempool queries for state and stats

- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/validation/block_validators.rs
- Updated the try_construct_fork function to check every new block that is added to the fork chain if it is connected to the main chain. This will fix a potential issue where a bad orphan block was added to the beginning of the fork chain that is already linked to the main chain causing the fork chain to fail validation.
- Some log messages were corrected and updated with better descriptions.
Fixes an issue where a bad orphan block can stop a valid reorg.
Existing tests remain functioning.
> Fixed issue where a bad orphan block can stop a valid reorg

- base_layer/core/src/base_node/states/block_sync.rs
The ban peer log will now supply n reason why the peer was banned
Current logs only list that a peer was banned and the the peer that was banned. We have no indication as to why it was banned. This changes the logs so we can see which peer, and why it was banned.
> The ban peer log will now supply n reason why the peer was banned

- applications/tari_base_node/src/parser.rs
[![asciicast](https://asciinema.org/a/PDVDZWvzTijSMtG3WvtV4gQrL.png)](https://asciinema.org/a/PDVDZWvzTijSMtG3WvtV4gQrL)
Used escape sequences in the output to display the searching string on a single line and output the missing blocks / headers after the loop has run. 
This will avoid lots of scrolling or missing blocks scrolling out of view before you can see them.
> Use a single line to display the search height

- applications/tari_base_node/src/parser.rs
To have the base node wallet perform this check more often we will just trigger it to start whenever the user interacts with the wallet aspect of the base node application.
In the near future we will do away with this and have the Output Manager manage this in a more proactive manner.
> Do a UTXO sync during get_balance and send_tari CLI commands

- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/src/validation/mocks.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/src/validation/traits.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/core/tests/diff_adj_manager.rs
- base_layer/core/tests/helpers/nodes.rs
- Cleaned up duplicate code from the Blockchain db, consensus manager, difficulty adjustment manager by removing unnecessary RwLockReadGuards and RwLockWriteGuards.
- Removed the ValidationWriteGuard trait and changed the block and transaction validators to use the simplified version.
These changes simplifies the blockchain db, consensus manager and difficulty adjustment manager calls where a RwLockReadGuards or RwLockWriteGuards could be used. It makes that only 2 validator traits are needed and not 3.
Covered by existing tests.
> RwLockReadGuards and RwLockWriteGuards refactor

- base_layer/core/src/blocks/block.rs
- base_layer/core/src/transactions/aggregated_body.rs
- base_layer/core/src/transactions/transaction.rs
- base_layer/core/src/validation/block_validators.rs
Validators will now check the block weight when doing validation and return a weight error if its too large
Blocks have a maximum size, this is represented in the consensus constants with the max weight field. By calculating the maximum weight of a block we can get a fairly accurate estimation of the maximum size of the block. This is to stop blocks getting too large.
> Validators will now check the weight of a block when doing validation

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
Instead of triggering a resync on Wallet operations from the tari_base_node CLI rather schedule a resync 4 minutes after a coinbase is imported into the wallet and do it in the background.
> Resync UTXOs a period after a coinbase is imported

- .github/workflows/clippy-check.yml
Some crates require rustfmt to compile
> Add rustfmt to github action dependencies

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/helpers/mock_backend.rs
- base_layer/core/src/mempool/mempool_storage.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_manager.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/mocks.rs
- base_layer/core/src/validation/traits.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/core/tests/diff_adj_manager.rs
- Removed the memory copy of metadata from the blockchain db and made the backend responsible for providing fast access to the chain metadata.
- A memory copy of the metadata was added to lmdb_db, and the backend was made responsible for restoring the memory copy and keeping it in sync with the persistent stored version.
- Removed all unused memory chain metadata functions and parameters from the blockchain db, mempool, consensus manager and difficulty adjustment manager.
- The validation train, block validators and transaction validators were updated to not need access to the chain metadata as it can be obtained from the blockchain backend.
- Modified the rewind_to_height function to update the metadata with the set of rewind db transactions ensuring it does not get updated when the db …
> Removed chain metadata from blockchain db.

- applications/tari_base_node/src/builder.rs
Updated add_peers_to_comms to prevent adding yourself as a peer
To be able to use a single configuration file for all base nodes
> Prevent adding yourself as a peer

- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/consensus/consensus_constants.rs
This PR is in preparation for Rincewind testnet launch.
Block interval is increased to 120s. Testing at one minute intervals
produced many orphaned blocks. Transaction propagation over ToR is not
quite fast enough at this stage; this can be revisited in future if/when
tx propagation times improve.
Max block weight icreased to 19500: In line with the new transaction
weights, this limit keeps blocks at around 1MB.
Minimum difficulty increased to 60e6; about 2 minutes on a single
MAcbook Pro.
Genesis block timestamp updated.
> Update testnet consensus constants

- base_layer/core/src/chain_storage/async_db.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/mempool/mempool_storage.rs
- base_layer/core/src/mempool/reorg_pool/reorg_pool.rs
- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/core/tests/async_db.rs
This PR adds in a check for new transactions if they are contain STxO's or not.  If they contain STxO's they are moved to the reorg pool and not orphan pool. 
Currently if a base node receives an old transaction it will flag as an orphan transaction and move it into the orphan pool because the inputs are not valid UTxO's. This will cause the base node to retransmit the transaction out to its peers. 
By checking the if the transaction contains STxO's, we can see if they contain spent outputs. We move the transaction to the reorg pool and we dont retransmit the transaction. This will reduce some network traffic as well as we dont re send transaction to peers. 
Unit tests for check stxo's
> Check if the  incoming tx contains STxO or not

- base_layer/core/src/mempool/mempool_storage.rs
- base_layer/core/src/mempool/unconfirmed_pool/unconfirmed_pool.rs
- base_layer/core/tests/mempool.rs
- These changes fixes an issue where some transactions in the unconfirmed pool might become timelocked after a reorg where the new chain height becomes lower. These transactions should be moved to the pending pool.
- When the mempool processes the set op removed and added blocks for a reorg, it will perform a check to determine if the new chain has a lower height. When a lower height is detected the unconfirmed pool will then check if there are any time locked transactions in the unconfirmed pool that should be moved to the orphan pool.
This will allow time locked transactions in the unconfirmed pool to be moved back to the pending pool.
> Fixed the time locked transactions in unconfirmed pool after reorg issue

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Update the `comms_config_create(...)` FFI function to add an argument to set the Discovery timeout.
@StriderDM @Jasonvdb This will require an update to the JNI and Swift wrappers
Towards @https://github.com/tari-project/tari/issues/1672
> Make Discovery timeout set by FFI client

- comms/dht/src/discovery/service.rs
Just added some Debug level logging of when Discovery message are sent and received to enable measuring Discovery times from the logs.
> Add some debug level logging of Discovery process

- comms/dht/examples/memorynet.rs
- comms/src/connection_manager/tests/manager.rs
- comms/src/peer_manager/manager.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/test_utils/node_identity.rs
When a node is determining if a requesting node is in it's region, it takes
the closest `n` peers that it is aware of and if the node ID is within
that threshold it considers it a neighbouring node. Because there are
nodes on the network that do not perform some network functions (such as
message propagation and store and forward i.e. wallets), there is a
chance that a majority of neighbours are these non-propagating nodes and
'take up space' where propagation nodes could 'fit'.
When calculating the threshold for neighbouring nodes it must take the
features of the nodes it knows about into account.
This PR changes the peer manager to consider `COMMUNICATION_NODE`s and
`COMMUNICATION_CLIENT`s independently to ensure a minimum number of
propagation nodes are considered neighbouring.
TODO: …
> Calculate region threshold depending on PeerFeatures

- applications/tari_base_node/src/parser.rs
Added a function to list available base node wallet UTXOs in the console.
There is a need to list available base node wallet UTXOs with their metadata.
Tested in Windows 10 and Ubuntu Linux
> Add function to list base node wallet UTXOs in the console

- base_layer/core/src/mining/miner.rs
Changes the logic of the miner to loop the futures::select so that the miner can listen for more than one event before restarting. 
The current miner code can cause that the miner can only listen once to an event. If the event does not change the miner state, the miner will continue to mine, but cant listen for future events until the miner finds a block. This causes lots of re-orgs to happen.
> Fix potential cause of frequent reorgs

- comms/dht/src/discovery/error.rs
- comms/dht/src/discovery/requester.rs
- comms/dht/src/discovery/service.rs
- comms/src/connection_manager/common.rs
- Added timestamp to in-flight discovery state to increase visibility of
discovery.
- More logging for different edge cases for discovery response
- Ensure that a peer is unmarked as offline when peer connects.
> Added some DHT discovery logging + peer offline bug

- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- comms/dht/src/outbound/encryption.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/message_params.rs
`EncryptForPeer` was originally intended to provide an additional layer
of encryption security by encrypting the message using a shared ECDH key
for the _direct_ over-the-wire receiver the message when using zMQ.
This mode has become redundant with the introduction of the noise
protocol, which provides over-the-wire security (see IX protocol
[security properties]).
[security properties]: https://noiseprotocol.org/noise.html#payload-security-properties
Removes redundant code and unnecessary computation. This is a non-breaking change because receivers do not require the message to have this additional encryption.
Existing tests updated where necessary.
> Removed redundant `EncryptForPeer` encryption option

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/parser.rs
Updated `list-utxos` command -displaying the Pedersen commitment rather than the spending key when listing UTXOs.
- When analyzing log files, Pedersen commitments can be traced, but not spending keys.
- The spending key should not be displayed in the console when UTXOs are listed, but kept private. 
Tested with runtime release versions of `tari_base_node` compiled with both Windows 10 and Ubuntu Linux.
> Updated `list-utxos` command

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/main.rs
- common/Cargo.toml
- common/examples/base_node_init.rs
- common/src/error.rs
- common/src/lib.rs
Allowing to reuse ConfigBootstrap CLI options via StructOpt would improve API ergonomics. StructOpt allows to define CLI arguments, description, default and validation in a regular Rust's struct, also allowing to embed that structure in client applications, so that CLI parametes will be reused. While providing StructOpt compatible configuration this change also preserves back compatibility with clap (StructOpt is using clap under the hood).
It also normalizes CLI arguments, e.g. no underscore, options correspond to struct parameters, e.g. `--base-path --log-config` accepted, as well as old aliases `--base_dir --log_config` accepted too.
Also adding `BoostrapConfig::init_dirs()` (similar to bootstrap_config_from_cli),`BoostrapConfig::initialize_logging()` and …
> Make ConfigBootstrap CLI options reusable via StructOpt

- comms/dht/src/actor.rs
- comms/dht/src/config.rs
- comms/dht/src/inbound/dedup.rs
- comms/dht/src/inbound/message.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/proto/store_forward.proto
- comms/dht/src/proto/tari.dht.store_forward.rs
- comms/dht/src/store_forward/database/mod.rs
- comms/dht/src/store_forward/error.rs
- comms/dht/src/store_forward/message.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/service.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/tests/dht.rs
- comms/src/peer_manager/node_id.rs
Storage and retreival of messages without an origin (PR #1686)
All private/anonymous messages are stored as low priority (short TTL)
messages.
- New response type `Anonymous` for store and forward query responses
- Added some more logging
- DHT store and forward integration test
- SAF messages can never be stored in store and forward
Since messages can be completely private (no known source or destination) SAF needs to store and relay these messages.
Added a store and forward integration test
> [Store and forward] Private message storage and retrieval

- base_layer/mmr/src/mmr_cache.rs
- base_layer/mmr/tests/mmr_cache.rs
Fixes an issue where if a large reorg occurs that rewinds the chain to the same height as the MmrCache base index then the base and current MMRs are not correctly updated resulting in incorrect Merkle and Merklish roots being generated.
Fixes an off by one error where the MmrCache is not correctly updated when a rewind occurs to the same index as the base index.
Added the multiple_rewinds tests that demonstrate this behaviour, this test fails when the fix is not applied.
> MmrCache rewind issue

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/utils.rs
- base_layer/core/src/mempool/mod.rs
- base_layer/core/tests/wallet.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/protocols/mod.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_chain_monitoring_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_receive_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
- comms/dht/src/dht.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/store_forward/forward.rs
- comms/src/builder/comms_node.rs
This PR refactors the 3 most complex long running processes in the Transaction service. The Sending protocol, Broadcast protocol and the Chain monitoring protocol.
These protocols all have multiple complex asynchronous stages and they were all handled in the main service code making them difficult to trace and maintain. The refactor introduces the idea of a “protocol” which is a struct and the logic to execute a long running task that requires complex asynchronous input and processing. The protocol is spawned as an async task and to receive input when it is created it registers channels with the Service task along which the required data will be sent when it arrives at the service.
The main service task still acts as a broker where all input streams (Event stream, comms stack message …
> Transaction Service Refactor to use a protocol and broker pattern

- applications/tari_base_node/src/utils.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_broadcast_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_chain_monitoring_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
This PR adds support for sending transactions via Store and Forward to the Wallet.
When a transaction is sent it is now attempted to send a Direct message which includes a Discovery attempt but also sends the message to the network to be propagated so that the recipient will be able to receive it via Store and Forward when they come back online. The wallet is updated to tolerate receiving repeated messages in case both these messages arrive.
As long as a transaction was sent out in either channel (direct or via store and forward) the transaction will be considered a Pending Outbound Transaction and will start waiting for a Transaction Reply. It is possible for the Direct send to work and the Store and Forward send not to work if the wallet only other peer is a Wallet but as long as you …
> Update wallet to support sending Tx via Store and Forward

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/parser.rs
Implemented basic `make-it-rain` command as 
`make-it-rain [Txs/s] [duration (s)] [start amount (uT)] [increment (uT)/Tx] ["start time (UTC)" / 'now' for immediate start] [public key or emoji id to send to] [message]`
TODO list:
- Read in the recipient address list and a custom message from file
- Implement Tx rate vs. as fast as possible, must be non-blocking
- Start at the specified time, must be non-blocking
This is for the purposes of stress testing the network.
Tested with 2x simultaneous Windows 10 nodes sending 370 Txs and 948 Txs respectively with overlapping time frames to ~14 online wallets (32 Txs from the 1st node and 68 Txs from the 2nd node to each wallet).
> `make-it-rain` command to enable stress testing the network

- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- comms/dht/src/actor.rs
- comms/dht/src/discovery/error.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/message_send_state.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/outbound/mod.rs
- comms/dht/src/outbound/serialize.rs
- comms/dht/src/store_forward/forward.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/src/test_utils/makers.rs
- comms/dht/src/test_utils/mod.rs
- comms/src/message/mod.rs
- comms/src/message/outbound.rs
- comms/src/protocol/messaging/error.rs
- comms/src/protocol/messaging/outbound.rs
- comms/src/protocol/messaging/protocol.rs
- comms/src/protocol/messaging/test.rs
Each message sent using outbound messaging now has a oneshot attached.
A success or failure result is guaranteed to be sent back on the oneshot
for every message sent.
Convenience functions were added to allow callers to easily know the
state of each message sent.
```rust
let send_states =
outbound_messaging_requester.propagate(...).await?.reolve_ok().await?;
let num_queued = send_states.len();
println!("{} message queued for sending", num_queued);
let (success, failed) = send_states.wait_percentage_success(0.51).await;
println!("Message sent to a majority of nodes ({} succeeded, {} failed)",succeeded.len(), failed.len())
// or (wait_* consumes send_states)
let (success, failed) = send_states.wait_all().await;
println!("Result of the propagation: {} succeeded, {} failed", succeeded.len(), …
```
> Added oneshot reply to outbound messaging

- base_layer/wallet_ffi/wallet.h
Function definition is
```
pub unsafe extern "C" fn wallet_create(
config: *mut TariCommsConfig,
log_path: *const c_char,
...
}
```
Header has to match definition.
> Added missing const to header

- base_layer/wallet_ffi/wallet.h
- common/src/lib.rs
With adding StructOpt support for BootstrapConfig back - support for clap ArgMatches appeared broken, while test `test_bootstrap_config_from_cli_and_load_configuration` was not showing a problem as it appeared worked fine with no arguments provided on env where there was default config in default dir, while hanging with prompt on envs without default setting.
This PR fixing the bug, so clap options are back supported again, also adding test that validates ArgMatches with possible combinations including aliases.
As reported by @sdbondi in nomatter:
> Anyone else finding the test_bootstrap_config_from_cli_and_load_configuration test is hanging locally? @dunnock I think the problem lies in ConfigBootstrap::from_matches because init is not  set to true even through the --init flag is present …
> Fix bug with hanging test bootstrap_config on some envs

- base_layer/wallet/src/transaction_service/protocols/transaction_chain_monitoring_protocol.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/transaction_service/service.rs
Not all stages of the transaction negotiation protocol were sending messages to the counter party both directly AND with Store and Forward correctly.
This PR adds the Store and forward messages for the Transaction Reply and Finalised transaction messages which were not sending the SAF message correctly. 
Transaction Service tests have been updated to take this into account and hopefully resolve the remaining flakiness.
Tests updated.
> Update Transaction protocols to send all Tx messages via Store & Forward correctly

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/states/block_sync.rs
- comms/dht/src/config.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/envelope.rs
- comms/dht/src/inbound/dedup.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/inbound/message.rs
- comms/dht/src/store_forward/database/mod.rs
- comms/dht/src/store_forward/error.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/tests/dht.rs
- comms/src/connection_manager/common.rs
- comms/src/peer_manager/manager.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_query.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/utils/datetime.rs
- Inbound join messages sent form SAF are discarded
- Inbound anonymous discovery messages sent from SAF are discarded
- Base node no longer requests SAF message on start up (BN wallet still
does)
- [BUG] `ForMe` messages only returns non-DHT messages
- (un)ban-peer command works on both the wallet and base node
- Sync peer ban set to 24 hours
- Only one discovery can be inflight at once
- Anonymous SAF response (sending back all anonymous messages) no longer happens
_NOTE: Wallet and base node peer databases will need to be deleted_
_RECOMMENDED: Delete your dht.db_
> Reject inbound SAF join messages, timelimit on peer bans, other fixes

- applications/tari_base_node/src/builder.rs
- comms/dht/src/actor.rs
- comms/dht/src/broadcast_strategy.rs
- comms/dht/src/config.rs
- comms/dht/src/dedup.rs
- comms/dht/src/dht.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/inbound/mod.rs
- comms/dht/src/lib.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/store_forward/database/mod.rs
- comms/dht/src/store_forward/message.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/src/store_forward/store.rs
- comms/dht/src/test_utils/makers.rs
- comms/dht/tests/dht.rs
- comms/src/peer_manager/peer.rs
- comms/src/protocol/messaging/protocol.rs
- [bug] BN wallet and BN shared same dht db
- [bug] accidently used `.gt` when comparing key strings
- [stopgap] return 50 store and forward messages instead of 100
- [spam] Don't do discovery if failing to connect to a peer
- [stopgap] return most recent messages rather than oldest that are stored (protocol needs to be extended to allow for something like paginated queries)
- [bug] response sends stored messages `>` requested timestamp, as `>=`  could result in duplicates being sent
- [test] integration test for propagation of messages and dedup
- [optimisation] Add outbound broadcast messages to dedup cache to
prevent mistaken rebroadcasting
_No database or network breaking changes_
> Dht and Store and forward fixes

- comms/dht/src/store_forward/saf_handler/task.rs
- comms/src/connection_manager/wire_mode.rs
- Fork network to prevent old nodes from spamming
- Don't send discovery back from S&F
> Network fork

- base_layer/core/src/transactions/transaction_protocol/mod.rs
The sequence diagram in the transactions docs describe the multi-receiver case. The single receiver case is simpler, and is inlcuded now for completeness.
> Add a single receiver tx sequence diagram

- applications/tari_base_node/src/builder.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- comms/dht/src/dht.rs
- comms/dht/src/discovery/service.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/error.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/store_forward/forward.rs
This PR updates the Tx Service to use the embedded oneshot reply channel to determine if a Direct message was sent or not rather than relying on the MessagingEvent stream.
It also fixes a bug in the Output Manager service where an Inbound transaction output was not fully encumbered so if the app restarted it would be cleared as a short term encuberance.
Finally some Clippy cleanup.
Existing tests cover this
> Update Tx Service to one-shot response for SendDirect(..) and fix Output manager encumbrance bug

- base_layer/wallet_ffi/src/lib.rs
- comms/dht/src/actor.rs
The DHT db was set to use an in-memory sqlite database on libwallet.
There is some DHT metadata that should be persisted. This change will
create a dht.db file in the datastore_path.
- Reused the datastore_path on `comms_config_create` ffi call
- Fixed flakey DHT test
Some dht metadata should be persisted on mobile wallets
> Use filesystem storage for dht.db on libwallet

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/validation/accum_difficulty_validators.rs
- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/tests/block_validation.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/helpers/nodes.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/node_state_machine.rs
- These changes will allow the accumulated difficulty to be checked using validators. The accumulated difficulty check was also updated that chain reorgs should only occur when the fork chain has a higher accumulated difficulty.
- When competing chain tip blocks are encountered with similar accumulated difficulty then the local chain will wait for the next block to determine which of the two chains are the dominant chain.
- A mock accumulated difficulty validator was also introduced that can be used for generating simpler test blockchains where the accumulated difficulty for each preceding block does not have to increase.
Introduced accumulated difficulty validators to allow different rules for testing and running running a base node.
Covered by existing tests.
> Perform reorgs only on stronger tip accumulated difficulties

- applications/tari_base_node/src/parser.rs
- base_layer/core/src/transactions/transaction_protocol/transaction_initializer.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- Coin split functionality was added to the output manager service where a set of available UTXOs are found and the finalized transaction is constructed and the outputs are encumbered and tracked.
- The finalised transaction can then be submitted to the transaction service that propagates it and checks its status. Functionality to submit a transaction, that spends to self, was added to the transaction service.
- The ability to encumber more than one output to receive was added to the output manager db and the memory_db and sqlite_db was updated.
- The select_outputs method was renamed to select_utxos and was modified to allow the required number of outputs to be specified so that the fee can be correctly calculated for cases where more than one output is required. It will also now …
> Coin-split base node cli command

- base_layer/wallet/src/util/emoji.rs
- base_layer/wallet/src/util/luhn.rs
Check if Emoji string is empty before trying to validate it.
Bug fix
> Empty Emoji String Bug Fix

- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
Store & Forward can result in the delivery of repeated messages. The Transaction Service can tolerate this but logged error messages in response. This PR just updates the Transaction Service logging to be friendlier to these types of errors and present that they are likely from repeated SAF message.
> Update Transaction Service error logs represent repeated SAF messages

- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_chain_monitoring_protocol.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
This PR fixes a bug where the Chain monitoring process in the Tx service was asleep for a long time and the pending Tx was mined and when they woke up they got the mempool response saying the Tx was no longer in the mempool BEFORE they get the Base Node response confirming its been mined. This used to result in the Pending Tx being cancelled. The Chain monitoring protocol was updated so that it will only cancel a pending tx in this way if it receives the mempool response AND the BN response and checks the BN response first.
The PR also stops completely deleting cancelled inbound UTXO’s and rather uses a status to mark them as deleted in case they need to be recovered.
Covered in existing tests
> Fix chain monitoring bug in Transaction Service

- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
- applications/tari_base_node/src/table.rs
- applications/tari_base_node/src/utils.rs
- base_layer/core/src/chain_storage/async_db.rs
- comms/dht/examples/memorynet.rs
- comms/dht/src/macros.rs
- comms/dht/src/outbound/mock.rs
- comms/dht/src/test_utils/dht_actor_mock.rs
- comms/dht/src/test_utils/dht_discovery_mock.rs
- comms/src/connection_manager/peer_connection.rs
- comms/src/peer_manager/connection_stats.rs
- comms/src/peer_manager/peer_features.rs
- Added basic ASCII table implementation that is easy to copy into a
spreadsheet
- `list-peers` and `list-connections` use table implementation
- `list-connections` shows peer data and duration of connection
```
NodeId           | Public Key                                                       | Address                                                                | Direction | Uptime  | Role
75cfb63f1e967a5d | 2e93c460df49d8cfbbf7a06dd9004c25a84f92584f7d0ac5e30bd8e0beee9a43 | /ip4/127.0.0.1/tcp/60187                                               | Inbound   | 13m 38s | Base node
9fc307fd4c4874fd | b81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709 | /ip4/127.0.0.1/tcp/60176                                               | Inbound   | 13m 39s | Base node
099fc6fc362f07b5 | …
```
> ASCII table output for list-peers and list-connections

- base_layer/core/src/validation/transaction_validators.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
Just push the log message that record when a double spend is attempted to debug level so that we can see when this happens on the Faucet node.
Also push the log message about starting and resuming the Send Transaction protocol to debug for easier debugging.
> Update logging level for double spend error and transaction send

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Added a basic FFI function that will log a string at debug level. This will be used to get some logging of info from the LibWallet clients in the logs.
> Add generic debug log function to FFI

- comms/dht/src/proto/tari.dht.envelope.rs
- comms/dht/src/store_forward/service.rs
- comms/dht/src/test_utils/store_and_forward_mock.rs
- Added SendStoreForwardRequestNeighbours to SAF service
Some delays experienced on iOS may be caused by the "on connect trigger" for SAF not triggering when the app is opened. External services can now send ad hoc SAF requests 
implementation already tested, although this call has not been tested.
> Allow external services to send SAF requests to neighbours

- base_layer/wallet/src/error.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
The wallet has been updated to send a request for outstanding SAF message whenever the LibWallet client requests a Base Node sync. This is done to try improve SAF delivery reliability when an app returns from the background.
> Update wallet to send a SAF request to neighbours on BN sync call

- base_layer/core/Cargo.toml
- base_layer/core/src/proof_of_work/monero_rx.rs
NB: Requires randomx-rs 0.2.0 to be available first.
Updated Version of randomx-rs
Updated monero_difficulty_calculation in monero_rx.rs
Update randomx-rs to latest version.
> RandomX - Version Update

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/service.rs
The default UTXO selection strategy is to use the smallest outputs
first. This works well most of the time, but for really large trans-
action amounts, we can run into the transaction input limits.
This PR adds a new strategy and a selection heuristic for selcring it.
`Largest` does what it says on the box. It's the inverse of `Smallest`.
If the total transaction amount > alpha * My largest UTXO, then we
select Largest (for now alpha = 1).
The coin_split strategy also uses Largest (since that makes the most
sense if you're trying to make more UTXOs)
> Add UTXO selection strategy for large txs

- comms/dht/src/discovery/error.rs
- comms/dht/src/discovery/service.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/requester.rs
- comms/src/peer_manager/peer.rs
- comms/src/test_utils/mocks/connection_manager.rs
- Adding a condition that will prevent peers from being marked as
offline while there are no active connections, in which case, the node
itself may have lost connection.
- To clarify the above: "Offline" means that a peer will not be chosen for the
propagation of messages. Attempting to send a message directly will still
be attempted. There is existing protection for marking more than 70%
of neighbouring peers as offline, so this change is an additional
protection from both sides considering each other offline.
- Bug fix where peers are displayed as offline in the `list-peers`
command, even though logically they are not considered offline.
Nodes could mistakenly be marked as offline by a node experiencing loss of connection. This remedies that by requiring at least one active peer …
> Don't mark peers as offline if there are no existing connections

- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/proof_of_work/median_timestamp.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/tests/median_timestamp.rs
- Decoupled the median timestamp calculation from the ConsensusManger by removing the get_median_timestamp and get_median_timestamp_at_height functions.
- Changed the get_median_timestamp function to calculate the median from a set of timestamps and not a set of headers.
- Changed the median calculation to use the correct median formula.
These changes decouple the median timestamp calculation from the blockchain backend and ConsensusManger. Also, the median calculation was changed to perform a true median and not an approximation. 
Updated the median timestamp tests and discarded the test_median_timestamp test that was testing similar mechanisms to the other median timestamp tests.
> Median timestamp refactor

- comms/dht/tests/dht.rs
The order that a message arrives is non-deterministic so the tests
should accommodate that by expecting each exactly once in any order.
> Fix flaky dht_store_forward test

- base_layer/p2p/src/services/liveness/state.rs
- comms/dht/examples/memorynet.rs
- comms/dht/src/actor.rs
- comms/dht/src/domain_message.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/outbound/requester.rs
- comms/dht/src/proto/dht.proto
- comms/dht/src/proto/mod.rs
- comms/dht/src/proto/tari.dht.rs
- comms/dht/src/store_forward/forward.rs
- comms/dht/src/store_forward/store.rs
When re-propagating messages from the domain layer, a nonce is placed in the
header causing the message hash to change for every propagation causing
unique domain messages to be generated when propagating.
For propagation messages this has been changed to always be `0`. Direct messages will still generate a unique nonce to prevent purposefully duplicate messages from being rejected.   
Added nonce to Join message. Join messages have a nonce per non-propagation send because they will often contain duplicate data.
Can result in propagated domain messages spamming the network
> MessageHeader::nonce set to constant (0) for propagation messages

- comms/src/connection_manager/wire_mode.rs
Changed wiremode byte to `0x03`
This will cause a network split
> Force a network split

- README.md
- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/main.rs
- common/Cargo.toml
- common/config/tari_config_sample.toml
- common/src/configuration/bootstrap.rs
- common/src/dir_utils.rs
- common/src/lib.rs
- common/src/logging.rs
- Main `README.md` updated to better guide first-time users to run the base node.
- `wallet_identity_file` and `wallet_tor_identity_file` parameters added to `tari_config_sample.toml`
- All aliases for command-line arguments are now consistently supported across platforms; `--create-id` & `--create_id`, `--base-path` & `--base_path`, `base-dir` & `base_dir`, `log-config` & `log_config`.
- `--base-path` can now be specified as a relative path, previously an absolute path was required.
- `--base-path` can now be created multiple levels deep, previously only one new sub-level could be accommodated.
- Deprecated command-line args from matches methods and associated tests removed
- Tests expanded and added to cover all use cases.
Bug fixes:
- Consistent command-line arguments for Windows and …
> runtime usage

- base_layer/core/src/base_node/chain_metadata_service/service.rs
- base_layer/core/src/transactions/transaction_protocol/sender.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/services/liveness/handle.rs
- base_layer/p2p/src/services/liveness/mock.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/services/liveness/state.rs
- base_layer/p2p/tests/services/liveness.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
Previously the transaction service would send a transaction once, directly and via store-and-forward, and then wait for a Reply from the Recipient. If the Transaction was lost it would never be resent and on the Sender’s side it would be a pending Tx until the client cancelled it 3 days later.
This PR updates the Transaction Send protocol in the Transaction service to use the Liveness Service to monitor the recipient for liveness with periodic pings. If the recipient replies with a Pong but has not sent the Transaction Reply message the Sender will resend the transaction to the Recipient in case the original send did not make it to them. Once the Send Transaction Protocol ends the Recipient will be removed from the Liveness service Nodes to monitor list.
Future PRs will apply this same …
> Update wallet to monitor Tx recipient for liveness and to resend Tx

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/consts.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/node_comms_interface.rs
- common/src/configuration/global.rs
- common/src/configuration/utils.rs
- Currently most nodes report their pruning horizon incorrectly using their chain metadata. To fix this without forcing nodes to add a pruning horizon setting to their config file, the default was changed to be an archival node.
- Made the BlockchainDatabaseConfig configurable using the base node application config file, allowing the orphan storage capacity and pruning horizon to be configured.
- Added the pruning horizon to the BlockchainDatabaseConfig and added functions to allow it to be stored using the blockchain backend.
These changes allow the pruning horizon to be configured and changes the default operation to archival mode.
Existing tests were updated to ensure that the mode operation is correctly configured.
> Configurable pruning horizon

- base_layer/core/src/chain_storage/postgres_db/migrations/2020-04-07-14-49_tx_outputs/up.sql
- base_layer/core/src/chain_storage/postgres_db/migrations/2020-04-28-15-51_outputs/up.sql
- base_layer/core/src/chain_storage/postgres_db/migrations/2020-04-28-15-51_spent/up.sql
Proposes some DB table changes
Currently the postgres tables have only one link per transactional output for created in a block and spent in a block. While this is fine for when an output only occurs in the main chain as an output can only be created once and spent once. But we have orphan blocks which means that a transactional output can be in more than one orphan block or in a orphan block and the main chain. This means that a transactional output can be in more in than one block if looked from the database's tables. This also means that the current table layout will not work for all cases.
> DB model update

- base_layer/core/src/transactions/helpers.rs
- base_layer/core/src/transactions/tari_amount.rs
I have added a formatter to split values of T or µT every 3 places from the end of the whole number. The decimal places of T has been limited to 2.
Refactored the `Display` implementation for `Tari` and `MicroTari` to use the new helper function `display_currency` 
Distinguishing between millions or tens of millions of µT / T was getting painful.
Updated the tests to include the new formatting as well as a few examples of the rounding.
> Added a currency style formatter for T and µT
