tari-project/tari

- Cargo.lock
- base_layer/core/Cargo.toml
- base_layer/core/src/block.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/pow.rs
- base_layer/core/src/transaction.rs
This PR
Add minimal block definitions 9Code compiles, but doesn't do anything yet) for cross referencing in RFC documents
> Block definition

- RFC/src/Glossary.md
- RFC/src/RFC-0150_Wallets.md
This PR
This document will propose the functionality and techniques required by the base layer Tari wallet module. The module exposes the core wallet functionality that user-facing wallet applications may be built on.
The content for this RFC is a lightly edited C&P from #17 by @neonknight64
> RFC-0150 -  Base layer wallet software

- infrastructure/crypto/src/common.rs
- infrastructure/crypto/src/curve25519/curve25519_keys.rs
- infrastructure/crypto/src/curve25519/curve25519_sig.rs
- infrastructure/crypto/src/keys.rs
- infrastructure/crypto/src/lib.rs
Several definitions on `PublicKey` and `SecretKey` are repeated. These are be factored out into a `ByteArray` trait with several default implementations.
The Curve25519 implementation has been updated
Fixes #68 
Features coming in soon (Commitments, Sigs etc) will also benefit from this
It's a refactor, so current tests should pass
> DRY up SecretKey and PublicKey

- RFC/src/RFC-0110_BaseNodes.md
- RFC/src/RFC-0130_Mining.md
This RFC adds mention of cut-though and pruning on the base layer
Pruning and cut-through is added as requirements. 
This PR is still a work in progress because it requires #22 
Cut-through and pruning is a key part of the scalability and confidentiality of MW.
> Pruning and cut through

- RFC/src/theme/css/chrome.css
Added a little padding on the top header so the logo is not touching the top of the browser and also moved the print icon so it stays centered.
> Header Styling Tweaks

- README.md
- RFC/README.md
Update RFC URL
RFCs are now hosted at user-friendly URL
> Update RFC URL

- .circleci/config.yml
Last step of [GH pages](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/) instructions. 
GH-pages deploy is broken
> Extra flags for CircleCI to allow GH pages deploy

- RFC/src/CNAME
Stops github pages from being broken after each push
> Add CNAME record

- Cargo.lock
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
Format code to make tests pass
Comment was over 120 char limit
> Fix circle tests

- README.md
- base_layer/p2p/src/lib.rs
- infrastructure/comms/Cargo.toml
- infrastructure/comms/src/connection/i2p/address.rs
- infrastructure/comms/src/connection/i2p/connection.rs
- infrastructure/comms/src/connection/i2p/mod.rs
- infrastructure/comms/src/connection/mod.rs
- infrastructure/comms/src/connection/net_address.rs
- infrastructure/comms/src/connection/onion/address.rs
- infrastructure/comms/src/connection/onion/connection.rs
- infrastructure/comms/src/connection/onion/mod.rs
- infrastructure/comms/src/connection/p2p/address.rs
- infrastructure/comms/src/connection/p2p/connection.rs
- infrastructure/comms/src/connection/p2p/mod.rs
- infrastructure/comms/src/peer_manager/ban_list.rs
- infrastructure/comms/src/peer_manager/liveness.rs
- infrastructure/comms/src/peer_manager/manager.rs
- infrastructure/comms/src/peer_manager/message.rs
- infrastructure/comms/src/peer_manager/mod.rs
- infrastructure/comms/src/peer_manager/peer.rs
- infrastructure/comms/src/peer_manager/routing_table.rs
- infrastructure/comms/src/peer_manager/storage.rs
- infrastructure/comms/src/pubsub/mod.rs
- infrastructure/comms/src/router.rs
- infrastructure/comms/src/rpc/deserialize.rs
- infrastructure/comms/src/rpc/mod.rs
- infrastructure/comms/src/rpc/serialize.rs
- infrastructure/comms/src/server/mod.rs
- infrastructure/comms/tests/mod.rs
- 2019 Copyright fixes
- added edition 2018
- build badge in README
> 2019 Copyright fixes, added edition 2018, build badge in README

- .circleci/config.yml
Try to prevent the `book/` subdir in `gh-pages`
> github pages fix

- .circleci/config.yml
> Resolve issue with RFC deploys

- .circleci/config.yml
> Fix invalid argument for mktemp

- .circleci/config.yml
> Fix no book subdir

- Cargo.lock
- RFC/src/Glossary.md
- RFC/src/RFC-0001_overview.md
- RFC/src/RFC-0301_NamespaceRegistration.md
- RFC/src/RFC-0311_AssetTemplates.md
This PR
A description of the templating system for the Tari digital asset network
> Asset templates

- RFC/src/RFC-0311_AssetTemplates.md
* Update `create_asset` instruction to include FQDN and nonce
*  Provide the `create_asset` RAID ID validation algorithm
* Fixes #178
> Raid validation #178

- Cargo.lock
- base_layer/blockchain/src/chain.rs
- base_layer/core/src/block.rs
- base_layer/core/src/transaction.rs
- base_layer/keymanager/src/file_backup.rs
- base_layer/keymanager/src/keymanager.rs
- base_layer/keymanager/src/mnemonic.rs
- infrastructure/comms/src/connection/net_address/ip.rs
- infrastructure/comms/src/connection/net_address/mod.rs
- infrastructure/comms/src/connection/net_address/onion.rs
- infrastructure/comms/src/connection/net_address/parser.rs
- infrastructure/crypto/src/challenge.rs
- infrastructure/crypto/src/musig.rs
- infrastructure/crypto/src/ristretto/musig.rs
- infrastructure/crypto/src/ristretto/pedersen.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- infrastructure/crypto/src/signatures.rs
- infrastructure/merklemountainrange/src/merklemountainrange.rs
- infrastructure/storage/src/lmdb.rs
- infrastructure/tari_util/src/hex.rs
- rustfmt.toml
This is purely a formatting PR. No changes to the codebase were made
`max` is perhaps a bit too aggressive in pushing calls onto one line.
This is making some fluent and functional calls look less readable
than authors are writing them.
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_small_heuristics
> Try turning small heuristics off

- base_layer/core/src/message.rs
Cargo-fmt rules changed after another PR was merged, breaking development
Re-run `cargo-fmt` on development source code
> Fix formatting

- RFC/src/RFC-1000_TariUseCases.md
- RFC/src/SUMMARY.md
There will be many types of digital assets that can be issued on Tari. This early, draft “framework” is intended to help issuers design new types of digital assets that may or may not exist in their ecosystems today.
A framework greatly helps creating new use cases for digital assets.
* [*] Documentation
> Tari Use Cases RFC

- RFC/src/Glossary.md
- RFC/src/RFC-0110_BaseNodes.md
- RFC/src/RFC-0230_HTLC.md
This is the RFC for HTLC
Describes how HTLC can be implemented in MimbleWimble
Closes #84  
Describes how HTLC can be implemented in MimbleWimble
> Add RFC for HTLC

- base_layer/core/Cargo.toml
- infrastructure/crypto/Cargo.toml
> Bump dalek curve25519 version to 1.1.3

- infrastructure/derive/src/extend_bytes.rs
- infrastructure/derive/src/hashable.rs
- infrastructure/merklemountainrange/src/lib.rs
- infrastructure/merklemountainrange/tests/support/testobject.rs
> Remove compiler warnings

- infrastructure/tari_util/src/fixed_set.rs
Summing zero-sized sets now returns the default value for the set type,
e.g. int_set.sum() == 0
> Implement logical behavior for zero-sized sets

- base_layer/core/src/fee.rs
- base_layer/core/src/transaction.rs
Provides a universal fee calculation utility for calculating fees based on transaction size. Will be used in the TX builder
> Add a small fee calculation utility

- Makefile
- meta/assets/rustdoc-include-js-header.html
`make doc` is more inclusive now, and it's easy to add crates in future
> Better doc script

- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/mod.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/core/src/transaction_protocol/single_receiver.rs
- base_layer/core/src/types.rs
When there is a single recipient in a transaction, the protocol can proceed via one round. This commit provides the logic for the single recipient receiving data from the sender, constructing an    output, creating a signature, and returning all the information    inside a suitable data structure
<s>Blocked by #257 </s>
Part of #42
> Single recipient transaction protocol

- Cargo.lock
- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/lib.rs
- base_layer/p2p/src/tari_message.rs
Implementing `TariMessageType` to be failthful to RFC-0172 proved to be quite tricky, but
I believe this is an implementation that achieves those goals while still being very
ergonomic and space efficient / performant on the wire.
The tests illustrate how the `TariMessageType` struct would be used.
Partially completes #184
> TariMessageType

- base_layer/core/src/transaction.rs
There was a misplaced comment in a test
N/A
> Fix comment in rangeproof test test

- Cargo.lock
- RFC/src/RFC-0172_PeerToPeerMessagingProtocol.md
- infrastructure/comms/Cargo.toml
- infrastructure/comms/src/connection/message.rs
- infrastructure/comms/src/peer_manager/node_id.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
Serialize and deserialze for the raw message into a message envelope 
Closes #184 
The dispatcher needs to work with a deserialized message
> Add new serialisable header

- infrastructure/comms/src/connection/connection.rs
- infrastructure/comms/src/connection/mod.rs
- infrastructure/comms/src/connection/monitor.rs
- infrastructure/comms/tests/connection/connection.rs
- infrastructure/comms/tests/connection/mod.rs
- infrastructure/comms/tests/connection/monitor.rs
- infrastructure/comms/tests/connection/peer_connection.rs
Abstraction of zMQ socket monitoring. The monitor connects to the given inproc and reads off socket events for a connection being monitored. The inproc is provided to the connection to be monitored through the `set_monitor_address` method in the `Connection` or `PeerConnectionContextBuilder` builders. That same inproc must be provided to the monitor. 
This will mainly be used internally by PeerConnection to allow it to establish if a peer can be connected to or if the peer has disconnected during a session.  The integration with the ConnectionMonitor and PeerConnection will be in a subsequent PR.
Partial #280 
Unit and functional testing
> ConnectionMonitor

- Cargo.lock
- Cargo.toml
- base_layer/core/Cargo.toml
- base_layer/core/src/transaction.rs
- base_layer/core/src/transaction_protocol/mod.rs
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/transaction_manager.rs
This PR implements a TransactionManager that allows for the management of multiple inbound and outbound transaction protocols which are uniquely identified by a tx_id. The TransactionManager generates and accepts the various protocol messages and applies them to the appropriate protocol instances based on the tx_id. The TransactionManager allows for the sending of transactions to single receivers, when the appropriate recipient response is handled the transaction is completed and moved to the completed_transaction buffer. The TransactionManager will accept inbound transactions and generate a reply. Received transactions will remain in the pending_inbound_transactions buffer.
Closes #248 
Unit tests are provided
> Implement TransactionManager

- infrastructure/storage/src/lmdb.rs
> ldmb test was failing on OsX

- infrastructure/crypto/src/ristretto/constants.rs
- infrastructure/crypto/src/ristretto/dalek_range_proof.rs
- infrastructure/crypto/src/ristretto/musig.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
- infrastructure/crypto/src/signatures.rs
- infrastructure/storage/src/keyvalue_store.rs
- infrastructure/storage/src/lmdb.rs
- infrastructure/tari_util/src/bit.rs
- infrastructure/tari_util/src/chacha20.rs
- infrastructure/tari_util/src/cipher.rs
- infrastructure/tari_util/src/fixed_set.rs
- infrastructure/tari_util/src/hex.rs
- infrastructure/tari_util/src/message_format.rs
Applied some recommendations from clippy.
Clippy errors relating to non-elementary loops over ranges were ignored
One lint relating to a `&Vec<T>` param was ignored since a large refactor
would be required to implement that.
Importantly, the `Copy` trait was removed from `PublicKey`
>  Fix some clippy errors for tari_crypto

- RFC/src/Glossary.md
- RFC/src/RFC-0170_NetworkCommunicationProtocol.md
- RFC/src/RFC-0302_ValidatorNodes.md
- RFC/src/RFC-0322_VNRegistration.md
A rough initial draft of the Validator registration process.
> Initial draft of RFC-0322

- .circleci/config.yml
> Add 'cargo test --release' to CircleCI

- Makefile
- base_layer/wallet/src/transaction_manager.rs
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/node_identity.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
Provided some more in depth docs to the PeerManager module
Closes https://github.com/tari-project/tari/issues/344
Just docs
> Add documentation to PeerManager

- comms/Cargo.toml
- comms/src/connection/peer_connection/worker.rs
- comms/src/connection_manager/connections.rs
- comms/src/connection_manager/manager.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/tests/connection_manager/live_peer_connections.rs
> Improve connection logging

- comms/src/peer_manager/node_id.rs
Docstrings
Closes Document #345
> Added some docs for NodeId

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/handlers.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/handlers.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
- comms/src/message/envelope.rs
- comms/src/message/error.rs
- comms/src/message/message.rs
- comms/src/message/mod.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/utils.rs
- Added message signature verification and decoding
- Send messages to correct handlers based on the message destination, decoding and signature verification
- Modified the MessageEnvelope constructor to generate the signatures and encode messages based on if the flag was set
- Modified the tests to make use of the MessageEnvelope constructor
- Important change to distribute messages correctly to handlers
- Message signature generation and verification is located in MessageEnvelope.
- Message encoding and decoding is located in MessageEnvelope
Tests were modified to make use of new functionality
> Signature verification and message decryption of inbound messages

- comms/src/builder/builder.rs
- comms/src/connection/zmq/endpoint.rs
- comms/src/connection/zmq/inproc_address.rs
- comms/src/domain_connector.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/lib.rs
- comms/src/message/domain_message_context.rs
The domain dispatcher will be replaced by ZMQ sockets which can be read by services/protocol managers. The facilitate this, a service can hold a connector which take a generic message type parameter and allow messages received on the connector to return the given concrete message type
Closes #378 
Extensive unit tests
> Added Domain Connector

- base_layer/blockchain/Cargo.toml
- base_layer/blockchain/src/block_chain_state.rs
- base_layer/blockchain/src/chain.rs
- base_layer/blockchain/src/error.rs
- base_layer/blockchain/src/genesis_block.rs
- base_layer/core/src/block.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/pow.rs
Add chain code scaffolding
Add genesis block scaffolding
Add most of the code to deal with the blocks and how to do reorgs
This code will be used to run the block chain
> Add chain code scaffolding

- common/config/tari_config_sample.toml
Here's what I'm thinking in terms of the Tari configuration file. It's currently incomplete, but it sets the tone and philosophy for configuration.
Here's the basis for the proposed layout:
Format: TOML
* Defaults should cover 90% of all use cases
* Every option is explained in detail, with examples for alternatives and describe when you might want to move off the default.
* One config file - per machine - to rule them all (wallets, base nodes, VNs)
> WIP Example configuration file

- comms/src/builder/builder.rs
- comms/src/connection/connection.rs
- comms/src/inbound_message_service/error.rs
- comms/src/inbound_message_service/inbound_message_broker.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/outbound_message_pool.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- comms/tests/outbound_message_service/outbound_message_pool.rs
- Changed InboundMessageService and MsgProcessingWorker to use new Connections
- Fixed flaky tests
- Add an extra Direct Broadcast strategy that uses the destination Public Key
Flaky tests!
Existing tests were fixed
> Fix InboundMessageService and MsgProcessingWorker Tests

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/initializers.rs
- base_layer/p2p/src/lib.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/error.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/src/services/mod.rs
- base_layer/p2p/src/services/registry.rs
- base_layer/p2p/src/services/service.rs
- base_layer/p2p/src/tari_message.rs
- comms/src/builder/builder.rs
- comms/src/builder/mod.rs
- comms/src/builder/routes.rs
- comms/src/control_service/handlers.rs
- comms/src/domain_connector.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/msg_processing_worker.rs
- comms/src/lib.rs
- comms/src/message/domain_message_context.rs
- comms/src/message/message_context.rs
- comms/src/message/message_data.rs
- comms/src/message/mod.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/node_identity.rs
- comms/tests/connection/peer_connection.rs
Added a service registry which wires up services to the comms layer. Each service is started in a thread from a service threadpool. See `p2p/initializers` to see how this is hooked up. I suspect this code will need to be moved but I wasn't sure where to put it.
ref #342 
Basic tests, Services tested with a basic test service - more integration tests need to be written 
* [~] I have added tests to cover my changes.
> Added Services wired up to comms

- base_layer/core/src/block.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/types.rs
This PR adds in a block builder class to allow users to construct a block using the builder pattern
This will make it easier to construct test chain's
> Block builder

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/lib.rs
- base_layer/p2p/src/macros.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/p2p/src/services/registry.rs
- base_layer/p2p/src/tari_message.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/types.rs
- base_layer/wallet/src/wallet.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/peer_manager/node_identity.rs
- comms/tests/connection/peer_connection.rs
Started a basic implementation of the Wallet API and in the process refactored some of the Domain services. This PR is not complete but @sdbondi needs these pieces to finish some tests he is writing.
Interrim PR
Related to https://github.com/tari-project/tari/issues/190
Some tests provided
> Started implementing Wallet API with refactor of the Domain Services

- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
Small changes which simplify PeerStorage setup.
Also set IMS to 4 worker threads which may ~fix~ minimize the fair dealer flakiness (ref #383)
Saves a few lines in tests
> Small refactor of peer storage 

- comms/src/outbound_message_service/message_pool_worker.rs
Continually reestablishing the requeue address connection can cause a
socket error ("Too many open files"). This fix establishes the
connection once before the loop begins and reuses it.
> Establish requeue address connection once in OMP

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/tests/ping_pong.rs
Changed the api methods to unwrap the response result and return the
actual value, removing the need for client code to handle this.
end_to_end test updated and passes
> Simplified the PingPongService api

- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/README.md
- base_layer/p2p/examples/gen_node_identity.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/examples/sample_identities/node-identity1.json
- base_layer/p2p/examples/sample_identities/node-identity2.json
- base_layer/p2p/src/initialization.rs
- base_layer/wallet/src/wallet.rs
- comms/src/connection_manager/establisher.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/handlers.rs
- comms/src/control_service/worker.rs
- comms/src/message/p2p/mod.rs
A relatively small pingpong example using the tari_p2p and tari_comms libraries.
Testing on comms from two different machines (mac and linux) seemed to
show that there is some issue with peer connection establishment which still
needs to be worked out. I've PR'd this example for everyone to play with
in the meantime.
N/A (examples are compiled during tests)
> PingPong example for tari_p2p

- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/example-log-config.yml
- base_layer/p2p/examples/pingpong.rs
Logs will be written in `base_layer/p2p/examples/log`
Gives us insight into the Comms layer performance
> Add file-based logging to ping-pong example

- comms/src/connection/connection.rs
- comms/src/outbound_message_service/outbound_message_service.rs
The OMS outbound (OMS to OMP) connection will only connect once per send, not once
per destination peer. This could connect once for the lifetime of the
OMS, however we need the OMS to be Sync + Send, so currently that is
out. Similar to #416 
Allow a name to be set for a connection
Added optional `set_name` on Connection to help identify
connections when they are dropped.
>  Only connect once per send in OMS

- comms/src/builder/builder.rs
- comms/src/builder/mod.rs
- comms/src/connection/mod.rs
- comms/src/connection/zmq/context.rs
- comms/src/connection/zmq/inproc_address.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/mod.rs
- comms/src/connection_manager/protocol.rs
- comms/src/control_service/mod.rs
- comms/src/control_service/service.rs
- comms/src/dispatcher/dispatcher.rs
- comms/src/dispatcher/mod.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/lib.rs
- comms/src/message/mod.rs
- comms/src/outbound_message_service/broadcast_strategy.rs
- comms/src/outbound_message_service/mod.rs
Added mod level docs for each of the submodules of `tari_comms`. Docs
can always be improved though, so any contributions welcome!
Closes #343 
Closes #347
> Added mod level docs for `tari_comms`

- comms/src/outbound_message_service/outbound_message_pool.rs
- infrastructure/storage/src/lmdb_store/store.rs
- infrastructure/storage/tests/lmdb.rs
- Add key and pair iterator to LMDBDatabase
- Added key_iterator and pair_iterator test
Required by PeerManager
New test were introduced
> Key and Pair iterator to LMDBDatabase

- comms/src/control_service/mod.rs
Removed the last trace of the old Storage system in comms, the ticket was primarily closed by #420
No tests needed
> Comms crate LMDB store refactor

- base_layer/wallet/src/text_message_service.rs
- base_layer/wallet/tests/text_message_service/mod.rs
Implemented CRUD functionality for Text Message contacts including the Service API interface.
Closes https://github.com/tari-project/tari/issues/456
Related to https://github.com/tari-project/tari/issues/381
Unit test provided. Service api interface will be tested via a subsequent PR that uses it.
> TextMessageService Contacts CRUD

- Cargo.toml
- applications/grpc_wallet/Cargo.toml
- applications/grpc_wallet/build.rs
- applications/grpc_wallet/proto/wallet_rpc.proto
- applications/grpc_wallet/src/grpc_interface.rs
- applications/grpc_wallet/src/lib.rs
- applications/grpc_wallet/src/wallet_server.rs
- applications/grpc_wallet/tests/mod.rs
- applications/grpc_wallet/tests/wallet_grpc_server/mod.rs
- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- comms/src/connection/net_address/mod.rs
- comms/src/peer_manager/error.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
This PR provides a gRPC server interface to interact with the the TextMessageService API. 
Tests are provided but the binary implementation will be provided in a subsequent PR. 
A big portion of the PR is just the extremely verbose gRPC client testing code
Closes https://github.com/tari-project/tari/issues/381
Integration tests are provided
> gRPC Server interface for TextMessageService

- base_layer/wallet/src/text_message_service.rs
A quick change to the TMS to enable syncing of unsent messages.
No tests just a small change
> Ping a new contact when added to TMS to trigger a flush of outstanding messages

- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/services/error.rs
- base_layer/p2p/src/services/executor.rs
- comms/src/connection/connection.rs
- comms/src/connection/dealer_proxy.rs
- comms/src/connection/monitor.rs
- comms/src/connection/peer_connection/worker.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/establisher.rs
- comms/src/connection_manager/manager.rs
- comms/src/control_service/handlers.rs
- comms/tests/connection/connection.rs
While debugging a comms issue I added some extra logging and added these
small improvements.
Ref #445 
Ref #440 
Ref #441
> Extra logging and possible reliability improvements [COMMS]

- comms/src/peer_manager/node_id.rs
This test was written as part of a debugging sanity check. Might as well PR it as it'll slightly increase test coverage
> Test NodeId PartialEq

- Cargo.toml
- applications/console_text_messenger/Cargo.toml
- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/sample_config/wallet_config_node1.toml
- applications/grpc_wallet/sample_config/wallet_config_node2.toml
- applications/grpc_wallet/sample_config/wallet_config_node3.toml
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/services/executor.rs
- base_layer/wallet/src/text_message_service.rs
- base_layer/wallet/src/wallet.rs
Implemented this console application that just runs the comms stack and wallet library to aid in debugging.
Aid in testing the comms stack and TMS
A console binary so no tests.
> Implemented a barebones console text message application

- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- Fixed issue where the search HashMap was not properly updated for the added NetAddress
- Added test that confirms update of search HashMap
Problem encounter during testing
New test was added
> Inconsistent NetAddress searching

- infrastructure/tari_util/src/ciphers/chacha20.rs
- infrastructure/tari_util/src/ciphers/cipher.rs
As per clippy recommendations:
* Replace `&Vec<>` with `&[T]`
* Replace `len() == 0` with `is_empty()`
This is a small PR to solve some small clippy fixes
> Replace `&Vec<>` with `&[T]`

- RFC/src/RFC_template.md
> RFC Template - technical editing changes.

- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/services/executor.rs
> Fixed build warnings

- .circleci/config.yml
..to use version nightly-2019-07-15
> Update CircleCI Rust container

- base_layer/core/src/block_chain_state.rs
- base_layer/core/src/blockheader.rs
- base_layer/core/src/chain.rs
- base_layer/core/src/genesis_block.rs
- base_layer/core/tests/support/simple_block_chain.rs
- infrastructure/merklemountainrange/src/merklemountainrange.rs
Updated documentation for the MMR and chain state
Some design decision was not documented as why they where taken and how they worked. This PR adds some context as to why they are required and how they are solved.
> Updated documentation for chain and MMR

- common/Cargo.toml
- comms/src/control_service/handlers.rs
- comms/tests/support/factories/mod.rs
- comms/tests/support/helpers/connection_message_counter.rs
- comms/tests/support/makers/node_id.rs
- infrastructure/merklemountainrange/tests/support/hashvalues.rs
Removed `#[allow(dead_code)]` flags in comms and infrastructure.
Additionally added a version to log4rs dependency in common to remove a warning.
Resolves issue #348
> Removed  `#[allow(dead_code)]` flags for issue #348

- RFC/src/RFC-0130_Mining.md
<General technical editing.>
<Checking grammar, spelling, consistency, links.>
> RFC-130 Technical Editing

- RFC/src/RFC-0140_Syncing_and_seeding.md
General technical editing review.
<Checking for consistency, grammar, spelling, abbreviations, links, etc.>
> RFC-140 Technical Editing

- .gitignore
- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/src/grpc_interface.rs
- applications/grpc_wallet/src/main.rs
- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- base_layer/wallet/migrations/2019-06-26-130555_initial/up.sql
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/schema.rs
- base_layer/wallet/src/text_message_service/error.rs
- base_layer/wallet/src/text_message_service/mod.rs
- base_layer/wallet/src/text_message_service/model.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
This PR updates the TMS to use the Sqlite backend to store its data.
Closes https://github.com/tari-project/tari/issues/429
Updated tests and provided new tests
> Plumb the Sqlite backend into the Text Message Service

- RFC/src/RFC-0171_MessageSerialisation.md
> RFC-0171 - Technical Editing

- RFC/src/RFC-0151_TransactionProtocol.md
> RFC-0151 - Technical edits

- RFC/src/RFC-0150_Wallets.md
> RFC-0150 - Technical edits

- RFC/src/RFC-0172_PeerToPeerMessagingProtocol.md
> RFC-0172 - Technical Editing

- RFC/src/RFC-0230_HTLC.md
> RFC-0230 - Technical Editing

- RFC/src/RFC-0322_VNRegistration.md
> RFC-0322 Technical Editing

- RFC/src/RFC-0300_DAN.md
> RFC-0300 - Technical Editing

- Contributing.md
- doc/build.md
- infrastructure/merklemountainrange/Cargo.toml
- infrastructure/merklemountainrange/benches/bench.rs
Creates a few benchmarks for the Merkle Mountain Range structure. I'm not sure which methods on the MMR are used in the rest of the project, so I tried to guess the ones that are important. I think we can probably remove the `pub` on most of the methods to make the interface a bit clearer. I added multiple test case sizes to see what kind of order of complexity each method ran in, but most of them ran in _O(n)_ time
I also added a file to document how to build the solution. I put it in the `docs` folder because I've seen it stored there on a few other blockchain projects.
Connected to #166
The benchmarks were run locally. It doesn't look like any of the other benchmarks are currently being run on the CI box.
> Create benchmarks for Merkle Mountain Range

- base_layer/p2p/Cargo.toml
- base_layer/p2p/src/saf_service/error.rs
- base_layer/p2p/src/saf_service/mod.rs
- base_layer/p2p/src/saf_service/saf_messages.rs
- base_layer/p2p/src/saf_service/saf_service.rs
- base_layer/p2p/src/tari_message.rs
- Skeleton of Store-and-forward Service
- Added RetrieveMsgsMessage and StoredMsgsMessage
Storage of messages for offline peers
Test will be added in next PRs.
> Store-and-forward service skeleton

- base_layer/core/src/tari_amount.rs
- base_layer/core/src/transaction.rs
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/output_manager_service.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/support/data.rs
- base_layer/wallet/tests/text_message_service/mod.rs
- infrastructure/crypto/src/ristretto/ristretto_keys.rs
Implement the Service API for the Output Manager Service.
Required by #191 and #291 
Tests provided
> Implement the Service API for the Output Manager Service

- base_layer/p2p/src/tari_message.rs
> Removed unused Accept message

- base_layer/core/src/blockchain/block_chain_state.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/consensus.rs
- base_layer/core/src/emission.rs
- base_layer/core/src/lib.rs
- base_layer/core/src/transaction.rs
- base_layer/core/src/types.rs
- base_layer/core/tests/support/simple_block_chain.rs
- base_layer/core/tests/tests/block_validation.rs
This PR adds a Consensus struct to the block chain. This controls what the consensus rules will be the values are called for reading
See issue #641 
This does not break any current unit test. 
a Unit test has been added to confirm that the consensus struct changes rules
> Add Consensus Struct

- infrastructure/storage/src/keyvalue_store.rs
- infrastructure/storage/src/lib.rs
- infrastructure/storage/src/lmdb.rs
Mark old key-value store strait and implementations as deprecated.
Reduced confusion as to which KV store traits and implementations should be used
> Mark old key-value store strait and implementations as deprecated

- Cargo.toml
- base_layer/mmr/Cargo.toml
- base_layer/mmr/README.md
- base_layer/mmr/benches/bench.rs
- base_layer/mmr/src/backend.rs
- base_layer/mmr/src/common.rs
- base_layer/mmr/src/error.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/merkle_proof.rs
- base_layer/mmr/tests/merkle_mountain_range.rs
- base_layer/mmr/tests/merkle_proof.rs
- base_layer/mmr/tests/support/mod.rs
This is part 1 of a MMR refactor that aims to improve readibility,
decouple functionality, improve performance and ease testing and
benchmarking.
This PR achieves the following:
* MerkleMountainRange is a struct with a *single purpose*: An immutable, append-only merklish datastructure.
* Backend storage for MerkleMountainRange is abstracted away to a trait (simplifies testing)
* Change bagging procedure to a simple approach suggested in [zmitton/merkle-mountain-range]
* Improve performance of pushes by a factor of ~2
* [xx] I have added tests to cover my changes.
> Refactor MMR code into base_layer crate

- base_layer/mmr/Cargo.toml
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_proof.rs
- base_layer/mmr/src/serde_support.rs
- base_layer/mmr/tests/merkle_proof.rs
Both human-friendly (JSON) and binary formats are auto-
matically de- serilaised.
> Add serialisation support for MerkleProof

- base_layer/p2p/src/ping_pong.rs
- base_layer/p2p/src/sync_services/executor.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service.rs
- comms/src/builder/builder.rs
- comms/src/consts.rs
- comms/src/domain_subscriber.rs
- comms/src/inbound_message_service/comms_msg_handlers.rs
- comms/src/inbound_message_service/inbound_message_publisher.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/inbound_message_service/mod.rs
- comms/src/pub_sub_channel.rs
Split out the subscriber from the Inbound message publisher so that the
comms builder can provide it to the domain services.
Ref: #621
Ref: #676
N/A
> Small refactor of IMS publisher

- base_layer/p2p/tests/services/liveness.rs
- base_layer/p2p/tests/services/mod.rs
- base_layer/p2p/tests/support/comms_outbound.rs
Tested sending a ping and receiving a pong, checking the ping/pong count
Ref #676 
Ref #621 
Depends on #686 
This PR contains new tests
> Integration tests for liveness service

- base_layer/p2p/examples/pingpong_async.rs
Made an async example for the PingPong cursive app based off of the sync example
Ref #621 
Ref #686 
Depends on #686 
N/A
> Added async cursive PingPong example app

- base_layer/p2p/examples/pingpong_async.rs
Fixed compiler error for pingpong_async example
> Fix pingpong_async compile error

- base_layer/mmr/src/change_tracker.rs
- base_layer/mmr/src/lib.rs
- base_layer/mmr/src/merkle_mountain_range.rs
- base_layer/mmr/src/mutable_mmr.rs
- base_layer/mmr/tests/with_blake512_hash.rs
* Bring in the tests from the old MMR crate for adiditonal coverage.
* A few typos
* Make `MutableMMr::push` return a more intuitive result
> Include old MMR tests

- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/metadata.rs
- base_layer/core/src/chain_storage/transaction.rs
> Additional documentation for `BlockchainDatabase` module

- RELEASE_CHECKLIST.md
- applications/console_text_messenger/Cargo.toml
- applications/grpc_wallet/Cargo.toml
- base_layer/core/Cargo.toml
- base_layer/keymanager/Cargo.toml
- base_layer/mining/Cargo.toml
- base_layer/mmr/Cargo.toml
- base_layer/p2p/Cargo.toml
- base_layer/service_framework/Cargo.toml
- base_layer/wallet/Cargo.toml
- common/Cargo.toml
- comms/Cargo.toml
- infrastructure/crypto/Cargo.toml
- infrastructure/derive/Cargo.toml
- infrastructure/storage/Cargo.toml
- infrastructure/tari_util/Cargo.toml
- scripts/publish_crates.sh
This PR brings in changes and updates that were made to enable
the 0.0.5 point release.
> Update crate metadata and release process

- Cargo.toml
- comms/Cargo.toml
- comms/src/inbound_message_service/inbound_message_publisher.rs
- comms/src/pub_sub_channel.rs
- infrastructure/broadcast_channel/.gitignore
- infrastructure/broadcast_channel/Cargo.toml
- infrastructure/broadcast_channel/README.md
- infrastructure/broadcast_channel/examples/async-simple.rs
- infrastructure/broadcast_channel/examples/raw-simple.rs
- infrastructure/broadcast_channel/src/atomic_counter.rs
- infrastructure/broadcast_channel/src/bus.rs
- infrastructure/broadcast_channel/src/channel.rs
- infrastructure/broadcast_channel/src/lib.rs
This PR incorporates https://github.com/tari-project/bus-queue into this repo.
Credit for the original implementation goes to @filipdulic.
This following PR details changes from the original (as of the date of
this commit):
https://github.com/filipdulic/bus-queue/pull/24
Provides a mechanism for implementing topic based pub-sub
Ref #621
> Added a single-producer, multi-consumer broadcast channel

- base_layer/core/Cargo.toml
- base_layer/core/src/transaction_protocol/recipient.rs
- base_layer/core/src/transaction_protocol/sender.rs
- base_layer/p2p/src/ping_pong.rs
- base_layer/wallet/src/text_message_service/model.rs
- base_layer/wallet/src/text_message_service/service.rs
- base_layer/wallet/src/transaction_service.rs
- comms/src/message/message.rs
- comms/src/outbound_message_service/outbound_message_service.rs
Closes #718
tari_core doesn't need to have a dependency on tari_p2p or comms
> Remove tari_p2p and comms dep from tari core

- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- comms/src/domain_subscriber.rs
- comms/src/inbound_message_service/inbound_message_service.rs
- comms/src/inbound_message_service/inbound_message_worker.rs
- comms/src/lib.rs
- comms/src/outbound_message_service/outbound_message_service.rs
- comms/src/pub_sub_channel.rs
Replaced a 'global' macro import with explicit imports. Thinned out some
other compiler warnings.
> Removed some warnings related to `macro_use`

- Cargo.toml
- ffi/Cargo.toml
- ffi/src/lib.rs
Added FFI bindings.
Bindings cover Wallet, Peers, Messages.
Equivalent functionality present as in the console text messenger.
Interoperability is a beneficial aspect for a project.
Necessary for integration with Qt and aspects of mobile development.
Linked to issue #656 .
Manually tested through a standalone Qt application utilizing the FFI bindings at present.
* [x ] New feature (non-breaking change which adds functionality)
> FFI Bindings

- base_layer/p2p/examples/pingpong_async.rs
Does what it says on the label
> Removed commented out code from pingpong example

- base_layer/core/src/base_node/base_node.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/node_state.rs
- base_layer/core/src/lib.rs
This PR simply sketches the outline and strategy for the Tari Base
node (aka full node) implementation. In summary, we describe the
node as a FSM; that maintains blockchain state with its peers.
This PR comprises mainly documentation.
Implied in the FSM is that the node contains validation services
that it delegates to in order to validate blocks as they are received.
> Outline of base node implementation

- RFC/src/RFC-0340_VNConsensusOverview.md
- RFC/src/RFC-0500_PaymentChannels.md
> Rough draft of RFC-5000: Payment channels

- base_layer/core/src/blocks/aggregated_body.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/blocks/blockheader.rs
- base_layer/core/src/transaction.rs
Adds Derive and custom display formats for Blocks.
Very useful for debugging output during tests, and for logging.
Example output:
```text
----------------- Block -----------------
--- Header ---
Version: 0
Block height: 1
Previous block hash: 60a608a3d2ed63893417816f3d7aef6592bd1a993bf6b01fee40b602886aec66
Timestamp: Fri, 27 Sep 2019 12:29:50 +0000
Accumulated difficulty: 2
Nonce: 0
Merkle roots:
Outputs: 0000000000000000000000000000000000000000000000000000000000000000
Range proofs: 0000000000000000000000000000000000000000000000000000000000000000
Kernels: 0000000000000000000000000000000000000000000000000000000000000000
---  Body  ---
--- Transaction Kernels ---
Kernel 0:
Fee: 901 µT
Lock height: 0
Features: (empty)
Excess: 5e49d1fef88ade1e2d1e9bcfb52ba28e265d1bd4351a13ca898ef45c276ea56f …
```
> Add display for block parts

- comms/Cargo.toml
- comms/src/peer_manager/mod.rs
- comms/src/peer_manager/node_features.rs
- Added NodeFeature enum with MessagePropagation key
- Added NodeFeatures with basic methods for working with a few
NodeFeatures.
Integration with peer manager still to come.
Ref #824
> Added NodeFeature flags

- base_layer/core/Cargo.toml
- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/comms_response.rs
- base_layer/core/src/base_node/comms_interface/error.rs
- base_layer/core/src/base_node/comms_interface/inbound_interface.rs
- base_layer/core/src/base_node/comms_interface/mod.rs
- base_layer/core/src/base_node/comms_interface/outbound_interface.rs
- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/base_node/test/mod.rs
- base_layer/core/src/chain_storage/metadata.rs
- Added initial skeleton for the inbound and outbound node comms interfaces, these interfaces are compatible with the service framework.
- Added NodeCommsRequest and NodeCommsResponse for sending requests to remote nodes or handling received requests.
Enables sending and handling of remote node requests if connected to a comm service.
Added tests for an outbound get_metadata request and handling of an inbound get_metadata request.
> Inbound and Outbound node comms interface skeleton

- base_layer/p2p/examples/pingpong_async.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/liveness/service.rs
- comms/dht/src/actor.rs
- comms/dht/src/builder.rs
- comms/dht/src/config.rs
- comms/dht/src/dht.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/lib.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- comms/dht/tests/dht.rs
- comms/src/builder/builder.rs
- comms/src/connection_manager/actor.rs
- comms/src/outbound_message_service/service.rs
- comms/src/shutdown.rs
- comms/tests/outbound_message_service/service.rs
- infrastructure/test_utils/src/runtime.rs
- Added a DHT actor which is responsible for auto joining on node startup
- Dht actor can send join and discover requests
- Dht actor shuts down when comms is shut down
Closes #825 
Unit test of DHT actor
> Add DHT actor

- comms/dht/src/actor.rs
- comms/dht/src/config.rs
- comms/dht/src/dht.rs
- comms/dht/src/store_forward/error.rs
- comms/dht/src/store_forward/mod.rs
- comms/dht/src/store_forward/saf_handler/task.rs
- StoredMessageRequest is sent on node startup (unless configured not to)
- SAF message handler checks ENCRYPTED message flag
- SAF message handler allows messages sent to a network region or
directly to this node. Messages sent to the network region will
then be checked if they can be decrypted to determine if they should
be accepted or rejected.
Closes #867 
Basic unit tests
> Ask network region for stored messages on startup

- applications/tari_testnet_miner/Cargo.toml
- applications/tari_testnet_miner/src/lib.rs
- applications/tari_testnet_miner/src/main.rs
- applications/tari_testnet_miner/src/miner.rs
- base_layer/core/src/blocks/block.rs
- base_layer/core/src/proof_of_work/blake_pow.rs
- base_layer/core/src/test_utils/sample_blockchains.rs
This provides a base layout of the miner logic, required to mine.
The logic in this PR needs modification forward to ensure that it is multithreaded as its currently only single threaded. This will be addressed in a future PR
Test_net miner
Created a unit test that mines a single block. The test is not currently enabled as it can take potentially very long. This needs to be discussed.
> Miner logic

- base_layer/wallet/src/ffi.rs
- base_layer/wallet/src/lib.rs
A proposal for the public facing API that LibWallet will expose for Wallet clients.
Closes #877 
Docstring proposal
> Proposal for the Wallet public API

- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/mod.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/transaction_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
This PR Updates the wallet container struct to hold the new Async services, and remove the Text Message Service which is not needed for MVP.
Closes https://github.com/tari-project/tari/issues/876
Integration test updated
> Update Wallet container

- base_layer/p2p/src/tari_message.rs
Removed DHT and store and forward message types
Closes #912
> Clean up some unused TariMessageTypes

- applications/tari_testnet_miner/src/main.rs
- applications/tari_testnet_miner/src/miner.rs
- base_layer/core/src/proof_of_work/blake_pow.rs
This PR converts the miner to use futures to mine in async while allowing to use some control from the ui
Mining is an intensive process and we need to be able to stop this process if we receive a new block or if the user wants to cancel the process.
> Convert miner to use futures

- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/handle.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/output_manager_service/storage/memory_db.rs
- base_layer/wallet/src/output_manager_service/storage/mod.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet/src/transaction_service/mod.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/mod.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/transaction_service/mod.rs
To allow for modular implementation of different storage backends for these services a storage backend trait was implemented for each of them and an in-memory DB backend was provided. In the future it will be easy to implement multiple styles of backends without modifying the service logic.
Closes #805 
Test were updated.
> Refactor Output Manager & Tx Service with generic storage backend

- applications/tari_base_node/src/builder.rs
* db no longer needs an Arc
* Take out hardcoded host parameter to CommsConfig
* Lint fixes
> Base node bug fixes

- applications/tari_testnet_miner/Cargo.toml
- applications/tari_testnet_miner/src/lib.rs
- applications/tari_testnet_miner/src/main.rs
- applications/tari_testnet_miner/src/miner.rs
- applications/tari_testnet_miner/src/t_blake_pow.rs
Moved the algorithm over the miner app. 
Added random start position
Added overflow
Added timestamp increase if no match was found. 
Fixed futures to run completely multi-threaded.
The mining should be able to always eventually find a match. The random start position should allow multiple miners to find the matching nonce faster. 
The mining now runs on 2 threads multithreaded.
> Fixed mining algo and converted to multi-threaded. 

- base_layer/wallet_ffi/src/lib.rs
Development doesnt build, this fixed dev to build
> fix ffi wallet

- comms/src/connection_manager/actor.rs
- comms/src/connection_manager/connectivity.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/mod.rs
- comms/src/outbound_message_service/service.rs
- comms/src/test_utils/dialers.rs
- comms/tests/connection_manager/actor.rs
- Added connection manager call `get_active_connection_count`
Closes #927 
Unit test
> Added ability to query number of active connections

- applications/tari_base_node/src/builder.rs
- base_layer/core/src/base_node/test/service.rs
- base_layer/p2p/examples/pingpong.rs
- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/liveness/config.rs
- base_layer/p2p/src/services/liveness/mod.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/tests/services/liveness.rs
- base_layer/p2p/tests/support/comms_and_services.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- base_layer/wallet/tests/wallet/mod.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/broadcast_strategy.rs
- comms/src/connection_manager/actor.rs
- comms/src/connection_manager/manager.rs
- comms/src/control_service/worker.rs
- comms/src/outbound_message_service/service.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_manager.rs
- comms/src/peer_manager/peer_storage.rs
- Optionally ping nearest neighbours at a configurable interval
- This is the precursor to periodically sharing chain metadata
- Fixed an edge-case bug in OMS
- Fixed a bug in the closest/neighbour peer selection in braodcast
- Added configuration for establish connection timeout
Ref #928 
> Periodically ping nearest neighbours

- base_layer/wallet/src/contacts_service/error.rs
- base_layer/wallet/src/contacts_service/handle.rs
- base_layer/wallet/src/contacts_service/mod.rs
- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/contacts_service/storage/database.rs
- base_layer/wallet/src/contacts_service/storage/memory_db.rs
- base_layer/wallet/src/contacts_service/storage/mod.rs
- base_layer/wallet/src/lib.rs
- base_layer/wallet/tests/contacts_service/mod.rs
This PR adds a Contacts service to the wallet that can manager Contacts which are Alias’s associated with Public keys. A modular backend is provided and a InMemory DB implemented.
We need Contacts to be managed
Tests provided
* [x ] New Tests
> Add Contacts Service to the wallet

- Cargo.toml
- applications/console_text_messenger/src/main.rs
- applications/grpc_wallet/src/main.rs
- applications/grpc_wallet/tests/wallet_grpc_server/wallet_grpc_server.rs
- applications/tari_base_node/src/builder.rs
- base_layer/transactions/src/transaction_protocol/sender.rs
- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/error.rs
- base_layer/wallet/src/lib.rs
- base_layer/wallet/src/output_manager_service/mod.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/output_manager_service/storage/database.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/src/storage/memory_db.rs
- base_layer/wallet/src/storage/mod.rs
- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/output_manager_service/mod.rs
- base_layer/wallet/tests/support/utils.rs
- base_layer/wallet/tests/transaction_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- comms/src/peer_manager/node_identity.rs
- comms/tests/support/factories/node_identity.rs
- ffi/Cargo.toml
- ffi/src/lib.rs
This PR completed the core MVP wallet functionality using an in-memory DB,
Features that were added:
- Include Contacts Service
- Transaction history
- Wallet database with backend for wallet specific data
Closes #886
Closes #880
Closes #883
Closes #884
Closes #885
Closes #922
Tests Provided
> Add the MVP wallet functionality and start FFI

- .circleci/config.yml
See if this fixes the panic in the build process.
> [NO MERGE] Change `cargo check` to `cargo build`

- base_layer/wallet/tests/wallet/mod.rs
- comms/src/peer_manager/mod.rs
Fixes a broken test that was behind a feature flag and turn off a problematic doc-test
> Fixes broken test that is hidden behind feature flag

- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/proto/dht.proto
- comms/src/control_service/worker.rs
- comms/tests/connection_manager/manager.rs
- Control service validates the Node ID against the public key before a
peer is added. This is a restriction on all base nodes and wallets.
DAN nodes will need a different method of verification.
- DHT will now not propagate Join and Discovery requests from banned
peers.
TODO
> Minor security enhancements for comms/DHT

- RFC/src/Glossary.md
- RFC/src/RFC-0100_BaseLayer.md
- RFC/src/RFC-0110_BaseNodes.md
- RFC/src/RFC-0120_Consensus.md
- RFC/src/SUMMARY.md
This PR adds a consensus RFC
We currently only discuss the consensus rules in the code base and no where is this mentioned or discussed in an RFC.
> Added a consensus RFC

- base_layer/core/src/proof_of_work/lwma_diff.rs
Changed how bad timestamps are fixed
Timestamps where fixed with a` if solvetime < 1 then solvetime = 1`
This will lead to unintentional increases in difficulty if jou have one bad timestamp. 
| - | - | - | - | - | - | - | - 
| - | - | - | - | - | - | - | - 
Timestamp | 100 | 110 | 90 | 130 | 140 | | Total time passed
solvetime = 1 |   | 10 | 1 | 40 | 10 | | 61
New method |   | 10 | 1 | 19 | 10 | | 40
One bad timestamp will increase the `solvetime` of and this decrease difficulty. The new method will correctly calculate the actual time passed.
> Fixed a bug in the difficulty adjustment

- base_layer/wallet_ffi/wallet.h
Updated two function signatures in the c header that did not match the lib.
> Updated C Header Function Signatures

- RFC/src/RFC-xxxx_multi_party_transactions.md
This is work in progress RFC. 
The following is still required:
- Bulletproof explanation
- RFC number
We require multi party UTXO's in tari
> WIP RFC Multi party utxo

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/error.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Added the ability for a client application to request LibWallet write logs to a file by passing in the file path during wallet creation. If no logging is desired a null pointer can be passed.
> Add optional file based logging for LibWallet

- .gitignore
- base_layer/wallet_ffi/build.sample.config
- base_layer/wallet_ffi/mobile_build.sh
Updated build script
Created build.sample.config
Added build.config to git ignore
Updated sample config
> Updated mobile build script

- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
Errors were not being written to logs in the wallet services but now all service requests that return an error will be logged before returning the error.
> Add complete error logging to Wallet services

- base_layer/wallet_ffi/build.config
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Isolated and fixed bug in comms_config_create after additional parameter was added.
Changed wallet_get_public_key to take a wallet pointer instead of a commsconfig pointer.
Updated header for the above.
cargo-fmt
cargo test --all-features
> Updated FFI

- base_layer/wallet_ffi/build.sample.config
- base_layer/wallet_ffi/mobile_build.sh
Moved iOS build portion to top of script.
Added the sqlite dependency for Android.
Added aarch64-linux-android, i686-linux-android, x86_64-linux-android to the platforms to be built for.
> Mobile Build Script - Dependency Update

- comms/Cargo.toml
- comms/src/lib.rs
- comms/src/macros.rs
- comms/src/transports/mod.rs
- comms/src/transports/tcp.rs
- Basic async TCP transport
- Settable socketopts
- Listen and dial connections using the transport
Closes #1044 
Basic unit tests
> Tokio-based TCP transport

- comms/Cargo.toml
- comms/src/lib.rs
- comms/src/noise/config.rs
- comms/src/noise/crypto_resolver.rs
- comms/src/noise/error.rs
- comms/src/noise/mod.rs
- comms/src/noise/socket.rs
- comms/src/test_utils/tcp.rs
The noise protocol is a secure "framework" that provides a number of
handshakes to negotiate encrypted connections.
This PR implements the IX handshake protocol.  More info [here](http://www.noiseprotocol.org/noise.html).
Once the protocol is complete, the connection traffic is encrypted and peers are mutually authenticated
(i.e static public key is verified).
- Using `snow@0.6.1`
- Added `NoiseSocket` and socket upgrade process
- Added crypto resolver for Ristretto
Some code in this PR is copied/slightly modified from the libra codebase.
Closes #1045 
Unit tests
> Noise protocol (IX) implementation

- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/mocks.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/src/validation/pipeline.rs
- base_layer/core/src/validation/traits.rs
The idea of ValidationPipeline is to provide a unified approach to
validation; and one that makes testing easier as we approach full
set of consensus rules.
A validation pipeline contains a set of validators that must all
pass before the pipeline passes.
The pipeline can maintain state (such as a BlockchainDB instance)
in order to help with validation.
There are also mock validators provided so that we can keep unit tests
of different parts of the consensus model separate, without
having to rewrite tests every time we add another consesnsus rule
in development.
This also lets us keep all validation in one place, making
maintainability easier.
> Validation Pipeline

- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/transaction_service/error.rs
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/mobile_build.sh
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Implemented Error Out Parameter
Fixed bug in build script
Added additional tests
Updated documentation
cargo test --all-features
> Implemented Error Out Parameter & Minor Build Script Fix

- base_layer/core/src/base_node/test/comms_interface.rs
- base_layer/core/src/chain_storage/db_transaction.rs
- base_layer/core/src/chain_storage/memory_db.rs
- base_layer/core/src/chain_storage/test/chain_backend.rs
- base_layer/core/src/test_utils/node.rs
Implement metadata storage and fetch for Mempool_db.
Change required for blockchain synchronisation tests and building on synced chain.
Existing test modified to allow testing of both Lmdb and Memory only Metadata storage and fetching.
> Mempool_db metadata storage

- base_layer/core/src/validation/block_validators.rs
This ads the pow checking into the validation pipeline
#1093
> Add pow checking

- base_layer/core/src/blocks/block.rs
- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/validation/block_validators.rs
This adds in timestamp checking to the validation pipeline
#1094
> Add timestamp validation

- RFC/src/RFC-0120_Consensus.md
- base_layer/core/src/proof_of_work/proof_of_work.rs
Implement geometric mean for difficulty comparison
#1075 for the why this was done
This is a refactor, the unit tests have been adjusted and all tests still pass
> Implemented geomteric mean

- base_layer/core/src/validation/block_validators.rs
This checks if inputs in a block are valid utxo's that can be spent
#1092
> Check if inputs in block is valid existing utxo's

- comms/Cargo.toml
- comms/src/connection_manager/listener.rs
- comms/src/connection_manager/mod.rs
- comms/src/connection_manager/protocol.rs
- Added interactive negotiation for aritrary protocols
Closes #1050 (New issue #1158)
Only single smoke test for now
> General-purpose protocol negitiation

- base_layer/wallet_ffi/README.md
- base_layer/wallet_ffi/wallet.h
Documentation for setup (Mac) necessary to build the Tari code and then cross compile wallet_ffi for Android and iOS
Header Fixes
* [] I have updated the documentation accordingly.
> Library Build Documentation

- base_layer/core/src/mempool/mempool.rs
- base_layer/core/src/mempool/orphan_pool/orphan_pool_storage.rs
- base_layer/core/src/mempool/priority/timelocked_transaction.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/error.rs
- base_layer/core/src/validation/mod.rs
- base_layer/core/src/validation/transaction_validators.rs
- base_layer/transactions/src/transaction.rs
This PR lays the ground work for the transaction validation. It adds validators to do transaction checks on the integrity, timelocks, valid inputs. 
This change will allow us to use the validator traits like we do with block validation, just now with transactions.
> transaction validation

- base_layer/core/Cargo.toml
- base_layer/core/src/proof_of_work/monero_rx.rs
- comms/src/connection/peer_connection/connection.rs
- comms/src/lib.rs
> Fixed RandomX flag issue

- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
The mobile frontend developers require richer test data for development purposes so this PR add in more transactions with more values and spreads the timestamps out over a the last 2 weeks.
Test provided
> Update wallet test data generation with more detail and appropriate content

- .circleci/config.yml
> Bump NUM_JOBS to 3

- rustfmt.toml
Git submodule was not removed entirely
> Remove git submodule

- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/error.rs
- base_layer/core/src/mining/miner.rs
This PR adds in the Miner stub library. This PR only adds in the skeleton. The functions required to fill in the proper values will be linked in a future PR. The Miner.mine function needs to run on the same runtime as the base_node. 
The Base node will need to be able to mine
> Miner stub

- base_layer/p2p/src/initialization.rs
- base_layer/p2p/src/services/liveness/service.rs
- base_layer/p2p/src/test_utils.rs
- base_layer/wallet/tests/support/comms_and_services.rs
- comms/dht/.gitignore
- comms/dht/src/builder.rs
- comms/dht/src/config.rs
- comms/dht/src/dht.rs
- comms/dht/src/envelope.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/inbound/mod.rs
- comms/dht/src/inbound/validate.rs
- comms/dht/src/macros.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/proto/dht.proto
- comms/dht/src/proto/envelope.proto
- comms/dht/src/proto/tari.dht.envelope.rs
- comms/dht/src/proto/tari.dht.message_header.rs
- comms/dht/src/proto/tari.dht.rs
- comms/dht/src/proto/tari.dht.store_forward.rs
- comms/dht/src/test_utils/dht_actor_mock.rs
- comms/dht/src/test_utils/dht_discovery_mock.rs
- comms/dht/src/test_utils/makers.rs
- comms/dht/tests/dht.rs
- Current choice of network: MainNet, TestNet, LocalTest (local only)
- Node will explicitly reject messages from networks other than the one
for which it is configured.
Closes #1231 
Unit tests for new
> Added Network field to DHT header

- base_layer/wallet/src/contacts_service/error.rs
- base_layer/wallet/src/contacts_service/handle.rs
- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/contacts_service/storage/database.rs
- base_layer/wallet/src/contacts_service/storage/memory_db.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
This allows for  updating contact aliases without adding more calls to the API.
Tests updated
> Change `add_contact(…)` to `upsert_contact(…)` in wallet

- comms/src/connection_manager/manager.rs
Ensure Disconnect event cannot happen more than once
> Fix for race condition on simultaneous_dial_events test

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- common/src/configuration.rs
The PR adds in the wallet to the base node. 
It is not yet connected, it is only constructed and its handles are passed on. 
This will allow the basenode to claim the coinbase utxo's that where mined by it.
> Add wallet to base node

- .gitignore
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Added method to sign a message.
Added method to verify a messages signature.
Updated tests.
Updated header.
Update lib.rs
Removed re-included module form merge.
cargo-fmt
Issue #1253 
cargo test test_wallet_ffi --all-features
> Added methods to sign messages and verify signatures of messages

- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
This PR implements CompletedTransaction broadcast when the Receiver receives the finalised transaction and the initial broadcast of any pending CompletedTransactions stored in the backend on wallet startup after the base node public key is set.
Towards: #640
Test provided
> Implement wallet transaction broadcast on wallet startup and for receiver

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/miner.rs
Tidy up various compiler warnings
> Clean up warnings

- .gitignore
- base_layer/wallet_ffi/mobile_build.sh
Changed lib name to reflect crate name change.
Added generated .config file to gitignore.
wallet_ffi crate was renamed to tari_wallet_ffi
> Updated mobile_build.sh

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
This provides a mock UI with the UI layout how commands will be filled in.
This adds in auto complete and a hinter for historic commands
This provides a peek into how the UI for the Base node will work
> Basic ui layout with mock commands

- base_layer/wallet/src/transaction_service/handle.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet/tests/wallet/mod.rs
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Allow the frontend to specify the message for the faux transaction.
> Add message field to import_utxo(…)

- base_layer/wallet/Cargo.toml
- base_layer/wallet/src/util/emoji.rs
- base_layer/wallet/src/wallet.rs
- base_layer/wallet_ffi/Cargo.toml
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Added public_key_to_emoji() and public_key_from_emoji().
Added tests for emoji.
Fixed a bug in test_keys().
Refactored logic for sign_message() and verify_message_signature() into wallet.
Updated header.
Merge PR #1294 and #1295 first. Will need to resolve conflicts after that.
Emoji support for public keys.
Refactoring sign and verify logic into wallet
Fixed bug in tests
cargo test
> Emojis, Sign & Verify Refactor

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
- base_layer/wallet/src/output_manager_service/service.rs
This PR adds in the calls to the actual handles of the base node and the wallet so that the calls are are passing to the correct functions. 
This fills in the mock UI with the actual content
> Extended UI to call actual handlers of base node and wallet

- comms/Cargo.toml
- comms/src/lib.rs
- comms/src/tor/client.rs
- comms/src/tor/commands/add_onion.rs
- comms/src/tor/commands/del_onion.rs
- comms/src/tor/commands/get_conf.rs
- comms/src/tor/commands/mod.rs
- comms/src/tor/error.rs
- comms/src/tor/mod.rs
- comms/src/tor/parsers.rs
- comms/src/tor/response.rs
- comms/src/tor/test_server.rs
- comms/src/tor/types.rs
The tor control port allows an authenticated client to issue commands to
the tor proxy daemon using an SMTP-like protocol.
[Tor control port spec](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt)
This PR adds a client library with support for three commands, namely `ADD_ONION`,
`DEL_ONION` and `GET_CONF`. Further commands can be added as/when they
are needed.
Closes #1100 - This will allow zero-config tor hidden services for wallets and nodes.
Unit tests for each command using a mock server which serves canned responses. These canned responses were copied from a running tor proxy.
> Added Tor control port client module

- applications/tari_base_node/src/builder.rs
This PR adds in the initialisers for the handles that are called by the base node. Because these are created on run time in boxes, the compiler cant check that they dont exist.  
Without these initialised the basenode bin will crash on start up
> fixes bn application runtime crash

- comms/examples/tor.rs
- comms/src/builder/builder_next.rs
- comms/src/protocol/messaging/messaging.rs
- comms/src/protocol/messaging/test.rs
Added a shutdown signal to Messaging to ensure that the service shuts
down when comms shuts down.
tor example now shutdown cleanly.
Tor example shuts down cleanly
> Ensure that messaging protocol correctly shuts down

- base_layer/wallet/src/transaction_service/service.rs
Found a bug in the test functions
> Quick fix to test functions for wallet_ffi

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- common/src/configuration.rs
- comms/dht/src/actor.rs
Adds several log messages to help identify network join issues.
Deleted redundant code in the broadcast message function.
> Add peer broadcast log coverage

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- base_layer/wallet/src/storage/connection_manager.rs
- base_layer/wallet/src/storage/database.rs
- base_layer/wallet/tests/contacts_service/mod.rs
- base_layer/wallet/tests/output_manager_service/service.rs
- base_layer/wallet/tests/output_manager_service/storage.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/storage.rs
- base_layer/wallet_ffi/src/lib.rs
- common/logging/log4rs-sample.yml
- common/src/configuration.rs
- common/src/lib.rs
* Add return exit codes
* Set the default logger to output to console from info up
* Added CLI args to prompt the user to create default config data if it does not exist
* Fixed some of the default config values which were incorrect
The main aim of this PR is to smooth out the first run experience for the CLI base node. Hope it helps.
> Base Node CLI startup fixes

- base_layer/wallet_ffi/src/error.rs
Errors from different services that return the same error have been given the same code.
Re-sorted errors by code.
> Consolidated error codes

- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
Added a (hopefully) better lock for the LMDBDatabase struct. In the current implementation there is the possibility of two threads entering `write()` and interleaving, leaving the state of the in memory members (e..g `uxto_mmr`, `utxo_checkpoints`) of `LMDBDatabase` in an inconsistent state.
For example, one thread could be in `reset_mmrs()` and another in `commit_mmrs()`, resulting in some MMRs having old data and some having new data.
I think there could be more improvement to how we are utilising the LMDB transactions, but since there is also in memory state on the struct I think a lock over the whole struct is necessary
If not done, the data in memory and in the database could become corrupt and unsalvageable. 
Difficult to test, but the current tests still pass
> Prevent Multiple Threads from Writing in LMDB

- base_layer/wallet_ffi/README.md
- base_layer/wallet_ffi/build.sample.config
- base_layer/wallet_ffi/mobile_build.sh
- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Updated FFI for new Comms
Updated build script
Updated documentation
Updated readme
Added tests
Fixed test
> Updated FFI for new Comms

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/mining/miner.rs
- comms/dht/src/actor.rs
* Format several log messges to make them more readable
> Cleanup incoming node request log message

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/wallet.rs
Had some logging in the Output Manager Service set to Trace that should have been Debug.
> Upgrade Trace logs in Output Manager Service to Debug

- base_layer/wallet_ffi/wallet.h
Fixed missing const in add_base_node_peer
> Header fix

- .github/workflows/audit.yml
- .github/workflows/clippy-check.yml
* Clippy, your friendly AI code reviewer. Now in your PRs
* And at 12:15 daily, scan the dependency tree for vulnerabilities
> Add Clippy and Security udit github actions

- scripts/install_tor.sh
Tor install script for linux and mac
> Added tor install script for linux/mac

- applications/tari_base_node/src/builder.rs
- This change will allow the MempoolService to be started in base node application. 
- A base node public key is provided to the Transaction service and Output manager service allowing the transactions to be propagated and the transaction status to be requested.
This fixes two bugs on the base node application. 
> MempoolService service not running and configured base node for Transaction service and Output manager

- base_layer/p2p/src/initialization.rs
> Additional debugging messages in comms stack

- base_layer/wallet/src/transaction_service/service.rs
Added two logging statements for Tx Broadcast and Mined? requests.
> Add Logging for Tx Broadcast and Mined Request

- base_layer/core/src/base_node/chain_metadata_service/service.rs
Logs the chainmetadata when received from a peer
> Log peer metadata

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/tests/helpers/nodes.rs
- comms/src/connection_manager/dialer.rs
Add a `get_peers` command for the base node which lists the peers in its db
> Add a command to list the peers in the node's Peer DB

- applications/tari_base_node/README.md
> Updated Readme

- .github/workflows/clippy-check.yml
Added step to install all required deps for the clippy check action
> Fix install dependencies for github action

- base_layer/core/tests/wallet.rs
The updated method for waiting on the event stream is less prone to time errors.
Updated test
> Improve Wallet/Base Node integration test reliability

- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/mempool/service/service.rs
Adds the request key and error to these two messages so that they can be debugged better
> Add request key to logs for better tracing

- base_layer/core/src/base_node/service/service.rs
- base_layer/p2p/src/comms_connector/peer_message.rs
- base_layer/wallet/src/output_manager_service/error.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- common/logging/log4rs-debug-sample.yml
- comms/dht/src/dht.rs
- comms/dht/src/domain_message.rs
- comms/dht/src/envelope.rs
- comms/dht/src/inbound/message.rs
- comms/dht/src/lib.rs
- comms/dht/src/logging_middleware.rs
- comms/dht/src/outbound/message.rs
- comms/dht/src/outbound/message_params.rs
- comms/dht/src/outbound/mod.rs
- comms/dht/src/outbound/requester.rs
Add Message logging for better debugging
> Add Outbound message logging

- scripts/run_tor.sh
- Added installation for xcode, if required
- Added installation for homebrew, if required
- Runs tor with defaults that will work with default tari base node
config
A script that JustWorks(tm) to install and run tor. The user shouldn't have to install any dependencies. 
Tested on linux (from scratch)  and mac (with xcode and brew already installed).
> Tor script: instal xcode, brew and runs tor

- base_layer/wallet/src/transaction_service/service.rs
Update two log messages to be more informative
> Update Transaction Service log messages

- base_layer/core/src/mempool/service/inbound_handlers.rs
Check if a transaction is in the mempool before adding it to ensure only new transactions are propagated.
This will fix the bug where transactions are propagated in an endless loop.
None
> Fix for transaction propagation issue

- .github/PULL_REQUEST_TEMPLATE.md
Add a requirement to squash commits into a single commit for pull requests
Added a checkbox into the PULL_REQUEST_TEMPLATE.md file
Helps people remember to squash their commits so the reviewers don't have to do it,
I remembered to squash my commits for this PR
> Update PULL_REQUEST_TEMPLATE.md with squashing requirement

- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/main.rs
Added init to Arguments in cli.rs.
Added exit logic if run with create_id or init in main.rs
Issue #1427 
> Updated argument logic

- applications/tari_base_node/Cargo.toml
- common/logging/log4rs-sample.yml
Changed the default logging file. 
Added a new log4rs cargo toml files. 
We need more clearer logs
We need rolling logs, see issue: #1431
> added rolling log file config

- base_layer/p2p/Cargo.toml
- base_layer/p2p/examples/pingpong.rs
- Target dependency `[target.'cfg(not(windows))'.dev-dependencies.cursive]` added to the `p2p/Cargo.toml` file to only include Cursive as a dependency if the target is not Windows.
- Example `pingpong.rs` changed to exclude all code if the target is not Windows.
- In conjuction with @sdbondi 
Cursive is not supported on Windows, exclude its build & test when running `test --all-features`
- `cargo test --package=tari_p2p --all-features` on Windows 10 and Linux Ubuntu, build and test works on both operating systems
- `cargo run --example pingpong` on Linux Ubuntu:
```
error: The following required arguments were not provided:
--node-identity <FILE>
--remote-identity <FILE>
USAGE:
pingpong --log-config <FILE> --node-identity <FILE> --remote-identity <FILE> --tor-control-addr <TORADDR>
For …
```
> windows_compatibility_cursive_pingpong

- base_layer/core/tests/helpers/nodes.rs
These changes will fix some of the flakiness on the base node tests where a NoBootstrapNodesConfigured error is sometimes produced. When constructing a network, it will wait until the dialing between peers are complete before continuing with the rest of the tests.
Improve some of the flakiness experienced in tests where a small network of base nodes are constructed.
None
> Fix for NoBootstrapNodesConfigured base node test issue 

- RFC/src/RFC-0500_PaymentChannels.md
Remove faulty link
The Clacks white paper link is missing at the very bottom of page, picked up [here](https://twitter.com/CryptoKairos/status/1236936470406946816). As the whitepaper is still a WIP, it will be to the community at large once it goes through several more rounds of peer review, as pointed out [here](https://twitter.com/tari/status/1237060218451681280).
Ran `mdbook test` in `.\RFC`
> ho_rfc_500_update

- base_layer/wallet/src/testnet_utils.rs
- base_layer/wallet_ffi/src/error.rs
- base_layer/wallet_ffi/src/lib.rs
Made an assumption about ordering in a HashMap which was wrong 1 out of 10 times.
> Fix flakey wallet FFI test

- applications/tari_base_node/setup.sh
- applications/tari_base_node/start_tor.sh
Adds a script to download, configure and run a base node
#1428
> Base Node setup script

- base_layer/wallet_ffi/src/callback_handler.rs
Elevate log level to debug instead of trace for callback handler
Minimum log level is debug
> Elevate log level to debug instead of trace for callback handler

- base_layer/wallet/src/contacts_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
Add a couple useful log statements to Wallet
> Add more logging to wallet

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
Clean up the wallet logging formatting.
Add a couple mroe trace logs for debugging.
> Add some more logging to the wallet

- base_layer/wallet/src/util/emoji.rs
Converting from an emoji id to a pubkey is a useful utlity function that
the wallet requires.
Added `str_to_pubkey` that tries to do the conversion; and updated the
tests to use the new function.
> Add EmojiID::str_to_pubkey

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/service/error.rs
- base_layer/core/src/base_node/service/initializer.rs
- base_layer/core/src/base_node/service/mod.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/base_node/service/service_request.rs
- base_layer/core/src/base_node/service/service_response.rs
- base_layer/core/src/helpers/mod.rs
- base_layer/core/src/helpers/waiting_requests.rs
- base_layer/core/src/mempool/service/error.rs
- base_layer/core/src/mempool/service/inbound_handlers.rs
- base_layer/core/src/mempool/service/initializer.rs
- base_layer/core/src/mempool/service/mod.rs
- base_layer/core/src/mempool/service/request.rs
- base_layer/core/src/mempool/service/response.rs
- base_layer/core/src/mempool/service/service.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/wallet.rs
Reverted changes that undid work that slipped through in #1474
> Reverted inadvertant changeset reversal in #1474

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/parser.rs
- comms/src/lib.rs
- comms/src/peer_manager/node_identity.rs
```
$ Tari Base Node
$ Copyright 2019-2020. The Tari Community
$ Version 0.0.9
Press Ctrl-C to quit..
Initializing logging according to "/Users/stanleybondi/Litterbox/basenode/log1.yml"
>> whoami
Public Key: 'xxxxxxxxxxxx'
Node ID: 'xxxxxxxxxxx'
Public address: '/onion3/xxxxxxxxxxxxxxxxxxxxxxxx:18001'
Active feature flags: 'MESSAGE_PROPAGATION | DHT_STORE_FORWARD | COMMUNICATION_NODE'
```
> Added whoami command

- config/presets/rincewind-simple.toml
A very basic but "Just Works"TM config file for Rincewind testnet
> Add rincewind simple preset config

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
Fixed two logged errors that should have just been ignored.
Closes https://github.com/tari-project/tari/issues/1493
Existing tests
> Remove some incorrectly logged errors

- common/src/lib.rs
- common/src/logging.rs
Platform agnostic path tests for `tari_base_node` runtime
With the 1st node party source code changes had to be made to load config information using Tor. This is not necessary anymore, but 2x tests were added to verify the correct loading of the information.
Tested on both Linux Ubuntu and Windows 10
> platform_agnostic_path_tests_for_tari_base_node_runtime

- comms/src/multiplexing/yamux.rs
If the underlying socket was suddenly dropped on the floor by a peer
a stream of eof error messages would flood the logs. It appears as
if the yamux stream does not close immediately in this case but insteads
emits a ConnectionError:Closed. This PR will stop the inbound worker in
this case.
Bug fix
> Ensure yamux incoming worker stops if connection closed impolitely

- common/src/configuration.rs
- config/presets/rincewind-simple.toml
Update the minimal Rincewind config used by base_node_application
> Update the minimal Rincewind config used by base_node_application

- applications/tari_base_node/osx/install.sh
- applications/tari_base_node/osx/start_tor.sh
- applications/tari_base_node/start_tor.sh
- scripts/build-dists-tarball.sh
- scripts/env-sample
Script to build archive with checksums and archive chechsum for OSX and Ubuntu (other platforms too follow)
ToDo: Add RedHat/CentOS/Fedora and other Linux distro - Upload dist archive on build
> Dist build script and bits for OSX and Ubuntu

- applications/tari_base_node/src/parser.rs
Uses more idiomatic Rust in a few spots
Make the `process_command` function in parser more generic and remove
some repeated code.
> Tidy up some CLI code

- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
Adds call to get a block of certain height. 
Changes the list-header command to allow you to ask for any specific range of headers. 
This provides usability improvements for the CLI.
> CLI UI Improvements

- applications/tari_base_node/src/parser.rs
This will print out the mining state to the console
Currently the user gets no feedback as to what the mining state is and you have to look in the log files to see what the state is. This prints out the new state to the console.
> Print out the new mining state to the console

- applications/tari_base_node/src/parser.rs
* Commands are split by whitespace rather than ' ' to gracefully handle
extra spaces between arguments.
* Any remaining test after the pubkey in send-tari is treated as the tx
message
> Add custom send message to CLI wallet

- base_layer/wallet/src/output_manager_service/service.rs
Add some trace level logging to Output Manager Service to help diagnose where this service is locking up.
> Add some trace level logging to Output Manager Service

- base_layer/core/src/base_node/states/block_sync.rs
Add a series of log messages to aid in block sync debugging
> Add block synching logs

- comms/src/multiplexing/yamux.rs
- comms/src/noise/socket.rs
Edge cases for closing yamux connection
Handled edge cases for yamux inbound worker shutdown.
1. If the mpsc sender is disconnected (i.e the peer connection is
dropped)
1. If the socket enters an endless UnexpectedEof state.
This should fix the endless logging of EOFs
> Edge cases for closing yamux connection

- base_layer/core/src/blocks/genesis_block.rs
Updates the timestamp to a more recent timestamp of the gen block
We need a more updated gen block
> update gen block timestamp

- base_layer/core/tests/mining.rs
Race condition due to there sometimes not being enough time between when
the block is submitted, the transactions being moved from the
unconfirmed pool to the reorg pool and that fact being checked.
Used the old trusty `async_assert_eventually!`
> Fixed flaky mining test

- base_layer/core/src/chain_storage/blockchain_database.rs
- During chain reorganisation the original chain is restored if one of the orphan blocks in the re-org chain doesn't pass validation. 
- The Orphan block that didn't pass validation is also removed from the block orphan pool.
This will ensure the current valid chain is not removed when an invalid fork chain is encountered.
Covered by current tests.
> Restore chain if reorg block fails validation

- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/proof_of_work/diff_adj_manager/diff_adj_storage.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
- base_layer/core/tests/diff_adj_manager.rs
This PR changes the way the difficulty adjustment works. Currently it uses the achieved difficulty of a block. This means that a really strong block will make it harder for new blocks to be created. 
This is not correct. On every block there is a target difficulty and if that target difficulty is achieved in a shorter or longer than expected time, the target difficulty should be adjusted up or down proportionally to the time difference. 
For example (assuming very short block windows): 
Target difficulty is at 100, block time 60s. A block comes in with achieved difficulty 1,000,000 at 60s. Target difficulty should not change. 
Another block comes in with achieved difficulty 3,000,000, 90s after the first block. The difficulty should actually decrease to between 50-75, because the target …
> Do difficulty adjustment based on target difficulty instead of achieved difficulty

- base_layer/core/src/consensus/consensus_constants.rs
Up the initial difficulty 
The initial difficulty is way too low and needs to be increased. This increases it. Having it too low lets the miner mine a few blocks when starting up which it should not.
> Up initial difficulty

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/mod.rs
- base_layer/core/src/base_node/state_machine.rs
- base_layer/core/src/base_node/states/block_sync.rs
- base_layer/core/src/base_node/states/listening.rs
- base_layer/core/src/base_node/states/shutdown_state.rs
- base_layer/core/src/base_node/states/starting_state.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/tests/mining.rs
- base_layer/core/tests/node_state_machine.rs
- base_layer/core/tests/wallet.rs
- infrastructure/shutdown/src/lib.rs
Used a Shutdown trigger and shutdown signals.
All base node state event futures could be interrupted by the shutdown
signal.
Base node has always required a "hard" interrupt. A clean shutdown is one which allows various tasks to exit their loops/persist what they need to/politely disconnect from peers etc 
Running a base node and shutting down in various states
> Clean node shutdown

- applications/tari_base_node/src/parser.rs
- comms/src/connection_manager/error.rs
- comms/src/connection_manager/manager.rs
- comms/src/connection_manager/requester.rs
- comms/src/peer_manager/manager.rs
- comms/src/peer_manager/peer.rs
- comms/src/peer_manager/peer_storage.rs
- comms/src/test_utils/connection_manager_mock.rs
- `ban-peer [hex pk or emoji id]`
- Added disconnect peer request to connection manager
Could be a useful command and demonstrates banning a peer
Tested on base node - NOTE: seed peers will be unbanned after each node restart
> Added `ban-peer` and `unban-peer` commands

- base_layer/core/src/chain_storage/blockchain_database.rs
There is a possible that this recursive call will call lmdb recursively saturating all available read locks. The lmdb calls will now not happen recursively while the function still is.
We need to release the read locks of the lmdb database between calls. Previously this call had a potential unlimited amount of read locks required. Especially if its a long reorg. 
This is a refactor, not breaking any code.
> Fix possible recursive call to lmdb that saturates the lmdb

- applications/tari_base_node/src/cli.rs
- applications/tari_base_node/src/main.rs
- common/Cargo.toml
- common/src/configuration.rs
- common/src/dir_utils.rs
- common/src/lib.rs
- common/src/logging.rs
- infrastructure/storage/Cargo.toml
This PR fixes `test_bootstrap_config_from_cli_and_load_configuration` from deleting your ~/.tari folder. It accomplishes this by allowing the user to set a custom `base_dir` instead of forcing `~/.tari`. The cli accepts `--b|--base_dir my/custom/path` as the directory to write to.
You can specify a base directory name in the `dir_utils` functions that falls back on `.tari` if `None` is provided. This can be expanded out in later PR's with an ENV to use multiple directories on a single machine for multiple nodes.
The test was deleting the main ~/.tari folder.
I have run the tests, they no longer delete the ~/.tari folder
> Create a temp test dir to avoid deleting ~/.tari

- applications/tari_base_node/Cargo.toml
- applications/tari_base_node/src/parser.rs
Add a QR code to the `whoami` command on the base node
> Add QR to whoami command

- base_layer/core/src/transactions/helpers.rs
- base_layer/wallet/src/contacts_service/storage/sqlite_db.rs
- base_layer/wallet/src/output_manager_service/storage/sqlite_db.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
> Fix some clippy warnings

- base_layer/core/src/base_node/states/block_sync.rs
- These changes will move the base node state system to the listening state for unrecoverable comms interface errors.
- The node will retry when requests timed out and ban peers when an unexpected api response was provided.
These changes will allow the base node to return to the listening state when it is unable to query the network.
> Base node NoBootstrapNodesConfigured issue

- base_layer/core/src/mempool/mempool.rs
> Shorten some mempool log messages

- base_layer/wallet/src/output_manager_service/service.rs
Currently the wallet will choose UTXO's based on their size. This means that it might choose a UTXO that is locked for some time when there are others that are not locked. 
This PR sorts UXTOs first by their maturity, then size. Ideally the wallet should know the current height of the blockchain and then it could group any UTXO's that are unlocked together, but I don't think that information is available to the wallet at this time.
> Choose UTXOs by Maturity First, Then Smallest

- base_layer/wallet_ffi/src/lib.rs
Updated test for getting transactions by id
cargo test --all-features test_wallet_ffi
> Updated test for getting transactions by id

- base_layer/p2p/src/services/liveness/service.rs
- comms/dht/Cargo.toml
- comms/dht/examples/memorynet.rs
- comms/dht/src/actor.rs
- comms/dht/src/broadcast_strategy.rs
- comms/dht/src/config.rs
- comms/dht/src/inbound/dht_handler/task.rs
- comms/dht/src/outbound/broadcast.rs
- comms/dht/src/outbound/message_params.rs
- comms/dht/src/store_forward/forward.rs
- comms/src/peer_manager/manager.rs
- comms/src/peer_manager/node_id.rs
- comms/src/peer_manager/peer_storage.rs
Only the destination node of the discovery can open the discovery
message. This PR makes sure that every 'recently online' wallet
that the base node knows about gets a copy of every discovery message
forwarded through the base node.
This is a base node change and does not require an update to the wallet to work
Propagating to closer peers will not work for discovery propagation for wallets because there is a good chance that a wallet will never receive the discovery. This ensures that as long as that wallet can be connected to and knows at least one co-operating base node, it will receive the discovery message. 
Memorynet discovers wallets across it's network 100% of the time.
> Ensure Discovery messages are flooded to communication clients (wallets)

- comms/src/connection_manager/peer_connection.rs
Uses an Arc in PeerConnection to keep track of references to the connection.
This function will be used by connectivity manager to ensure that a peer
connection is not disconnected while being held by another service.
Function unit tested
> Add reference count to peer connection

- base_layer/core/src/chain_storage/blockchain_database.rs
The majority of this change is changing `check_for_valid_height` to use the current height from `db.fetch_last_header()` instead of the metadata. It can happen that the metadata and db height get out of sync, which prevents a number of operations. 
For example, I had block 1233-1239 in my db, but my metadata had ended up stuck at 1232 and then I was unable to sync passed 1233. 
There is clearly a bug where these two can get out of sync, but I think in general it is better to use the db as the main source of truth, and because it is local, querying the last header will be a very quick operation.
I also removed a number of `*_writelock` methods that were not public. This access can be controlled internally to BlockchainDatabase, so there is no need for the duplication, which could lead to …
> Use DB to Determine Tip Height, not Metadata

- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet_ffi/src/lib.rs
The function did not return `Imported` transactions and returned a null without an error.
> Fix `wallet_get_completed_transaction_by_id(...)` in Wallet FFI

- base_layer/core/src/transactions/tari_amount.rs
- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/storage/sqlite_db.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
- base_layer/wallet_ffi/src/callback_handler.rs
- base_layer/wallet_ffi/src/lib.rs
Replaced .find() with .any() in output_manager_service/service.rs.
Replaced let Ok(_) with is_ok() in sqlite_db.rs.
Allowed identity_op in tari_amount.rs.
Replaces unecessary clone in output_manager_service/service..rs and lib.rs.
Allowed too_many_arguments in transaction_service/service.rs and callback_handler.rs.
Replaced match logging_path_string with if let Some(path) = logging_path_string.
clippy fixes
> Clippy Fixes

- base_layer/wallet_ffi/src/error.rs
Split errors for 101, 103, 104 and 108
> Split Errors

- base_layer/wallet/src/output_manager_service/service.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet_ffi/src/lib.rs
Fix the FFI get transaction by id functions.
> Fix FFI transaction by id functions

- base_layer/wallet/src/transaction_service/service.rs
Add more logging for Transaction Service
> Add more logging for Transaction Service

- comms/dht/src/dht.rs
Windows `__chkstk` routine throws an access violation when all DHT layers are
added. It seems not to be the size of the stack, but the depth. This is
not fully understood yet. As a work around, this PR reintroduces the store
and forward layers excluded previously and excludes layers that are not
critical to a properly functioning node (namely, MessageLogging and
the filtering out of store and forward messages for mobile wallets)
> [Windows] Exclude non-critical DHT messaging layers

- README.md
Provide Windows build instructions.
- Windows build instructions were not yet documented.
- The 1st portion of the document (lines 3 to 75) has been duplicated before, which has now been fixed.
Build and tested on a Windows 10 distribution not yet used for development.
> Windows-build-instructions

- applications/tari_base_node/src/parser.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
adds two UI calls
1. searches for missing data in db
2. debug call for checking header timing. 
Fix spelling mistake in call
The first call is for searching the db to find missing headers and blocks in the database. This might point to future bugs and see if and where the db is corrupted. It would be better to add a automated call that tries to fix the missing data with remote peers. This is left for a future PR as this requires adding more comms requests. 
The second UI call is only for testing during the testnet period as this prints out the information regarding block timings.
> UI updates

- comms/src/protocol/messaging/protocol.rs
Fixed another endless error loop on substream.
Ref #1514 #1588
> Endless error loop fix in messaging

- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/p2p/src/initialization.rs
- comms/dht/src/test_utils/makers.rs
- comms/dht/tests/dht.rs
- comms/examples/tor.rs
- infrastructure/storage/src/key_val_store/lmdb_database.rs
This PR ups the size limits on all the lmdb db sizes. 
The lmdb crashes that its too small. The default limit of 10 mb has been changed to 50Gb for now.
> up all lmdb size limits

- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/state_machine.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/proof_of_work/lwma_diff.rs
Changed some logs to the correct logging detail
Changed some logs to use display and not debug
Cleaning up and making clearer logs
> Updates and fixes some logs

- base_layer/core/src/mining/miner.rs
Changes the way the miner thread handles errors. It will now just close and return itself where previously it returned errors. 
The miner will return an error which makes it crash on joining back to the main thread. If an error occurs this will mean that the basenode will need to restart work again. This PR will shutdown the miner and let it restart again so that it can try again.
> Update miner error handling

- applications/tari_base_node/src/parser.rs
If the header is missing, it will incorrectly display the wrong hash for the block. This PR is removes block hash to remove the problem. The missing block height should be sufficient to show the problem.
> fix for potential check db display problem

- applications/tari_base_node/src/parser.rs
The period calculation had an error in the minimum calculation.
This PR rewrites that calculation:
a) putting the calculation itself in a helper function.
b) using functional programming to make the logic more expressive.
c) adding a few unit tests to confirm the logic is correct (in at least one
case)
> Fix block period calculation

- base_layer/core/src/chain_storage/blockchain_database.rs
- These changes fixes an issue where the chain metadata is not correctly updated before the block validators make use of it, and would have resulted in invalid validation of blocks.
- Modified store_new_block to also update the backend metadata as well as the memory metadata when a block is added.
Fixes a bug where the block validators are using outdated chain metadata, the difficulty adjustment algorithm would also not have had the correct information.
Existing tests remain functioning.
> Fixes issue where block validation uses outdated chain metadata

- base_layer/wallet_ffi/src/lib.rs
> Added safety information

- base_layer/wallet_ffi/src/lib.rs
Increase the Discovery timeout used the wallet.
> Bump the discovery timeout to 120 seconds

- config/presets/rincewind-simple.toml
Updates the default peers in the toml file of rincewind for the new peers.
> Update the default peers

- base_layer/core/src/validation/block_validators.rs
Adds more precise logs for mmr mismatch warnings
We see a lot of mmr mismatch warning in the log, it would help if we could see which exact mmr is mismatching
> Adds more precise mmr mismatch logs

- applications/tari_base_node/src/builder.rs
- applications/tari_base_node/src/main.rs
- applications/tari_base_node/src/miner.rs
- applications/tari_base_node/src/parser.rs
- applications/tari_base_node/src/utils.rs
Initial documentation for tari-base node, added documentation where missing
> Tari Base Node Application - Documentation

- base_layer/core/src/base_node/states/block_sync.rs
This changes the log message to display why the block validation failed. Cascaded error types need to be displayed as debug to display the complete error and not just the parent.
This is only place where block validation can fail and we dont log why it fails. Block validation will return an appropriate error message to indicate why it failed. This will ensure that this error message is printed to log messages if it occurs.
> Add warn to display why block validation failed

- base_layer/wallet_ffi/README.md
* Added a few missing instructions I discovered while migrating to new
notebook
* Alternative NDK download instructions
> Update mobile build README

- base_layer/wallet/src/transaction_service/protocols/transaction_send_protocol.rs
- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/tests/transaction_service/service.rs
Fix for flaky `transaction_mempool_broadcast` test
> Fix for flaky `transaction_mempool_broadcast` test

- base_layer/wallet/src/transaction_service/service.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- base_layer/wallet/src/transaction_service/storage/memory_db.rs
- base_layer/wallet/src/transaction_service/storage/sqlite_db.rs
- base_layer/wallet/tests/transaction_service/service.rs
Previously only Outbound Txs could be cancelled. This PR updates it so that all pending Txs can be cancelled.
New test provided that creates and deletes pending Tx in both directions
> Update Transaction cancellation to work for Inbound and Outbound Txs

- comms/dht/src/dht.rs
Removed builder layer exclusions for Windows builds
Builder layer exclusions do not prevent stack overflow for `tari_base_node` in debug mode, thus not worth excluding. `tari_base_node` in release mode runs fine without any stack overflow. See #1416.
Tested in Windows 10 runtime for `tari_base_node`
> Remove builder layer exclusions for Windows builds

- base_layer/wallet/src/transaction_service/service.rs
remove log that floods log file with large unreadable message
> update log message

- base_layer/core/src/mining/miner.rs
Small fix for the miner state as it had a bug where it would get stuck on the event loop waiting for a state change.
> fix miner state

- applications/tari_base_node/src/cli.rs
Updated final char still not being displayed on windows
Windows Support
> Windows UI Compatible Char Fix

- base_layer/wallet_ffi/src/lib.rs
- base_layer/wallet_ffi/wallet.h
Fixed const correctness in header.
Removed potential future byg from test, allow_test_addresses field is not settable from outside the lib.
> Fixed header and test

- applications/tari_base_node/osx-pkg/build-pkg.sh
- applications/tari_base_node/osx-pkg/scripts/postinstall
- applications/tari_base_node/osx-pkg/scripts/preinstall
- applications/tari_base_node/osx/post-install.sh
- applications/tari_base_node/osx/uninstall-pkg.sh
Complete the basic OSX pkg build and install
scripts, plus post install which installs
XCode, brew, tor and a few brew utils for
testing and setup tor as running background
service started at login.
> OSX pkg build and install scripts

- applications/tari_base_node/src/parser.rs
- applications/tari_base_node/src/utils.rs
- base_layer/core/src/transactions/transaction.rs
- base_layer/core/src/transactions/transaction_protocol/recipient.rs
- base_layer/core/src/transactions/transaction_protocol/sender.rs
- base_layer/wallet/src/transaction_service/storage/database.rs
- comms/dht/src/dht.rs
- List inbound and outbound transactions with states to assist with
debugging
- Allow pending transactions to be cancelled
- `list-completed-transactions` lists the last 10 transactions. Specify
a single argument to return `n` transactions. Specify 2 arguments to
return `m` transactions from `n` onwards.
Listing transactions is a useful function that was missing. Being able to cancel transactions has become more important due to the possibility UTXOs being locked up while asynchronous store and forward transactions are completed. 
Tested in base node
> Added list-transactions and cancel-transaction commands

- base_layer/core/src/base_node/chain_metadata_service/handle.rs
> add display for peer meta

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/proto/request.proto
- base_layer/core/src/base_node/proto/request.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/helpers/mock_backend.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/src/proof_of_work/error.rs
- base_layer/core/src/proof_of_work/proof_of_work.rs
- base_layer/core/src/proof_of_work/target_difficulty.rs
- base_layer/core/src/proto/block.proto
- base_layer/core/src/proto/block.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/helpers/pow_blockchain.rs
- base_layer/core/tests/median_timestamp.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/target_difficulty.rs
- As the target difficulty is specified in the header the block creation process was updated. When constructing a block template the target difficulty for the selected PoW algorithm is included.
- The base node get block template request was updated to allow the PoW algorithm to be specified.
- The mining code was updated to use the target difficulty from the block template and not perform an additional request from the base node.
- The ability to query the target difficulties and timestamps from the stored headers was added to the blockchain backend and lmdb_db and memory_db implementations were provided.
- Validation of the target difficulty in the header was added to the block validation.
- The consensus constant for min_pow_difficulty was changed to allow the minimum difficulty for …
> Block header target difficulty

- base_layer/core/src/base_node/comms_interface/comms_request.rs
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/comms_interface/local_interface.rs
- base_layer/core/src/base_node/proto/request.proto
- base_layer/core/src/base_node/proto/request.rs
- base_layer/core/src/blocks/genesis_block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/lmdb_db/lmdb_db.rs
- base_layer/core/src/chain_storage/memory_db/memory_db.rs
- base_layer/core/src/chain_storage/mod.rs
- base_layer/core/src/consensus/consensus_constants.rs
- base_layer/core/src/consensus/consensus_manager.rs
- base_layer/core/src/helpers/mock_backend.rs
- base_layer/core/src/mining/blake_miner.rs
- base_layer/core/src/mining/miner.rs
- base_layer/core/src/proof_of_work/error.rs
- base_layer/core/src/proof_of_work/median_timestamp.rs
- base_layer/core/src/proof_of_work/proof_of_work.rs
- base_layer/core/src/proof_of_work/target_difficulty.rs
- base_layer/core/src/proto/block.proto
- base_layer/core/src/proto/block.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
- base_layer/core/tests/chain_storage_tests/chain_backend.rs
- base_layer/core/tests/helpers/pow_blockchain.rs
- base_layer/core/tests/median_timestamp.rs
- base_layer/core/tests/node_service.rs
- base_layer/core/tests/target_difficulty.rs
Reset Genesis block
Decouple the median timestamp calculation from the blockchain backend and ConsensusManger.
These changes added the target difficulty for a specified PoW algorithm in the block header
> V0.1  Testnet release candidate

- comms/src/peer_manager/peer.rs
Fixed off by one error in banned_until
> Off by one error in banned_until

- base_layer/core/src/blocks/block.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/src/validation/helpers.rs
Provide more granular trace logs for validation, and provide feedback on
orphan blocks when validation fails.
> More refined validation logs

- base_layer/core/src/proof_of_work/proof_of_work.rs
The target difficulty is now stored in headers. The `Display`
implementation is updated to display this field.
> Update PoW display to print new field

- base_layer/core/src/validation/helpers.rs
Fixes the incorrect error log when a valid median timestamp was generated.
An error log is produced when calculating a valid median timestamp, this change fixes the issue.
None
> Invalid median timestamp log error fix

- RFC/src/RFC-0111_BaseNodeArchitecture.md
- base_layer/core/src/base_node/comms_interface/inbound_handlers.rs
- base_layer/core/src/base_node/service/service.rs
- base_layer/core/src/chain_storage/blockchain_database.rs
- base_layer/core/src/chain_storage/error.rs
- base_layer/core/src/proof_of_work/median_timestamp.rs
- base_layer/core/src/transactions/transaction.rs
- base_layer/core/src/validation/block_validators.rs
- base_layer/core/tests/chain_storage_tests/chain_storage.rs
- base_layer/core/tests/mempool.rs
- common/config/tari_config_sample.toml
- Improved the log messages for newly received blocks, adding of blocks, reorgs and median timestamp calculation.
- Also fixed a few small language issues.
These changes will making tracking of blocks easier using the logs.
No testing required.
> Improved add block and reorg log messages

- base_layer/core/src/chain_storage/postgres_db/error.rs
- base_layer/core/src/chain_storage/postgres_db/mod.rs
- base_layer/core/src/chain_storage/postgres_db/models/kernels.rs
- base_layer/core/src/chain_storage/postgres_db/models/metadata.rs
- base_layer/core/src/chain_storage/postgres_db/models/tx_outputs.rs
- base_layer/core/src/chain_storage/postgres_db/postgres_db.rs
This introduces an initial push to the `BlockChainBackend` for postgres
All interaction to the backend storage mechanisms is though the `BlockChainBackend` trait. If we want to have postgres as a backend we need to implement the trait.  This is the initial push of this.
> impl blockchainBackend for postgres
